(function(g){var window=this;'use strict';var f0=function(Z){Z=Z.split("px");return Z.length>0?(Z=Number(Z[0]))?Z:0:0},Fud=function(Z){var u=QRd.length;
if(Z.byteLength<u)return!1;Z=new Uint8Array(Z,0,u);for(var G=0;G<u;G++)if(QRd[G]!==Z[G])return!1;return!0},ctP=function(Z,u,G){var y=[],q;
for(q in Z.j.j)if(Z.j.j.hasOwnProperty(q)){var N=Z.j.j[q];if(g.so(N,G||null)){var e=N.info.captionTrack;e&&e.languageCode===u&&y.push(N)}}return y.length?y[0]:null},TSi=function(Z,u,G){Z.u7=Z.u7||!!G;
var y={};Object.assign(y,Z.j.FB);Object.assign(y,G||u.j);Object.assign(y,Z.xi.FB);(G=!Z.K)&&gQi(Z);for(var q=Z.SD&&Z.Mu&&g.JX(y,Z.Mu)?Z.SD:wus(Z,y),N=typeof u.text==="string",e=N?u.text.split("\n"):[u.text],h=0;h<e.length;h++){var d=h>0||!u.append,K=e[h];d&&!G?(gQi(Z),q=wus(Z,y)):d&&G&&(G=!1);K&&(q.appendChild(N?g.IL(K):K),N||K.tagName!=="RUBY"||K.childElementCount!==4||g.z9||!g.B$(K.children[2],"text-emphasis")||(d=Z.T?"padding-right":"padding-top",g.B$(K.children[2],"text-emphasis-position")&&(d=
Z.T?"padding-left":"padding-bottom"),g.sG?g.O0(q,d,"1em"):g.O0(q,d,"0.5em")))}Z.Mu=y;Z.SD=q;Z.X.push(u)},ak4=function(Z,u,G){g.A(function(y){Z.j=g.Je(u,G);
g.pA(y)})},bsa=function(Z,u){Z.player.Fx(u);
u=g.m(u);for(var G=u.next();!G.done;G=u.next())g.lu(Z.SD,G.value);VE(Z.Mu)},Xj=function(Z,u,G){this.trackData=Z;
this.X=G;this.version=this.G=this.T=this.byteOffset=0;this.U=[];this.j=new DataView(this.trackData)},Ike=function(Z,u){var G="vertical-rl";
Z.j.I9===1&&(G="vertical-lr");g.ko&&(G=G==="vertical-lr"?"tb-lr":"tb-rl");g.O0(u,"-o-writing-mode",G);g.O0(u,"-webkit-writing-mode",G);g.O0(u,"writing-mode",G);g.O0(u,"text-orientation","upright");g.AM(u,"ytp-vertical-caption");Z.U.params.Ca===3&&(g.O0(u,"text-orientation",""),g.O0(u,"transform","rotate(180deg)"))},n0=function(Z,u,G){g.QX.call(this,Z);
this.videoData=u;this.audioTrack=G;this.G=u.Oj},rte=function(Z){Z.xx=Array.from(Z.element.getElementsByClassName("caption-visual-line"));
for(var u=Z.U.params.Xm,G=0,y=0,q=Z.xx.length-1;G<u&&q>-1;){var N=Z.xx[q];y+=Z.T?N.offsetWidth:N.offsetHeight;G++;q--}Z.C=y;u=Math;G=u.max;isNaN(Z.Zi)&&((y=Z.j.q$)?(q=g.Ol("SPAN"),g.vJ(q,"\u2013".repeat(y)),g.O0(q,$Vd(Z,Z.j.FB)),Z.D.appendChild(q),Z.Zi=q.offsetWidth,Z.D.removeChild(q)):Z.Zi=0);y=Z.D;Z.Qn=G.call(u,Z.Zi,Z.Qu,(Z.T?y.offsetHeight:y.offsetWidth)+1)},isP=function(Z,u){var G={},y=u.getAttribute("wp");
y&&Object.assign(G,Z.C[y]);Z=l9(u,"ap");Z!=null&&(G.vg=Z);Z=DO(u,"cc");Z!=null&&(G.q$=Z);Z=DO(u,"ah");Z!=null&&(G.Ne=Z);Z=DO(u,"rc");Z!=null&&(G.Xm=Z);u=DO(u,"av");u!=null&&(G.UL=u);return G},ZQa=function(Z){if(typeof Z==="string")return!1;
Z=new Xj(Z,8,0);return kEJ(Z)},NfJ=function(Z,u){switch(Z){case 0:return uQk[(u&127)-32];
case 1:return Gse[u&15];case 2:return yrk[u&31];case 3:return q3P[u&31]}return 0},eNa=function(Z,u,G,y,q,N){g.O.call(this);
this.policy=Z;this.player=u;this.AT=G;this.C=y;this.G=q;this.Fn=N;this.D=new MT;this.X=-1;this.U=this.T=this.j=null;this.Qn=0;this.K=new g.fy(this.VX,1E3,this);this.events=new g.Ch(this);g.M(this,this.K);g.M(this,this.events);this.events.V(u,"SEEK_COMPLETE",this.Ic);this.Ic();this.VX()},x2i=function(Z,u){return u!=null&&u in Z.j.j?Z.j.j[u]:null},JL=function(Z,u){Ys.call(this);
this.U=Z;this.D=u;this.track=this.D.languageName==="CC3"?4:0;this.j=new hNa;this.j.U=1<<this.track},d2k=function(){var Z=void 0;
Z=Z===void 0?{}:Z;var u="suggest_correction"in g.Mee?g.Mee.suggest_correction:"Edit caption";u=u||"";var G={},y;for(y in Z){G={n_:G.n_};G.n_=y;var q=function(N){return function(){return String(Z[N.n_])}}(G);
u=u.replace(new RegExp("\\$\\{"+G.n_+"\\}","gi"),q);u=u.replace(new RegExp("\\$"+G.n_,"gi"),q)}return u},KYs=function(){this.timestamp=this.j=0},fhP=function(Z){var u={};
if(Z=g.oU(Z))u.lang=Z,g.Z7e.test(Z)&&(u.Ca=1);return u},VIw=function(Z,u,G,y){var q=u/360*16;
u>=Z&&(Z=640,y>G*1.3&&(Z=480),q=G/Z*16);return q},Xqe=function(Z,u){Z.W.S("html5_modify_caption_vss_logging")&&(Z.videoData.g6=u)},EL=function(Z,u){g.QX.call(this,u);
this.j=Z;this.B=u;this.D=null;this.X=!1;this.logger=new g.ab("caps");this.K=g.CT(this.B,this.j)},MIs=function(Z){if(Z.W.qH===1||Z.videoData.Zd===1||g.lO(Z.videoData,"yt:cc")==="alwayson")return!0;
if(Z.videoData.captionTracks.length)var u=Z.getAudioTrack().U;if(Z.W.qH===2){if(g.Pv(Z.W))var G=nWe(Z);else if(Z.storage)try{G=Z.storage.get("module-enabled")}catch(q){Z.storage.remove("module-enabled")}else G=null;if(G!=null)return!!G}G=lh4(Z.player.getAudioTrack(),g.Pv(Z.W));var y=g.lO(Z.videoData,"yt:cc");if(D2P(Z)===void 0){if(G==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return y?y==="on":!0;if(G==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return y==="on"}else return y==="on";return u==="ON"||g.lO(Z.videoData,
"yt:cc")==="on"},nWe=function(Z){if(!Z.B.isInline())return g.sy("yt-player-sticky-caption")},m2J=function(Z){var u=Z.LV.getVideoContentRect(!0).height,G=Z.LV.getVideoContentRect(!0).width;
if(!u||!G)return null;u*=Z.UT.height;G*=Z.UT.width;return{width:G,height:u}},MT=function(){this.segments=[]},Y3v=function(){},Ys=function(){g.O.apply(this,arguments)},Jri=function(Z,u,G,y){for(var q=0;q<y;q++)for(var N=0;N<=32;N++){var e=Z.T[u+q][N],h=Z.T[G+q][N];
e.j=h.j;e.timestamp=h.timestamp}},EWP=function(Z){Z.style.set(4);
Z.j=Z.text;Z.j.style=Z.style;Z.T.mode=1<<Z.j.D},pqa=function(Z,u){if(u instanceof UL){var G=Z.xx[u.id];
G&&G.U!==u&&(G.dispose(),delete Z.xx[u.id],G=null);G||(G=U2J(Z,u))&&(Z.xx[u.id]=G)}else G=u.windowId,Z.sT[G]||(Z.sT[G]=[]),Z.sT[G].push(u)},HQi=function(Z){this.T=Z;
this.G=0;this.style=new p0;this.X=new Hr(this.T);this.K=new Hr(this.T);this.text=new Hr(this.T);this.U=this.X;this.D=this.K;this.j=this.U},WYk=function(Z,u){Z.j.sort(function(q,N){var e=q.time-N.time;
return e===0?q.order-N.order:e});
for(var G=g.m(Z.j),y=G.next();!y.done;y=G.next())y=y.value,Z.time=y.time,y.type===0?Bfe(Z,y.Zs,y.IH,u):y.type===1&&Z.U&496&&tIa(Z.G,y.Zs,y.IH,u);Z.j.length=0},OQv=function(Z,u,G){if(typeof u==="string"||ZQa(u))return[{trackData:u,
Y3:G}];if(typeof u==="string"&&u.substring(0,6)==="WEBVTT"||typeof u!=="string"&&Fud(u))return[{trackData:u,Y3:G}];var y=new DataView(u);if(y.byteLength<=8||y.getUint32(4)!==1718909296)return[];var q=g.$xF(y);if(Z.U&&q){var N=g.TcG(q),e=g.wn9(q);q=q.YC;N&&q&&Z.U.Xg(q,N,e)}Z=g.lP(y,1835295092);if(!Z||!Z.length||!Z[0].size)return[];N=[];for(e=0;e<Z.length;e++)q=Z[e],q=new Uint8Array(u,q.dataOffset,q.size-(q.dataOffset-q.offset)),q=g.By(q),N.push({trackData:q,Y3:G+e*1E3});jui(y,N,G);return N=N.filter(function(h){return!!h.trackData})},
ArH=function(Z,u){var G=g.Ip(Z.segments,u);
G>=0||G<0&&(-G-1)%2===1||(G=-G-1,G>0&&u-Z.segments[G-1]===1&&G<Z.segments.length&&Z.segments[G]-u===1?(g.K8(Z.segments,G),g.K8(Z.segments,G-1)):G>0&&u-Z.segments[G-1]===1?Z.segments[G-1]=u:G<Z.segments.length&&Z.segments[G]-u===1?Z.segments[G]=u:(g.Dh(Z.segments,G,0,u),g.Dh(Z.segments,G+1,0,u)))},Br=function(Z,u){g.QX.call(this,u);
this.j=Z;this.B=u;this.logger=new g.ab("caps");this.D=this.X=null;this.K=new zNH(this.B,this,this.logger,this.j.M3)},LYe=function(Z,u){Z=g.Ip(Z,{startTimeMs:u},function(G,y){return G.startTimeMs-y.startTimeMs});
return Z>=0?Z:-Z-2},vWR=function(Z,u,G,y,q,N,e){var h=N[0],d=e[h.getAttribute("p")];
if(d.OP===1){var K=N[1],f=N[2];N=N[3];h.getAttribute("t");K.getAttribute("t");f.getAttribute("t");N.getAttribute("t");h.getAttribute("p");K.getAttribute("p");N.getAttribute("p");e=e[f.getAttribute("p")];h=suv(h.textContent,K.textContent,f.textContent,N.textContent,e);return new tL(Z,u,q,G,h,y,d)}switch(d.OP){case 9:case 10:d.textEmphasis=1;break;case 11:d.textEmphasis=2;break;case 12:d.textEmphasis=3;break;case 13:d.textEmphasis=4;break;case 14:d.textEmphasis=5}return new tL(Z,u,q,G,h.textContent||
"",y,d)},j8=function(Z,u){if(!Z.j)return null;
if(Z.Fn&&Z.Fn.D)return Z.Fn.D;u=S3R(Z,u);u=g.AZ(Z.j.U,u);var G=null;if(RNH(Z.W)){var y=Z.B.isInline()?void 0:g.sy("yt-player-caption-sticky-language");for(var q=[y,Z.videoData.captionsLanguagePreference,Z.W.captionsLanguagePreference,g.lO(Z.videoData,"yt:cc_default_lang")],N=!1,e=0;e<q.length;e++){var h=q[e];if(h){N=!0;for(var d=0;d<u.length;d++)if(g.oU(u[d])===h)return u[d];for(d=0;d<u.length;d++)if(g.oU(u[d]).split("-")[0]===h.split("-")[0])return u[d]}}if(N&&Z.j&&(q=Z.j.G,q.length))for(q=g.m(q),
N=q.next();!N.done;N=q.next())if(N=N.value,N.languageCode===y){G=N;break}}else for(y=[Z.videoData.captionsLanguagePreference,Z.W.captionsLanguagePreference,g.lO(Z.videoData,"yt:cc_default_lang")],q=0;q<y.length;q++)for(N=0;N<u.length;N++)if(g.oU(u[N])===y[q])return u[N];y=null;Z.Fn&&Z.Fn.T&&(y=Z.Fn.T);y||(y=u.find(function(K){return K.isDefault})||null);
y||(y=u[0]||Wr(Z));y&&G&&g.oU(y).split("-")[0]!==G.languageCode.split("-")[0]&&(y=C1P(y,G));return y},P1s=function(Z,u){var G,y,q;
return g.A(function(N){if(N.j==1)return G=Z+"|"+u,g.S(N,g.Xs(),2);if(N.j!=3){y=N.U;if(!y)throw g.ip("gct");return g.S(N,g.V$(y),3)}q=N.U;return N.return(q.get("captions",G))})},oWe=function(Z,u,G,y,q){y===0&&(y=0x8000000000000);
var N={};u.wpWinPosId&&Object.assign(N,Z.D.get(u.wpWinPosId));u.wsWinStyleId&&Object.assign(N,Z.G.get(u.wsWinStyleId));Z=u.rcRowCount;Z!==void 0&&(N.Xm=Z);u=u.ccColCount;u!==void 0&&(N.q$=u);if(N.Ca===2||N.Ca===3)u=N.Xm,N.Xm=N.q$,N.q$=u;return new UL(G,y,0,q,N)},Quw=function(Z,u){var G=Z.B.l4().zw().textTracks;
Z=Z.U.toString();for(var y=0;y<G.length;y++){var q=G[y];q.id===Z&&(u?q.mode!=="showing"&&(q.mode="showing"):q.mode==="showing"&&(q.mode="disabled"))}},FYv=function(Z,u,G,y){y=Object.assign({Qo:0},y);
return new UL(Z,u,G,"_"+OL++,y)},gQi=function(Z){Z.K=g.Ol("SPAN");
g.O0(Z.K,{display:"block"});g.AM(Z.K,"caption-visual-line");Z.D.appendChild(Z.K)},AL=function(Z){Z=g.Oi(Math.round(Z),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-Z.length)+Z},crk=function(Z){Z.row=Z.j>0?Z.j:1;
Z.U=1;zZ(Z,0,15)},gWa=function(Z){var u="_"+OL++;
return new UL(0,0x8000000000000,0,u,Z)},Hr=function(Z){this.G=Z;
this.T=[];this.j=this.U=this.row=0;this.style=new p0;for(Z=this.D=0;Z<=15;Z++){this.T[Z]=[];for(var u=0;u<=32;u++)this.T[Z][u]=new KYs}},suv=function(Z,u,G,y,q){var N=g.JJ(),e=N?g.Ol("DIV"):g.Ol("RUBY"),h=g.Ol("SPAN");
h.textContent=Z;e.appendChild(h);Z=N?g.Ol("DIV"):g.Ol("RP");Z.textContent=u;e.appendChild(Z);u=N?g.Ol("DIV"):g.Ol("RT");u.textContent=G;e.appendChild(u);G=q.OP;if(G===10||G===11||G===12||G===13||G===14)if(g.O0(u,"text-emphasis-style","filled circle"),g.O0(u,"text-emphasis-color","currentcolor"),g.O0(u,"webkit-text-emphasis","filled circle"),q.OP===11||q.OP===13)g.O0(u,"webkit-text-emphasis-position","under left"),g.O0(u,"text-emphasis-position","under left");G=!0;if(q.OP===4||q.OP===7||q.OP===12||
q.OP===14)g.O0(e,"ruby-position","over"),g.O0(e,"-webkit-ruby-position","before");else if(q.OP===5||q.OP===6||q.OP===11||q.OP===13)g.O0(e,"ruby-position","under"),g.O0(e,"-webkit-ruby-position","after"),G=!1;q=N?g.Ol("DIV"):g.Ol("RP");q.textContent=y;e.appendChild(q);N&&(y=G,g.O0(e,{display:"inline-block",position:"relative"}),N=e.firstElementChild.nextElementSibling,g.O0(N,"display","none"),N=N.nextElementSibling,g.O0(N,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.O0(e.lastElementChild,"display","none"),y?(g.O0(e,"padding-top","0.6em"),g.O0(N,"top","0")):(g.O0(e,"padding-bottom","0.6em"),g.O0(N,"bottom","0")));return e},zZ=function(Z,u,G){for(var y=0;y<G;y++)for(var q=0;q<=32;q++)Z.T[u+y][q].reset()},wqs=function(Z){Z.style.set(1);
Z.j=Z.D;Z.j.j=0;Z.j.style=Z.style;Z.T.mode=1<<Z.j.D},Tfv=function(Z){var u=1+.25*(Z.fontSizeIncrement||0);
if(Z.offset===0||Z.offset===2)u*=.8;return u},p0=function(){this.type=0},Bfe=function(Z,u,G,y){u===255&&G===255||!u&&!G?(++Z.T===45&&Z.reset(),Z.D.U.clear(),Z.G.U.clear()):(Z.T=0,tIa(Z.D,u,G,y))},ahe=function(Z,u,G){var y=[],q;
for(q in Z.j.j)if(Z.j.j.hasOwnProperty(q)){var N=Z.j.j[q];if(g.so(N,G||null)){var e=N.info.captionTrack;e&&e.languageCode===u&&y.push(N)}}return y.length?y[0]:null},lh4=function(Z,u){return u?Z.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Ihi=function(Z,u){rte(Z);
var G=Z.xx.reduce(function(N,e){return(Z.T?e.offsetWidth:e.offsetHeight)+N},0);
G=Z.C-G;if(G!==Z.al){var y=G>0&&Z.al===0,q=G<Z.al;u||isNaN(G)||y||!q||(g.AM(Z.element,"ytp-rollup-mode"),Z.V(Z.element,"transitionend",Z.zt));g.O0(Z.D,"transform",bQJ(Z,G));Z.al=G}rte(Z)},sL=function(Z,u,G,y,q,N,e,h,d,K){L0.call(this,Z,u,G,y,q,N,e,h,d,K);
var f=this;this.type=2;this.xx=[];this.Qn=this.C=this.al=0;this.Zi=NaN;this.Qu=0;this.By=null;this.DY=new g.fy(this.zt,433,this);this.G&&(K.createClientVe(this.G,this,167342),this.V(this.G,"click",function(){K.logClick(f.G)}),Z=new g.wc(this.element,!0),g.M(this,Z),Z.subscribe("hoverstart",function(){K.logVisibility(f.G,!0)},this));
g.AM(this.element,"ytp-caption-window-rollup");g.M(this,this.DY);g.O0(this.element,"overflow","hidden")},vr=function(Z,u){if(Z.style.type===3){for(var G=0,y=0,q=Z.G.time+0,N="",e="",h=q,d=1;d<=15;++d){for(var K=!1,f=y?y:1;f<=32;++f){var V=Z.T[d][f];
if(V.j!==0){G===0&&(G=d,y=f);K=String.fromCharCode(V.j);var X=V.timestamp;X<q&&(q=X);V.timestamp=h;e&&(N+=e,e="");N+=K;K=!0}if((V.j===0||f===32)&&K){e="\n";break}else if(y&&!K)break}if(G&&!K)break}N&&u.D(G,y,q,h,N)}else for(y=G=0,N=q=Z.G.time+0,e=1;e<=15;++e)for(h="",d=1;d<=32;++d)if(f=Z.T[e][d],V=f.j,V!==0&&(G===0&&(G=e,y=d),K=String.fromCharCode(V),X=f.timestamp,X<=q&&(q=X),h+=K,f.reset()),d===32||V===0)h&&u.D(G,y,q,N,h),q=N,h="",y=G=0},S8=function(Z){var u=Z.byteOffset;
Z.byteOffset+=1;return Z.j.getUint8(u)},l9=function(Z,u){Z=DO(Z,u);
return Z!==void 0?Z:null},rrP=function(Z,u){var G=[],y;
for(y in Z.j.j)if(Z.j.j.hasOwnProperty(y)){var q=Z.j.j[y];if(g.so(q,u||null)){var N=q.info.id,e=N,h="."+N,d="",K="";if(q=q.info.captionTrack)N=q.languageCode,e=q.displayName,h=q.vssId,d=q.kind,K=q.id;else{q=N;var f=g.ofi.get(q);f==null&&(f=$2J[q]||$2J[q.replace(/-/g,"_")],g.ofi.set(q,f));q=f;e=q||e}G.push(new g.vR({id:y,languageCode:N,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:d,captionId:K}))}}return G},ksJ=function(Z,u,G){if(Z===255&&u===255||!Z&&!u)return{t5:Z,
RC:u,result:0};Z=iQe[Z];u=iQe[u];if(Z&128){var y;if(y=!(u&128))y=u,y=G.Y$()&&G.RC===y;if(y)return{t5:Z,RC:u,result:1}}else if(u&128&&1<=Z&&Z<=31)return{t5:Z,RC:u,result:2};return{t5:Z,RC:u,result:3}},ZkH=function(Z){var u,G=!((u=Z.B.l4())==null||!u.Fv());
return Z.wH&&G&&Z.D!=="LIVE"&&Z.D!=="SABR_LIVE"},uP4=function(Z,u,G){var y=Z.U,q=!1;
switch(Z.style.get()){case 4:case 1:case 2:Z.style.get()===4&&y.j>0||(vr(y,G),crk(Z.U),crk(Z.D),y.row=15,y.j=u,q=!0)}Z.style.set(3);Z.j=y;Z.j.style=Z.style;Z.T.mode=1<<y.D;q?y.U=1:y.j!==u&&(y.j>u?(vr(y,G),zZ(y,y.row-y.j,u)):y.row<u&&(u=y.j),y.j=u)},R7=function(Z){Ys.call(this);
this.X=Z;this.j=new Map;this.D=new Map;this.G=new Map;this.U=new Map},S3R=function(Z,u){g.XL(Z.videoData)&&(u=!0);
u||(u=Z.D==="TTS"?!1:Z.D==="INNERTUBE"?!1:!0);return u||Z.W.S("web_deprecate_always_includes_asr_setting")&&g.Pv(Z.W)?!0:!!g.ct().Py(66)},DO=function(Z,u){Z=Z.getAttribute(u);
if(Z!=null)return Number(Z)},GrR=function(Z){this.j=Z;
this.G=0;this.T=new HQi(this.j);this.X=new HQi(this.j);this.U=new C0;this.D=this.T},bQJ=function(Z,u){if(!u)return"";
Z.T&&Z.U.params.I9!==1&&(u*=-1);return"translate"+(Z.T?"X":"Y")+"("+u+"px)"},yvi=function(Z){var u=Z.split(":");
Z=0;u=g.m(u);for(var G=u.next();!G.done;G=u.next())Z=Z*60+Number(G.value);return Z*1E3},tIa=function(Z,u,G,y){Z.U.update();
u=ksJ(u,G,Z.U);switch(u.result){case 0:return;case 1:case 2:return}var q=u.t5;G=u.RC;if(32<=q||!q)Z.j.mode&Z.j.U&&(u=q,u&128&&(u=127),G&128&&(G=127),Z=Z.D.j,u&96&&Pr(Z,0,u),G&96&&Pr(Z,0,G),u!==0&&G!==0&&Z.style.type===3&&vr(Z,y));else if(q&16)a:if(!Z.U.matches(q,G)&&(u=Z.U,u.t5=q,u.RC=G,u.state=2,u=q&8?Z.X:Z.T,Z.D=u,Z.j.mode=1<<(Z.G<<2)+(u.G<<1)+(u.style.type===4?1:0),(Z.j.mode|1<<(Z.G<<2)+(u.G<<1)+(u.style.type!==4?1:0))&Z.j.U))if(G&64){y=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(q&7)<<1|G>>5&1];
Z=G&16?((G&14)>>1)*4:0;G=u.j;switch(u.style.get()){case 4:y=G.row;break;case 3:if(y!==G.row){if(y<G.j&&(y=G.j,y===G.row))break;var N=1+G.row-G.j,e=1+y-G.j;Jri(G,e,N,G.j);u=N;q=G.j;e<N?(N=e+q-N,N>0&&(u+=N,q-=N)):(N=N+q-e,N>0&&(q-=N));zZ(G,u,q)}}G.row=y;G.U=Z+1}else switch(q&7){case 1:switch(G&112){case 32:Pr(u.j,0,32);break a;case 48:G===57?(y=u.j,o7(y).j=0,y.U<32&&y.U++):Pr(u.j,1,G&15)}break;case 2:G&32&&Pr(u.j,2,G&31);break;case 3:G&32&&Pr(u.j,3,G&31);break;case 4:case 5:if(32<=G&&G<=47)switch(G){case 32:wqs(u);
break;case 33:y=u.j;y.U>1&&(--y.U,o7(y).j=0);break;case 36:y=u.j;u=o7(y);for(Z=0;Z<=15;Z++)for(G=0;G<=32;G++)if(y.T[Z][G]===u){for(;G<=32;G++)y.T[Z][G].reset();break}break;case 37:uP4(u,2,y);break;case 38:uP4(u,3,y);break;case 39:uP4(u,4,y);break;case 40:Pr(u.j,0,32);break;case 41:u.style.set(2);u.j=u.U;u.j.j=0;u.j.style=u.style;u.T.mode=1<<u.j.D;break;case 42:y=u.text;y.j=15;y.style.set(4);crk(y);EWP(u);break;case 43:EWP(u);break;case 44:Z=u.U;switch(u.style.get()){case 1:case 2:case 3:vr(Z,y)}zZ(Z,
0,15);break;case 45:b:{Z=u.j;switch(u.style.get()){default:case 2:case 1:break b;case 4:if(Z.row<15){++Z.row;Z.U=1;break b}break;case 3:}Z.j<2&&(Z.j=2,Z.row<Z.j&&(Z.row=Z.j));u=Z.row-Z.j+1;vr(Z,y);Jri(Z,u,u+1,Z.j-1);zZ(Z,Z.row,1)}break;case 46:zZ(u.D,0,15);break;case 47:vr(u.U,y),u.D.updateTime(u.T.time+0),y=u.D,u.D=u.U,u.U=y,wqs(u)}break;case 7:switch(G){case 33:case 34:case 35:y=u.j,(y.U+=G&3)>32&&(y.U=32)}}},qk4=function(Z,u,G){P1s(Z,u).then(function(y){y&&G(y.trackData,new g.vR(y.metadata))})},
Wr=function(Z){return Z.Fn&&Z.Fn.j},hNa=function(){this.T=this.time=this.mode=this.U=0;
this.D=new GrR(this);this.G=new GrR(this);this.j=[];this.clear()},C1P=function(Z,u){var G=new g.vR;
G.languageCode=Z.languageCode;G.languageName=Z.languageName;G.name=Z.name;G.displayName=Z.displayName;G.kind=Z.kind;G.isDefault=!1;G.j=Z.j;G.isTranslateable=Z.isTranslateable;G.vssId=Z.vssId;G.url=Z.url;G.translationLanguage=u;Z.xtags&&(G.xtags=Z.xtags);Z.captionId&&(G.captionId=Z.captionId);return G},QE=function(Z){Ys.call(this);
this.D=Z;this.pens={};this.C={};this.Fn={};this.G="_"+OL++;this.K={};this.U=this.j=null;this.X=!0},$Vd=function(Z,u){var G={},y=u.background?u.background:Z.j.FB.background;
if(u.backgroundOpacity!=null||u.background){var q=u.backgroundOpacity!=null?u.backgroundOpacity:Z.j.FB.backgroundOpacity;y=Nuv(y);G.background="rgba("+y[0]+","+y[1]+","+y[2]+","+q+")";Z.ZY&&(G["box-decoration-break"]="clone",G["border-radius"]=Z.sT/8+"px")}if(u.fontSizeIncrement!=null||u.offset!=null)G["font-size"]=Z.nV*Tfv(u)+"px";y=1;q=u.color||Z.j.FB.color;if(u.color||u.textOpacity!=null)q=Nuv(q),y=u.textOpacity==null?Z.j.FB.textOpacity:u.textOpacity,q="rgba("+q[0]+","+q[1]+","+q[2]+","+y+")",
G.color=q,G.fill=q;var N=u.charEdgeStyle;N===0&&(N=void 0);if(N){q="rgba(34, 34, 34, "+y+")";var e="rgba(204, 204, 204, "+y+")";u.Lk&&(e=q=u.Lk);var h=Z.nV/16/2,d=Math.max(h,1),K=Math.max(2*h,1),f=Math.max(3*h,1),V=Math.max(5*h,1);y=[];switch(N){case 4:for(;f<=V;f+=h)y.push(K+"px "+K+"px "+f+"px "+q);break;case 1:K=window.devicePixelRatio>=2?.5:1;for(N=d;N<=f;N+=K)y.push(N+"px "+N+"px "+q);break;case 2:y.push(d+"px "+d+"px "+e);y.push("-"+d+"px -"+d+"px "+q);break;case 3:for(f=0;f<5;f++)y.push("0 0 "+
K+"px "+q)}G["text-shadow"]=y.join(", ")}q="";switch(u.fontFamily){case 1:q='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:q='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:q='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:q='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:q='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:q=g.JJ()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:q='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}q&&(G["font-family"]=q);q=u.offset;q==null&&(q=Z.j.FB.offset);switch(q){case 0:G["vertical-align"]="sub";break;case 2:G["vertical-align"]="super"}u.fontFamily===7&&(G["font-variant"]="small-caps");u.bold&&(G["font-weight"]="bold");u.italic&&(G["font-style"]="italic");u.underline&&(G["text-decoration"]=
"underline");u.Lm1&&(G.visibility="hidden");u.pU===1&&Z.T&&(G["text-combine-upright"]="all",G["text-orientation"]="mixed",q=g.z9||g.Lq,Z.U.params.Ca===3?G.transform=q?"rotate(90deg)":"rotate(180deg)":q&&(G.transform="rotate(-90deg)"));if(u.textEmphasis===1||u.textEmphasis===2||u.textEmphasis===3||u.textEmphasis===4||u.textEmphasis===5)if(g.z9)G["font-weight"]="bold";else switch(G["text-emphasis-style"]="filled circle",G["text-emphasis-color"]="currentcolor",G["webkit-text-emphasis"]="filled circle",
u.textEmphasis){case 4:case 3:G["text-emphasis-position"]="under left";G["webkit-text-emphasis-position"]="under left";break;case 5:case 2:G["text-emphasis-position"]="over right",G["webkit-text-emphasis-position"]="over right"}return G},RNH=function(Z){return g.Pv(Z)||Z.S("web_enable_caption_language_preference_stickiness")},Pr=function(Z,u,G){u>=2&&Z.U>1&&(--Z.U,o7(Z).j=0);
var y=o7(Z);y.timestamp=Z.G.time+0;y.j=NfJ(u,G);Z.U<32&&Z.U++},cr=function(Z,u){Z=Z.getAttribute(u);
if(Z!=null)return Fj.test(Z),Z},jui=function(Z,u,G){var y=g.b_(Z,0,1836476516),q=9E4;
y&&(q=g.nZ(y)||9E4);y=0;for(var N=g.lP(Z,1836019558),e=0;e<N.length;e++){var h=N[e];e<u.length&&(h=g.b_(Z,h.dataOffset,1953653094))&&(h=g.b_(Z,h.dataOffset,1952867444))&&(h=g.DH(h)/q*1E3,e===0&&(y=h),u[e].Y3=h-y+G||G*e*1E3)}},tL=function(Z,u,G,y,q,N,e){N=N===void 0?!1:N;
e=e===void 0?null:e;g.BX.call(this,Z,Z+u,{priority:G,namespace:"captions"});this.windowId=y;this.text=q;this.append=N;this.j=e},xjw=function(Z,u,G,y){var q={};
Object.assign(q,isP(Z,u));Object.assign(q,eSw(Z,u));y?g.JX(q,Z.D)?(y=Z.G,q=Z.D):y="_"+OL++:y=u.getAttribute("id")||"_"+OL++;Z=DO(u,"t")+G;u=DO(u,"d")||0x8000000000000;if(q.Ca===2||q.Ca===3)G=q.Xm,q.Xm=q.q$,q.q$=G;return new UL(Z,u,0,y,q)},fXe=function(Z){g.gC.call(this,Z);
var u=this;this.B=Z;this.SD=[];this.xx={};this.sT={};this.C=!1;this.D="NONE";this.j=this.Fn=this.Qn=this.nV=this.JT=null;this.DY={Po:function(){u.Po()},
ib:function(N,e,h,d){u.ib(N,e,h,d)}};
this.U=null;this.W=this.B.J();this.videoData=this.B.getVideoData();this.LV=this.B.l7();this.T={FB:{}};this.X={FB:{}};g.$X(this.videoData)?this.D="OFFLINE":hSR(this.videoData,this.B)?this.D="SABR_LIVE":g.eB7(this.videoData,this.B)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.DY&&(this.D="TTS");this.wH=this.W.controlsType==="3";this.Hu=new gU(this.B,this.W);this.u7=new g.Ch(this);this.K=new g.P({Z:"div",Y:"ytp-caption-window-container",N:{id:"ytp-caption-window-container"}});
this.UT={top:0,right:0,bottom:0,left:0,width:1,height:1};var G=null,y=g.j0("yt-html5-player-modules::subtitlesModuleData");y&&(G=new g.ql(y));this.storage=G;var q;this.kx=!((q=Z.l4())==null||!q.QO());this.G=ZkH(this);this.Zi=!this.G&&this.wH&&this.kx&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.M(this,this.Hu);this.G?this.al=this.Mu=null:(this.Mu=new g.OM(this.G9,void 0,this),g.M(this,this.Mu),this.al=new g.fy(this.AdD,2E3,this),g.M(this,this.al));g.M(this,this.u7);g.l7(this.player,this.K.element,4);
g.M(this,this.K);this.G||this.u7.V(Z,"resize",this.wP);(this.Qu=g.fT(this.W)&&!g.US()&&!this.B.isFullscreen()&&!this.G&&!this.Zi)&&this.u7.V(Z,"resize",this.g$m);this.u7.V(Z,"onPlaybackAudioChange",this.Xc1);this.u7.V(Z,g.ir("captions"),function(N){u.onCueRangeEnter(N)});
this.u7.V(Z,g.kq("captions"),function(N){u.onCueRangeExit(N)});
dj4(this,Khe()||{});this.player.OE("onCaptionsModuleAvailable")},hSR=function(Z,u){if(!g.WhS(Z)||Z.j!=null&&g.CT(u,Z.j)&&Z.j.j.rawcc!=null)return!1;
u=!!Z.j&&Z.j.isManifestless&&Object.values(Z.j.j).some(function(G){return g.so(G,"386")});
Z=!!Z.j&&!Z.j.isManifestless&&g.oco(Z.j);return u||Z},zNH=function(Z,u,G,y){var q=this;
this.B=Z;this.T=u;this.logger=G;this.M3=y;this.Af=[];this.fY=[];this.j=null;this.Wy={Pon:function(){return q.j},
y5:function(){return q.Af}};
Z=g.Zh(this.B.J().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=Z>0?Z:10},C0=function(){this.state=this.RC=this.t5=0},b9=function(Z,u,G){Z.loaded&&Z.unload();
G!=null&&(Z.C=G,Z.C&&(g.Pv(Z.W)?wU(Z,!!u):TZ(Z,!!u)));u!==null||a7(Z,!0)||Z.eM(u,!!u,Z.C?"m":"s");Z.U=u;a7(Z)&&(Z.U=Wr(Z));var y;Xqe(Z,(y=Z.U)!=null?y:void 0);Z.load()},V1e=function(Z,u,G,y,q,N,e,h,d){switch(e.tagName){case "b":h.bold=!0;
break;case "i":h.italic=!0;break;case "u":h.underline=!0}for(var K=0;K<e.childNodes.length;K++){var f=e.childNodes[K];if(f.nodeType===3)f=new tL(u,G,y,q.id,f.nodeValue,N||K>0,g.fV(h)?void 0:h),d.push(f),q.j.push(f);else{var V={};Object.assign(V,h);V1e(Z,u,G,y,q,!0,f,V,d)}}},eSw=function(Z,u){var G={},y=u.getAttribute("ws");
Object.assign(G,y?Z.Fn[y]:Z.D);Z=l9(u,"mh");Z!=null&&(G.Qo=Z);Z=l9(u,"ju");Z!=null&&(G.textAlign=Z);Z=l9(u,"pd");Z!=null&&(G.Ca=Z);Z=l9(u,"sd");Z!=null&&(G.I9=Z);Z=cr(u,"wfc");Z!=null&&(G.windowColor=Z);u=DO(u,"wfo");u!==void 0&&(G.windowOpacity=u/255);return G},wus=function(Z,u){var G=g.Ol("SPAN");
g.O0(G,{display:"inline-block","white-space":"pre-wrap"});g.O0(G,$Vd(Z,u));G.classList.add("ytp-caption-segment");Z.K.appendChild(G);G.previousElementSibling&&(g.O0(G.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.O0(G,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return G},o7=function(Z){return Z.T[Z.row][Z.U]},XFa=function(Z,u){var G=[],y;
for(y in Z.j.j)if(Z.j.j.hasOwnProperty(y)){var q=Z.j.j[y];if(g.so(q,u||null)){var N=q.info.id,e=N,h="."+N,d="",K="";if(q=q.info.captionTrack)N=q.languageCode,e=q.displayName,h=q.vssId,d=q.kind,K=q.id;G.push(new g.vR({id:y,languageCode:N,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:d,captionId:K}))}}return G},a7=function(Z,u){if(Z.U&&(u===void 0||!u)||!Z.videoData.captionTracks.length)return!1;
Z=Z.getAudioTrack();return!!Z.j||Z.U==="FORCED_ON"},nnR=function(Z,u){Z.j=function(G,y){if(G.info.T){var q=G;
if(Z.fY.length>0){for(q=Z.fY.shift();Z.fY.length>0;)q=g.Qb(q,Z.fY.shift());q=g.Qb(q,G)}if(q){G=q;try{var N=g.hT(G)*1E3}catch(K){N=G.info.startTime*1E3}try{var e=g.KWo(G)*1E3}catch(K){e=G.info.duration*1E3}if(N<0||e<0)N<0&&(N=G.info.startTime*1E3),e<0&&(e=G.info.duration*1E3);G.info.startTime=N/1E3;G.info.D=N/1E3;G.info.duration=e/1E3;G.info.K=e/1E3;N=Z.Ha(q);e=N.b7;N={formatId:N.formatId,startTimeMs:N.startTimeMs,durationMs:N.durationMs,Za:e,kK:e};e=LYe(Z.Af,N.startTimeMs);var h=(G=e>=0?Z.Af[e]:null)?
G.startTimeMs+G.durationMs:0,d=N.startTimeMs+N.durationMs;!G||N.startTimeMs-h>Z.U?Z.Af.splice(e+1,0,N):(G.durationMs=Math.max(h,d)-G.startTimeMs,G.kK=Math.max(G.kK,N.kK));y(Z.Af);N=g.e5(q);y=Z.T;N=N.buffer.slice(N.byteOffset,N.byteLength+N.byteOffset);q=q.info.D;y.X?y.D==null?g.Gm(y.logger,350058965,"Null loaded track meta data at captions data received"):u.ib(N,y.D,q*1E3):g.Gm(y.logger,350058965,"Null Representation at captions data received")}else g.Gm(Z.logger,350058965,"Empty slice")}else Z.fY.push(G)};
Z.B.addEventListener("sabrCaptionsDataLoaded",Z.j)},lX4=function(Z,u){if(!Z.j)return{};
if(u){g.fV(u)||Z.po(u.vss_id,"m");if(Z.G||!g.n$(u))return;if(g.fV(u)){b9(Z,null,!0);return}for(var G,y=g.AZ(Z.j.U,!0),q=0;q<y.length;q++){var N=y[q];N.languageCode!==u.languageCode||G&&(N.languageName!==u.languageName||(N.captionId||"")!==(u.captionId||"")||g.gZ(N)!==u.displayName)||(G=u.translationLanguage?C1P(N,u.translationLanguage):N)}Z.lM(u.position);!G||G===Z.U&&Z.loaded||(u=g.z1(),y=g.oU(G),u.length&&y===u[u.length-1]||(u.push(y),g.XZ("yt-player-caption-language-preferences",u)),RNH(Z.W)&&
!Z.B.isInline()&&g.XZ("yt-player-caption-sticky-language",y,2592E3),b9(Z,G,!0))}else return Z.loaded&&Z.U&&!I7(Z)?g.wZ(Z.U):{};return""},Dje=function(Z,u,G){u&&!Z.Qn?(u=gWa({Ca:0,
lang:"en-GB"}),Z.Qn=[u,new tL(u.start,u.end-u.start,0,u.id,G!=null?G:"Captions look like this")],Z.player.JP(Z.Qn)):!u&&Z.Qn&&(bsa(Z,Z.Qn),Z.Qn=null)},$s=function(Z,u,G,y,q,N,e,h,d,K){L0.call(this,Z,u,G,y,q,N,e,h,d,K);
this.type=1},U2J=function(Z,u){var G=m2J(Z);
if(!G)return null;var y=Z.U?g.oU(Z.U):null;y&&g.Z7e.test(y)&&(u.params.Ca=1);var q=Z.LV.getPlayerSize();y=q.height*Z.UT.height;q=q.width*Z.UT.width;Z.W.playerStyle!=="google-live"||Z.T.isDefault||Object.assign(u.params,Z.T);switch(u.params.Qo!=null?u.params.Qo:u.j.length>1?1:0){case 1:return new $s(u,Z.T,Z.X,G.width,G.height,q,y,Z.W.experiments,Z.b$.bind(Z),Z.B);case 2:return new sL(u,Z.T,Z.X,G.width,G.height,q,y,Z.W.experiments,Z.b$.bind(Z),Z.B);default:return new L0(u,Z.T,Z.X,G.width,G.height,q,
y,Z.W.experiments,Z.b$.bind(Z),Z.B)}},gU=function(Z,u){g.O.call(this);
this.B=Z;this.W=u;this.j=null;this.U=this.B.Zy();this.logger=new g.ab("caps")},L0=function(Z,u,G,y,q,N,e,h,d,K){var f=K.isInline()&&!0,V={};
Object.assign(V,u);Object.assign(V,Z.params);Object.assign(V,G);var X={};Object.assign(X,u.FB);Z.params.FB&&Object.assign(X,Z.params.FB);Object.assign(X,G.FB);f&&(V.windowOpacity=.6,X.backgroundOpacity=0);V.FB=X;var n=V.Ca===1,l=[{Z:"span",Y:"captions-text",N:{style:"word-wrap: normal; display: block;"}}],Y,E,W;(h=h.i7("caption_edit_on_hover")&&((Y=K.getVideoData().getPlayerResponse())==null?void 0:(E=Y.captions)==null?void 0:(W=E.playerCaptionsTracklistRenderer)==null?void 0:W.openTranscriptCommand))&&
l.unshift({Z:"button",Y:"caption-edit",N:{tabindex:"0","aria-label":d2k()},L:[{Z:"svg",N:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},L:[{Z:"path",N:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.P.call(this,{Z:"div",Y:"caption-window",N:{id:"caption-window-"+Z.id,dir:n?"rtl":"ltr",tabindex:"0",lang:V.lang},L:l});var p=
this;this.X=[];this.u7=!1;this.U=Z;this.Mu=this.SD=null;this.Du=N;this.vy=e;this.K=null;this.maxWidth=N*.96;this.maxHeight=e*.96;this.j=V;this.xi=G;this.UT=u;this.D=this.Di("captions-text");this.ZY=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.nV=VIw(y,q,N,e);this.p8=d;h&&(this.G=this.Di("caption-edit"),this.V(this.G,"click",function(){p.p8()}));
this.type=0;this.sT=this.nV*Tfv(X);this.kx=f;Z=new g.wc(this.element,!0);g.M(this,Z);Z.subscribe("dragstart",this.ju,this);Z.subscribe("dragmove",this.oy,this);Z.subscribe("dragend",this.cU,this);this.Hu=this.wH=this.LV=this.JT=0;Z="";this.j.windowOpacity&&(Z=Nuv(this.j.windowColor),Z="rgba("+Z[0]+","+Z[1]+","+Z[2]+","+this.j.windowOpacity+")");u={"background-color":Z,display:this.j.isVisible===!1?"none":"","text-align":M1H[this.j.textAlign]};this.ZY&&(u["border-radius"]=Z?this.sT/8+"px":"");(this.T=
this.U.params.Ca===2||this.U.params.Ca===3)&&Ike(this,this.element);g.O0(this.element,u);if(f){var z;(z=this.element.parentElement)==null||z.style.setProperty("--caption-window-color",Z)}switch(this.j.vg){case 0:case 1:case 2:g.AM(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.AM(this.element,"ytp-caption-window-bottom")}},dj4=function(Z,u,G){G=G===void 0?!1:G;
var y=rU.FB;Z.T={};Object.assign(Z.T,rU);Z.T.FB={};Object.assign(Z.T.FB,y);Z.X={FB:{}};var q=u.backgroundOverride?Z.X:Z.T,N=u.background||y.background;Fj.test(N);q.FB.background=N;q=u.colorOverride?Z.X:Z.T;N=u.color||y.color;Fj.test(N);q.FB.color=N;q=u.windowColorOverride?Z.X:Z.T;N=u.windowColor||rU.windowColor;Fj.test(N);q.windowColor=N;q=u.backgroundOpacityOverride?Z.X:Z.T;N=u.backgroundOpacity;N==null&&(N=y.backgroundOpacity);q.FB.backgroundOpacity=N;q=u.fontSizeIncrementOverride?Z.X:Z.T;N=u.fontSizeIncrement;
N==null&&(N=y.fontSizeIncrement);q.FB.fontSizeIncrement=N;N=u.fontStyleOverride?Z.X:Z.T;q=u.fontStyle;q==null&&(q=y.bold&&y.italic?3:y.bold?1:y.italic?2:0);N=N.FB;switch(q){case 1:N.bold=!0;delete N.italic;break;case 2:delete N.bold;N.italic=!0;break;case 3:N.bold=!0;N.italic=!0;break;default:delete N.bold,delete N.italic}q=u.textOpacityOverride?Z.X:Z.T;N=u.textOpacity;N==null&&(N=y.textOpacity);q.FB.textOpacity=N;q=u.windowOpacityOverride?Z.X:Z.T;N=u.windowOpacity;N==null&&(N=rU.windowOpacity);q.windowOpacity=
N;q=u.charEdgeStyleOverride?Z.X:Z.T;N=u.charEdgeStyle;N==null&&(N=y.charEdgeStyle);q.FB.charEdgeStyle=N;q=u.fontFamilyOverride?Z.X:Z.T;N=u.fontFamily;N==null&&(N=y.fontFamily);q.FB.fontFamily=N;Z.loaded&&Z.wP();G&&g.XZ("yt-player-caption-display-settings",u,2592E3)},wU=function(Z,u){Z.B.isInline()||g.XZ("yt-player-sticky-caption",u,2592E3)},mja=function(Z,u){if(Z.policy.RL&&Z.player.Gv()){var G=g.r5(u,Z.policy,{});
G.set("pot",Z.player.Gv());G=G.M0()}else G=g.r5(u,Z.policy,{}).M0();var y={format:"RAW",withCredentials:!0};if(Z.policy.al){y.method="POST";var q=u.D;q&&Object.keys(q).length>0?y.postBody=g.hX(q,g.G4):y.postBody=(0,g.Zg)([120,0])}Z.G&&(y.responseType="arraybuffer");var N=++Z.Qn,e=(0,g.MJ)();Z.U=g.ET(G,y,3,100,-1,function(h){h.errorCode==="net.timeout"&&Z.player.ET("capnt",{rn:N++})}).then(function(h){if(Z.policy.g77&&N%100===1){var d=(0,g.MJ)();
Z.player.ET("caprsp",{rn:N,ms:d-e,kb:(h.xhr.responseText.length/1024).toFixed()})}a:{h=h.xhr;Z.Bu();if(Z.T){var K=!(Z.G?h.response:h.responseText)||h.status>=400;if(d=g.eRS(h)){h=g.r5(Z.T,Z.policy,{});Z.T.Xx(h,d);mja(Z,Z.T);break a}if(K)Z.player.ET("capfail",{status:h.status});else{var f;g.No("fcb_r",(0,g.MJ)(),((f=Z.player.getVideoData())==null?void 0:f.Fn)||"");f=Z.T.vu[0];d=f.b7;Z.C!=null&&Z.X!==d&&(Z.G?Z.C(h.response,(f.startTime+Z.player.N3())*1E3):Z.C(h.responseText,(f.startTime+Z.player.N3())*
1E3),Z.X=d)}}Z.T=null;Z.U=null}}).Uh(function(h){Z.T=null;
Z.U=null;var d;Z.player.ET("capfail",{rn:N,status:(d=h.xhr)==null?void 0:d.status})});
Z.T=u;ArH(Z.D,Z.T.vu[0].b7)},Khe=function(){return g.sy("yt-player-caption-display-settings")},Yki=function(Z){return Z.j&&Z.j.G?Z.j.G+Z.player.N3()<Z.player.getCurrentTime():!1},I7=function(Z){var u=Wr(Z);
return!!u&&Z.U===u},TZ=function(Z,u){if(Z.storage)try{Z.storage.set("module-enabled",u)}catch(G){}},JvP=function(){Ys.call(this)},Nuv=function(Z){if(!Ene.test(Z))throw Error("'"+Z+"' is not a valid hex color");
Z.length==4&&(Z=Z.replace(Uji,"#$1$1$2$2$3$3"));Z=Z.toLowerCase();Z=parseInt(Z.slice(1),16);return[Z>>16,Z>>8&255,Z&255]},pFJ=function(Z,u,G){Z.j||(Z.j=new JvP);
Z=Z.j.T(u,G);Math.random()<.01&&g.h6(Error("Deprecated subtitles format in web player: WebVTT"));return Z},VE=function(Z){Z.isActive()||Z.start()},i9=function(Z){var u=Z.byteOffset;
Z.byteOffset+=4;return Z.j.getUint32(u)},UL=function(Z,u,G,y,q){g.BX.call(this,Z,Z+u,{priority:G,
namespace:"captions"});this.id=y;this.params=q;this.j=[]},kEJ=function(Z){if(!(Z.byteOffset<Z.j.byteLength)||i9(Z)!==1380139777)return!1;
Z.version=S8(Z);if(Z.version>1)return!1;S8(Z);S8(Z);S8(Z);return!0},ks=function(Z,u){Z=Z.getAttribute(u);
if(Z!=null)return Z==="1"},D2P=function(Z){var u=void 0,G=g.ct().Py(65);
if(g.Pv(Z.W)&&G!=null){if(nWe(Z)!=null)return!1;u=!G}return u};
g.QX.prototype.lw=g.$r(71,function(){return!1});
g.QX.prototype.WO=g.$r(70,function(){});
g.nP.prototype.WO=g.$r(69,function(Z,u,G){var y=this;this.Bu();u=this.JG(Z,u);var q=this.KV.J().S("html5_report_captions_ctmp_qoe"),N=(0,g.MJ)();this.TQ();ak4(this,u,{format:"RAW",onSuccess:function(e){y.j=null;if(q){var h=(e.responseText.length/1024).toFixed(),d=(0,g.MJ)();y.videoData.ET("capresp",{ms:d-N,kb:h})}G.ib(e.responseText,Z)},
onError:q?function(e){var h;e=(h=e==null?void 0:e.status)!=null?h:0;y.videoData.ET("capfail",{status:e})}:void 0,
withCredentials:!0})});
g.mp.prototype.WO=g.$r(68,function(Z,u,G){var y=this;this.Bu();u=this.JG(Z,u);this.TQ();this.j=g.Je(u,{format:"RAW",onSuccess:function(q){y.j=null;G.ib(q.responseText,Z)},
withCredentials:!0})});
g.LZ.prototype.Iu=g.$r(67,function(){for(var Z=g.i4(document,"track",void 0,this.j),u=0;u<Z.length;u++)g.qr(Z[u])});
g.lZ.prototype.Iu=g.$r(66,function(){this.mediaElement.Iu()});
g.LZ.prototype.QO=g.$r(65,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.lZ.prototype.QO=g.$r(64,function(){return this.mediaElement.QO()});
g.LZ.prototype.Fv=g.$r(63,function(){return!!this.j.textTracks});
g.lZ.prototype.Fv=g.$r(62,function(){return this.mediaElement.Fv()});
g.LZ.prototype.YS=g.$r(61,function(Z){for(var u=0;u<Z.length;u++)this.j.appendChild(Z[u])});
g.lZ.prototype.YS=g.$r(60,function(Z){this.mediaElement.YS(Z)});
g.DP.prototype.Xg=g.$r(59,function(Z,u,G){this.Kn.Xg(Z,u,G)});
g.LT.prototype.Xg=g.$r(58,function(Z,u,G){this.U.set(Z,{SY:u,Uq:G})});
g.Sr.prototype.Xg=g.$r(57,function(Z,u,G){this.UT.Xg(Z,u,G)});
g.DP.prototype.s4=g.$r(56,function(Z){return this.Kn.s4(Z)});
g.Sr.prototype.s4=g.$r(55,function(Z){var u=2;this.G.has(Z)?u=0:g.jVY(this,Z)&&(u=1);return u});
g.Jk.prototype.Wb=g.$r(43,function(Z){var u=g.jX(this.app,{playerType:void 0});return u?u.Wb(Z):!1});
g.oG.prototype.Wb=g.$r(42,function(Z){return this.jD.Wd.Wb(Z)});
g.PM.prototype.Wb=g.$r(41,function(Z){return this.Ns().some(function(u){return u.namespace===Z})});
g.s1.prototype.Wb=g.$r(40,function(){return!1});
g.Jk.prototype.po=g.$r(38,function(Z,u){this.app.yn().po(Z,u)});
g.oG.prototype.po=g.$r(37,function(Z,u){this.jD.po(Z,u)});
g.jT.prototype.po=g.$r(36,function(Z,u){Z=[Z,u];g.ph(this,g.UJ(this.provider),"cfi",Z)});
g.Al.prototype.po=g.$r(35,function(Z,u){this.qoe&&this.qoe.po(Z,u)});
g.nr.prototype.po=g.$r(34,function(Z,u){this.n8.po(Z,u)});
g.s1.prototype.po=g.$r(33,function(){});
g.Jk.prototype.eM=g.$r(32,function(Z,u,G){this.app.yn().eM(Z,u,G)});
g.oG.prototype.eM=g.$r(31,function(Z,u,G){this.jD.eM(Z,u,G)});
g.jT.prototype.eM=g.$r(30,function(Z,u,G){if(this.al!==Z||this.xi!==u)u=u==="rawcc"?"":u,G=[Z,u,this.al,G],this.provider.W.hP().j.Py(g.ie)&&!this.kx&&G.push("sms.0"),g.ph(this,g.UJ(this.provider),"cfs",G),this.al=Z,this.xi=u,this.kx=!0});
g.Al.prototype.eM=g.$r(29,function(Z,u,G){this.qoe&&this.qoe.eM(Z,u,G)});
g.nr.prototype.eM=g.$r(28,function(Z,u,G){this.n8.eM(Z,u,G)});
g.s1.prototype.eM=g.$r(27,function(){});
g.Nt.prototype.F$=g.$r(12,function(){return this.G});
g.cj.prototype.F$=g.$r(11,function(){return this.yn().Zy()});
g.Jk.prototype.Zy=g.$r(10,function(){return this.app.F$()});
g.oG.prototype.Zy=g.$r(9,function(){return this.jD.Zy()});
g.nr.prototype.Zy=g.$r(8,function(){var Z;return((Z=this.loader)==null?void 0:Z.F$())||null});
g.s1.prototype.Zy=g.$r(7,function(){return null});
g.lC.prototype.BY=g.$r(1,function(Z){return(Z=this.xR(Z))?Z.j:0});
g.S9.prototype.BY=g.$r(0,function(){return 0});
var Uji=/#(.)(.)(.)/,Ene=/^#(?:[0-9a-f]{3}){1,2}$/i,$2J={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};MT.prototype.contains=function(Z){Z=g.Ip(this.segments,Z);return Z>=0||Z<0&&(-Z-1)%2===1};
MT.prototype.length=function(){return this.segments.length/2};
g.I(eNa,g.O);g.D=eNa.prototype;g.D.tT=function(){g.O.prototype.tT.call(this);this.U&&this.U.cancel()};
g.D.Ic=function(){this.seekTo(this.player.getCurrentTime())};
g.D.seekTo=function(Z){Z-=this.player.N3();var u=this.j;this.j=g.Qu(this.AT.p7(Z).vu);u!==this.j&&this.Fn&&this.Fn()};
g.D.reset=function(){this.D=new MT;this.X=-1;this.U&&(this.U.cancel(),this.U=null)};
g.D.VX=function(){this.Bu();var Z;if(Z=this.j!=null)Z=this.j,Z=Z.AT.c9(Z);if(Z&&!this.U&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){Z=this.j;Z=Z.AT.o1(Z);var u=Z.vu[0],G;if((G=this.player.getVideoData())==null?0:G.enableServerStitchedDai)if(G=this.player.Zy()){var y=u.AT.info.id,q=u.b7,N=Z.vu[0].D;if(this.policy.al){if(G=G.Xl(N,q,y,3))Z.D=G}else if(y=G.vt(N,q,y,3))if(G=G.s4(q),G===0)y&&(Z.j=new g.BY(y));else if(G===2){this.K.start();Yki(this)&&this.seekTo(this.player.getCurrentTime());
return}}u.AT.index.XU(u.b7)?(this.D.contains(Z.vu[0].b7)||mja(this,Z),this.j=g.Qu(Z.vu)):Yki(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.I(EL,g.QX);g.D=EL.prototype;g.D.WO=function(Z,u,G){var y=this;this.TQ();u=x2i(this,Z.getId());u||(u=Z.languageCode,u=this.j.isManifestless?ctP(this,u,"386"):ctP(this,u));if(u){var q=(u.index.BY(u.index.qq())-u.index.getStartTime(u.index.qq()))*1E3,N=new g.WjS(this.B.J());this.D=new eNa(N,this.B,u,function(e,h){G.ib(e,Z,h,q)},this.K||g.qE(u.info),function(){y.D&&y.D.reset();
y.X=!0})}};
g.D.lw=function(){var Z=this.X;this.X=!1;return Z};
g.D.zF=function(Z){var u=this.B.J().S("html5_fallback_if_rawcc_missing");var G=this.j.j.rawcc!=null;if(!this.K||!G&&u)u=this.j.isManifestless?rrP(this,"386"):rrP(this);else{if(!G){g.Gm(this.logger,386248249,"rawcc used but unavailable");return}u=[new g.vR({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.vR({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}u=g.m(u);
for(G=u.next();!G.done;G=u.next())g.i2(this.U,G.value);Z.Po()};
g.D.TQ=function(){this.D&&(this.D.dispose(),this.D=null)};
g.D.JG=function(){return""};
var Fj=/^#(?:[0-9a-f]{3}){1,2}$/i;var M1H=["left","right","center","justify"];g.I(L0,g.P);g.D=L0.prototype;g.D.ju=function(Z,u){this.wH=Z;this.Hu=u;var G=g.xH(this.element,this.element.parentElement);this.JT=Z-G.x;this.LV=u-G.y};
g.D.oy=function(Z,u){if(Z!==this.wH||u!==this.Hu){g.c_(this.element,"ytp-dragging")||g.AM(this.element,"ytp-dragging");var G=g.fk(this.element);Z=Z-this.JT-.02*this.Du;var y=u-this.LV-.02*this.vy,q=(Z+G.width/2)/this.maxWidth*3;q=Math.floor(g.Oi(q,0,2));var N=(y+G.height/2)/this.maxHeight*3;N=Math.floor(g.Oi(N,0,2));u=q+N*3;Z=(Z+q/2*G.width)/this.maxWidth;Z=g.Oi(Z,0,1)*100;G=(y+N/2*G.height)/this.maxHeight;G=g.Oi(G,0,1)*100;this.U.params.vg=u;this.U.params.UL=G;this.U.params.Ne=Z;this.U.params.isDefault=
!1;this.j.vg=u;this.j.UL=G;this.j.Ne=Z;this.j.isDefault=!1;this.UT.vg=u;this.UT.UL=G;this.UT.Ne=Z;this.UT.isDefault=!1;this.H$()}};
g.D.cU=function(){g.w4(this.element,"ytp-dragging")};
g.D.H$=function(){this.WJ(this.X)};
g.D.WJ=function(Z){var u=this.kx?0:Math.min(this.CO(),this.maxWidth),G=this.P1(),y=this.kx;if(y){var q=getComputedStyle(this.D.parentNode);q=f0(q.borderLeftWidth)+f0(q.borderRightWidth)+f0(q.paddingLeft)+f0(q.paddingRight)}else q=0;var N=q;q="";this.U.params.Ca===3&&(q="rotate(180deg)");var e=y?"calc(96% - "+N+"px)":"96%";g.O0(this.element,{top:0,left:0,right:"",bottom:"",width:u?u+"px":"",height:G?G+"px":"","max-width":e,"max-height":e,margin:"",transform:""});this.a7(Z);q={transform:q,top:"",left:"",
width:u?u+"px":"",height:G?G+"px":"","max-width":"","max-height":""};var h=this.j.Ne*.96+2;e=this.j.vg;switch(e){case 0:case 3:case 6:(y=this.j.FB.fontSizeIncrement)&&y>0&&this.j.Ca!==2&&this.j.Ca!==3&&(h=Math.max(h/(1+y*2),2));q.left=h+"%";break;case 1:case 4:case 7:q.left=h+"%";h=this.D.offsetWidth;u||h?(u=u||h+1,q.width=u+"px",q["margin-left"]=y?u/-2-N/2+"px":u/-2+"px"):q.transform+=" translateX(-50%)";break;case 2:case 5:case 8:q.right=100-h+"%"}y=this.j.UL*.96+2;switch(e){case 0:case 1:case 2:q.top=
y+"%";break;case 3:case 4:case 5:q.top=y+"%";(G=G||this.element.clientHeight)?(q.height=G+"px",q["margin-top"]=G/-2+"px"):q.transform+=" translateY(-50%)";break;case 6:case 7:case 8:q.bottom=100-y+"%"}g.O0(this.element,q);if(this.G){G=this.D.offsetHeight;y=1;for(u=0;u<Z.length;u++)q=Z[u],typeof q.text==="string"&&(y+=q.text.split("\n").length-1,q.append||u===0||y++);G/=y;this.G.style.height=G+"px";this.G.style.width=G+"px";this.element.style.paddingLeft=G+5+"px";this.element.style.paddingRight=G+
5+"px";Z=Number(this.element.style.marginLeft.replace("px",""))-G-5;G=Number(this.element.style.marginRight.replace("px",""))-G-5;this.element.style.marginLeft=Z+"px";this.element.style.marginRight=G+"px"}};
g.D.a7=function(Z){var u;for(u=0;u<Z.length&&Z[u]===this.X[u];u++);if(this.u7||this.X.length>u)u=0,this.u7=!1,this.X=[],this.K=this.Mu=this.SD=null,g.Cz(this.D);for(;u<Z.length;u++)TSi(this,Z[u])};
g.D.CO=function(){return 0};
g.D.P1=function(){return 0};
g.D.toString=function(){return g.P.prototype.toString.call(this)};hNa.prototype.clear=function(){this.T=this.time=this.mode=0;this.j=[];this.reset()};
hNa.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var iQe=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];p0.prototype.set=function(Z){this.type=Z};
p0.prototype.get=function(){return this.type};
C0.prototype.clear=function(){this.state=0};
C0.prototype.update=function(){this.state=this.state===2?1:0};
C0.prototype.Y$=function(){return this.state!==0};
C0.prototype.matches=function(Z,u){return this.Y$()&&Z===this.t5&&u===this.RC};
KYs.prototype.reset=function(){this.timestamp=this.j=0};
Hr.prototype.updateTime=function(Z){for(var u=1;u<=15;++u)for(var G=1;G<=32;++G)this.T[u][G].timestamp=Z};
Hr.prototype.debugString=function(){for(var Z="\n",u=1;u<=15;++u){for(var G=1;G<=32;++G){var y=this.T[u][G];Z=y.j===0?Z+"_":Z+String.fromCharCode(y.j)}Z+="\n"}return Z};
Hr.prototype.reset=function(Z){for(var u=0;u<=15;u++)for(var G=0;G<=32;G++)this.T[u][G].reset();this.D=Z;this.j=0;this.U=this.row=1};
var uQk=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Gse=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],yrk=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],q3P=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];HQi.prototype.reset=function(Z,u){this.G=u;this.style.set(2);this.U=this.X;this.D=this.K;this.j=this.U;var G=(Z<<2)+(u<<1);this.X.reset(G);this.K.reset(G);this.text.reset((Z<<2)+(u<<1)+1)};
GrR.prototype.reset=function(Z){this.G=Z;this.U.clear();this.D=this.T;this.T.reset(Z,0);this.X.reset(Z,1)};Y3v.prototype.D=function(){};g.I(tL,g.BX);tL.prototype.toString=function(){return g.BX.prototype.toString.call(this)};g.I(Ys,g.O);Ys.prototype.reset=function(){};g.I(UL,g.BX);UL.prototype.toString=function(){return g.BX.prototype.toString.call(this)};
var OL=0;g.I(QE,Ys);QE.prototype.reset=function(){this.K={};this.U=this.j=null;this.X=!0};
QE.prototype.T=function(Z,u){Z=Z.firstChild;Z.getAttribute("format");u=u||0;Number.isFinite(u);Z=Array.from(Z.childNodes);Z=g.m(Z);for(var G=Z.next();!G.done;G=Z.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "head":var y=G;break;case "body":var q=G}if(y)for(y=Array.from(y.childNodes),y=g.m(y),Z=y.next();!Z.done;Z=y.next())if(Z=Z.value,Z.nodeType===1)switch(Z.tagName){case "pen":G=Z.getAttribute("id");var N=this.pens,e={},h=Z.getAttribute("p");h&&Object.assign(e,this.pens[h]);h=ks(Z,"b");
h!=null&&(e.bold=h);h=ks(Z,"i");h!=null&&(e.italic=h);h=ks(Z,"u");h!=null&&(e.underline=h);h=l9(Z,"et");h!=null&&(e.charEdgeStyle=h);h=l9(Z,"of");h!=null&&(e.offset=h);h=cr(Z,"bc");h!=null&&(e.background=h);h=cr(Z,"ec");h!=null&&(e.Lk=h);h=cr(Z,"fc");h!=null&&(e.color=h);h=l9(Z,"fs");h!=null&&h!==0&&(e.fontFamily=h);h=DO(Z,"sz");h!==void 0&&(e.fontSizeIncrement=h/100-1);h=DO(Z,"bo");h!==void 0&&(e.backgroundOpacity=h/255);h=DO(Z,"fo");h!==void 0&&(e.textOpacity=h/255);h=l9(Z,"rb");h!=null&&h!==10&&
h!==0&&(e.OP=h>10?h-1:h);Z=l9(Z,"hg");Z!=null&&(e.pU=Z);N[G]=e;break;case "ws":G=Z.getAttribute("id");this.Fn[G]=eSw(this,Z);break;case "wp":G=Z.getAttribute("id"),this.C[G]=isP(this,Z)}if(q){y=[];q=Array.from(q.childNodes);q=g.m(q);for(Z=q.next();!Z.done;Z=q.next())if(Z=Z.value,Z.nodeType===1)switch(Z.tagName){case "w":this.j=xjw(this,Z,u,!1);(Z=this.K[this.j.id])&&Z.end>this.j.start&&(Z.end=this.j.start);this.K[this.j.id]=this.j;y.push(this.j);break;case "p":var d=Z;h=u;G=[];N=d.getAttribute("w")||
this.G;e=!!ks(d,"a");h=(DO(d,"t")||0)+h;var K=DO(d,"d")||5E3;e||(!this.X&&this.U&&this.U.windowId===N&&this.U.end>h&&(this.U.end=h),this.U&&this.U.text==="\n"&&(this.U.text=""));var f=e?6:5,V=d.getAttribute("p");V=V?this.pens[V]:null;var X=Array.from(d.childNodes);X.length&&(this.X=d.getAttribute("d")!=null);for(d=0;d<X.length;d++){var n=X[d],l=void 0;d>0&&(e=!0);var Y=void 0;n.nodeType===1&&(Y=n);if(Y&&Y.tagName==="s"){if((n=(n=Y.getAttribute("p"))?this.pens[n]:null)&&n.OP&&(n.OP===1?(n=X.slice(d,
d+4),n.length===4&&(l=vWR(h,K,N,e,f,n,this.pens),d+=3)):l=vWR(h,K,N,e,f,[Y],this.pens)),!l){var E=Y;l=h;Y=K;n=N;var W=e,p=f,z=E.textContent?E.textContent:"",L=E.getAttribute("p");L=L?this.pens[L]:null;E=DO(E,"t")||0;l=new tL(l+E,Y-E,p,n,z,W,L)}}else l=new tL(h,K,f,N,n.textContent||"",e,V);G.push(l);this.U=l}if(G.length>0)for(G[0].windowId===this.G&&(this.j=xjw(this,Z,u,!0),y.push(this.j)),Z=g.m(G),G=Z.next();!G.done;G=Z.next())G=G.value,G.windowId=this.j.id,this.j.j.push(G),y.push(G)}u=y}else u=[];
return u};var Hkv=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.I(R7,Ys);R7.prototype.reset=function(){this.U.clear()};
R7.prototype.T=function(Z,u){var G=JSON.parse(Z);if(!G)return[];if(G.pens){Z=0;for(var y=g.m(G.pens),q=y.next();!q.done;q=y.next()){q=q.value;var N={},e=q.pParentId;e&&Object.assign(N,this.j.get(e));q.bAttr&&(N.bold=!0);q.iAttr&&(N.italic=!0);q.uAttr&&(N.underline=!0);e=q.ofOffset;e!=null&&(N.offset=e);q.szPenSize!==void 0&&(N.fontSizeIncrement=q.szPenSize/100-1);e=q.etEdgeType;e!=null&&(N.charEdgeStyle=e);q.ecEdgeColor!==void 0&&(N.Lk=AL(q.ecEdgeColor));e=q.fsFontStyle;e!=null&&e!==0&&(N.fontFamily=
e);q.fcForeColor!==void 0&&(N.color=AL(q.fcForeColor));q.foForeAlpha!==void 0&&(N.textOpacity=q.foForeAlpha/255);q.bcBackColor!==void 0&&(N.background=AL(q.bcBackColor));q.boBackAlpha!==void 0&&(N.backgroundOpacity=q.boBackAlpha/255);(e=q.rbRuby)&&e!==10&&(N.OP=e>10?e-1:e,N.textEmphasis=Hkv.get(N.OP));q.hgHorizGroup&&(N.pU=q.hgHorizGroup);this.j.set(Z++,N)}}if(G.wsWinStyles)for(Z=0,y=g.m(G.wsWinStyles),q=y.next();!q.done;q=y.next())q=q.value,N={},(e=q.wsParentId)?Object.assign(N,this.G.get(e)):Object.assign(N,
this.X),q.mhModeHint!==void 0&&(N.Qo=q.mhModeHint),q.juJustifCode!==void 0&&(N.textAlign=q.juJustifCode),q.pdPrintDir!==void 0&&(N.Ca=q.pdPrintDir),q.sdScrollDir!==void 0&&(N.I9=q.sdScrollDir),q.wfcWinFillColor!==void 0&&(N.windowColor=AL(q.wfcWinFillColor)),q.wfoWinFillAlpha!==void 0&&(N.windowOpacity=q.wfoWinFillAlpha/255),this.G.set(Z++,N);if(G.wpWinPositions)for(Z=0,y=g.m(G.wpWinPositions),q=y.next();!q.done;q=y.next())q=q.value,N={},(e=q.wpParentId)&&Object.assign(N,this.D.get(e)),q.ahHorPos!==
void 0&&(N.Ne=q.ahHorPos),q.apPoint!==void 0&&(N.vg=q.apPoint),q.avVerPos!==void 0&&(N.UL=q.avVerPos),q.ccCols!==void 0&&(N.q$=q.ccCols),q.rcRows!==void 0&&(N.Xm=q.rcRows),this.D.set(Z++,N);if(G.events){Z=[];G=g.m(G.events);for(y=G.next();!y.done;y=G.next()){var h=y.value;q=(h.tStartMs||0)+u;N=h.dDurationMs||0;if(h.id)e=String(h.id),y=oWe(this,h,q,N,e),Z.push(y),this.U.set(e,y);else{h.wWinId?e=h.wWinId.toString():(e="_"+OL++,y=oWe(this,h,q,N,e),Z.push(y),this.U.set(e,y));y=Z;var d=h;N===0&&(N=5E3);
h=this.U.get(e);var K=!!d.aAppend,f=K?6:5,V=d.segs,X=null;d.pPenId&&(X=this.j.get(d.pPenId));for(d=0;d<V.length;d++){var n=V[d],l=n.utf8;if(l){var Y=n.tOffsetMs||0,E=null;n.pPenId&&(E=this.j.get(n.pPenId));if((h.params.Qo!=null?h.params.Qo:h.j.length>1?1:0)===2&&K&&l==="\n")continue;n=null;var W=[],p;if(p=E&&E.OP===1){p=V;var z=d;if(z+3>=p.length||!p[z+1].pPenId||!p[z+2].pPenId||!p[z+3].pPenId)p=!1;else{var L=p[z+1].pPenId;(L=this.j.get(L))&&L.OP&&L.OP===2?(L=p[z+2].pPenId,L=this.j.get(L),!L||!L.OP||
L.OP<3?p=!1:(L=p[z+3].pPenId,p=(L=this.j.get(L))&&L.OP&&L.OP===2?!0:!1)):p=!1}}if(p)Y=V[d+1].utf8,n=V[d+3].utf8,p=V[d+2].utf8,z=this.j.get(V[d+2].pPenId),l=suv(l,Y,p,n,z),n=new tL(q,N,f,e,l,K,E),d+=3;else{if(l.indexOf("<")>-1){var Q=void 0;W=E;p=X;z=q;L=N;var b=Y,w=f,yv=K,x9=[],qS=g.T1("<html>"+l+"</html>");if(!qS.getElementsByTagName("parsererror").length&&((Q=qS.firstChild)==null?0:Q.childNodes.length))for(Q=g.m(qS.firstChild.childNodes),qS=Q.next();!qS.done;qS=Q.next()){qS=qS.value;var K7=void 0,
GR=void 0,ED=(GR=(K7=qS.textContent)==null?void 0:K7.replace(/\n/g,""))!=null?GR:"";if(qS.nodeType!==3||ED&&ED.match(/^ *$/)==null){K7={};Object.assign(K7,W||p);GR=void 0;switch((GR=qS)==null?void 0:GR.tagName){case "b":K7.bold=!0;break;case "i":K7.italic=!0;break;case "u":K7.underline=!0}x9.push(new tL(z+b,L-b,w,h.id,ED,yv,K7))}}W=x9}W.length||(W=[new tL(q+Y,N-Y,f,h.id,l,K,E||X)])}if(W.length)for(K=g.m(W),E=K.next();!E.done;E=K.next())E=E.value,y.push(E),h.j.push(E);else n&&(y.push(n),h.j.push(n))}K=
!0}}}u=Z}else u=[];return u};g.I(n0,g.QX);n0.prototype.WO=function(Z,u,G){qk4(this.videoData.videoId,Z.vssId,G.ib)};
n0.prototype.zF=function(Z){if(this.audioTrack)for(var u=g.m(this.audioTrack.captionTracks),G=u.next();!G.done;G=u.next())g.i2(this.U,G.value);Z.Po()};g.I($s,L0);$s.prototype.a7=function(Z){var u=this.U.j;L0.prototype.a7.call(this,Z);for(Z=Z.length;Z<u.length;Z++){var G=u[Z];if(N&&G.j===q)var y=N;else{y={};Object.assign(y,G.j);Object.assign(y,Buw);var q=G.j;var N=y}TSi(this,G,y)}};
var Buw={Lm1:!0};g.I(Xj,Y3v);Xj.prototype.D=function(Z,u,G,y,q){if(G<y){var N="_"+OL++;G=G/1E3-this.X;y=y/1E3-this.X;Z=new UL(G,y-G,5,N,{textAlign:0,vg:0,Ne:u*2.5,UL:Z*5.33});q=new tL(G,y-G,5,N,q);this.U.push(Z);this.U.push(q)}};
g.I(JL,Ys);JL.prototype.T=function(Z){Z=new Xj(Z,Z.byteLength,this.U);if(kEJ(Z)){for(;Z.byteOffset<Z.j.byteLength;)for(Z.version===0?Z.T=i9(Z)*(1E3/45):Z.version===1&&(Z.T=i9(Z)*4294967296+i9(Z)),Z.G=S8(Z);Z.G>0;Z.G--){var u=S8(Z),G=S8(Z),y=S8(Z);u&4&&(u&3)===this.track&&(this.track===0||this.track===1)&&(u=this.j,u.j.push({time:Z.T,type:this.track,Zs:G,IH:y,order:u.j.length}))}WYk(this.j,Z);return Z.U}return[]};
JL.prototype.reset=function(){this.j.clear()};g.I(sL,L0);g.D=sL.prototype;g.D.H$=function(){g.Ec(this.DY)};
g.D.zt=function(){this.element.removeEventListener("transitionend",this.zt,!1);g.w4(this.element,"ytp-rollup-mode");this.WJ(this.By,!0)};
g.D.P1=function(){return this.T?this.Qn:this.C};
g.D.CO=function(){return this.T?this.C:this.Qn};
g.D.WJ=function(Z,u){this.By=Z;if(this.U.params.Xm){for(var G=0,y=0;y<this.X.length&&G<Z.length;y++)this.X[y]===Z[G]&&G++;G>0&&G<Z.length&&(Z=this.X.concat(Z.slice(G)));this.Qu=this.Qn;this.C=this.Qn=0;L0.prototype.WJ.call(this,Z);Ihi(this,u)}L0.prototype.WJ.call(this,Z)};zNH.prototype.unload=function(){this.j!=null&&(this.B.removeEventListener("sabrCaptionsDataLoaded",this.j),this.j=null);this.Af=[];this.B.publish("sabrCaptionsBufferedRangesUpdated",this.Af)};
zNH.prototype.Ha=function(Z){return{formatId:g.bd(Z.info.AT.info,this.M3),b7:Z.info.b7+(this.M3?0:1),startTimeMs:Z.info.D*1E3,durationMs:Z.info.K*1E3}};g.I(Br,g.QX);Br.prototype.WO=function(Z,u,G){this.TQ();u=Z.getId();u=u!=null&&u in this.j.j?this.j.j[u]:null;u||(u=Z.languageCode,u=this.j.isManifestless?ahe(this,u,"386"):ahe(this,u));u&&(this.D=Z,this.X=u,nnR(this.K,G),this.B.publish("sabrCaptionsTrackChanged",g.bd(u.info,this.j.M3)))};
Br.prototype.zF=function(Z){var u=this.j.isManifestless?XFa(this,"386"):XFa(this);u=g.m(u);for(var G=u.next();!G.done;G=u.next())g.i2(this.U,G.value);Z.Po()};
Br.prototype.TQ=function(){this.D&&(this.D=this.X=null,this.K.unload(),this.B.publish("sabrCaptionsTrackChanged",null))};
Br.prototype.JG=function(){return""};var QRd="WEBVTT".split("").map(function(Z){return Z.charCodeAt(0)});
g.I(JvP,Ys);
JvP.prototype.T=function(Z,u){Z instanceof ArrayBuffer&&(Z=g.By(new Uint8Array(Z)));var G=[];Z=Z.split(t1e);for(var y=1;y<Z.length;y++){var q=Z[y],N=u;if(q!==""&&!WhP.test(q)){var e=jgk.exec(q);if(e&&e.length>=4){var h=yvi(e[1]),d=yvi(e[2])-h;h+=N;var K=(e=e[3])?e.split(" "):[];e={};var f=null;var V="";var X=null,n="";K=g.m(K);for(var l=K.next();!l.done;l=K.next())if(l=l.value.split(":"),l.length===2){var Y=l[1];switch(l[0]){case "line":l=Y.split(",");l[0].endsWith("%")&&(f=l[0],e.UL=Number.parseInt(f,
10),l.length===2&&(V=l[1].trim()));break;case "position":l=Y.split(",");X=l[0];e.Ne=Number.parseInt(X,10);l.length===2&&(n=l[1].trim());break;case "align":switch(Y){case "start":e.textAlign=0;break;case "middle":e.textAlign=2;break;case "end":e.textAlign=1}}}f||V||(V="end");if(!X)switch(e.textAlign){case 0:e.Ne=0;break;case 1:e.Ne=100;break;case 2:e.Ne=50}if(e.textAlign!=null){f=0;switch(V){case "center":f+=3;break;case "end":f+=6;break;default:f+=0}switch(n){case "line-left":f+=0;break;case "center":f+=
1;break;case "line-right":f+=2;break;default:switch(e.textAlign){case 0:f+=0;break;case 2:f+=1;break;case 1:f+=2}}V=f<0||f>8?7:f;e.vg=V}q=q.substring(jgk.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");n=e;e=q;q={};if(e.indexOf("<")<0&&e.indexOf("&")<0)N=FYv(h,d,5,n),d=new tL(h,d,5,N.id,e,!1,g.fV(q)?void 0:q),G.push(N),G.push(d),N.j.push(d);else for(V=e.split(Oke),V.length===1?(e=5,n=FYv(h,d,e,n)):(f=e=6,n=Object.assign({q$:32},n),n=new UL(h,d,f,"_"+OL++,n)),G.push(n),f=h,X=0;X<V.length;X++)K=V[X],
X%2===0?(l=g.T1("<html>"+K+"</html>"),l.getElementsByTagName("parsererror").length?(Y=l.createElement("span"),Y.appendChild(l.createTextNode(K))):Y=l.firstChild,V1e(this,f,d-(f-h),e,n,X>0,Y,q,G)):f=yvi(K)+N}jgk.lastIndex=0}}return G};
var WhP=/^NOTE/,t1e=/(?:\r\n|\r|\n){2,}/,jgk=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Oke=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.I(gU,g.O);gU.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
gU.prototype.reset=function(){this.j&&this.j.reset()};
gU.prototype.tT=function(){g.O.prototype.tT.call(this);this.clear()};var rU={windowColor:"#080808",windowOpacity:0,textAlign:2,vg:7,Ne:50,UL:100,isDefault:!0,FB:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.I(fXe,g.gC);g.D=fXe.prototype;g.D.tT=function(){if(this.G||this.Zi){var Z=this.B.l4();Z&&!Z.Bu()&&Z.Iu()}else Dje(this,!1);g.gC.prototype.tT.call(this)};
g.D.k9=function(){return this.W.S("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"};
g.D.aY=function(){if(this.wH)return this.G||this.Zi;var Z=this.getAudioTrack();if(this.k9()){if(!Z.captionTracks.length)return!1;if(!this.j)return!0}Z=lh4(Z,g.Pv(this.W));return Z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:Z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?a7(this):D2P(this)||a7(this)?!0:MIs(this)};
g.D.load=function(){g.gC.prototype.load.call(this);this.Fn=this.getAudioTrack();if(this.j)this.U&&(this.Hu.clear(),this.G?Quw(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.WO(this.U,"json3",this.DY),this.G||this.Zi||I7(this)||this.player.OE("captionschanged",g.wZ(this.U)));else{var Z;this.D==="OFFLINE"?Z=new n0(this.player,this.videoData,this.getAudioTrack()):this.D==="SABR_LIVE"?Z=new Br(this.videoData.j,this.player):this.D==="LIVE"?Z=new EL(this.videoData.j,this.player):this.D==="INNERTUBE"?
Z=new g.nP(this.player,this.videoData,this.getAudioTrack()):Z=new g.mp(this.player,this.videoData.DY,this.videoData.videoId,g.mHY(this.videoData),this.videoData.BF,this.videoData.eventId);this.j=Z;g.M(this,this.j);this.j.zF(this.DY)}};
g.D.unload=function(){this.G&&this.U?Quw(this,!1):(this.al&&g.Uc(this.al),this.player.fK("captions"),this.SD=[],this.j&&this.j.TQ(),this.Hu.clear(),this.Qn&&this.player.JP(this.Qn),this.wP());g.gC.prototype.unload.call(this);this.player.l1();this.player.OE("captionschanged",{})};
g.D.create=function(){this.aY()&&this.load();var Z;a:{var u,G,y;if(this.W.S("web_player_nitrate_promo_tooltip")&&((u=this.videoData.getPlayerResponse())==null?0:(G=u.captions)==null?0:(y=G.playerCaptionsTracklistRenderer)==null?0:y.enableTouchCaptionsNitrate)){var q,N;if(u=(Z=this.videoData.getPlayerResponse())==null?void 0:(q=Z.captions)==null?void 0:(N=q.playerCaptionsTracklistRenderer)==null?void 0:N.captionTracks)for(Z=g.m(u),q=Z.next();!q.done;q=Z.next())if(q=q.value,q.kind==="asr"&&q.languageCode===
"en"){Z=!0;break a}}Z=!1}Z&&this.B.publish("showpromotooltip",this.K.element)};
g.D.Po=function(){var Z=lh4(this.player.getAudioTrack(),g.Pv(this.W));var u=Z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?j8(this,this.C):Z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&a7(this)?Wr(this):D2P(this)||this.C||MIs(this)?j8(this,this.C):a7(this)?Wr(this):null;if(this.G||this.Zi){var G=g.AZ(this.j.U,!0);Z=[];for(var y=0;y<G.length;y++){var q=G[y],N=g.Ol("TRACK");N.setAttribute("kind","subtitles");N.setAttribute("label",g.gZ(q));N.setAttribute("srclang",g.oU(q));N.setAttribute("id",q.toString());
this.Zi||N.setAttribute("src",this.j.JG(q,"vtt"));q===u&&N.setAttribute("default","1");Z.push(N)}u=this.B.l4();u.YS(Z);Z=u.zw();this.kx&&this.u7.V(Z.textTracks,"change",this.AWn)}else!this.U&&u&&b9(this,u),this.player.OE("onCaptionsTrackListChanged"),this.player.SN("onApiChange")};
g.D.AWn=function(){for(var Z=this.B.l4().zw().textTracks,u=null,G=0;G<Z.length;G++)if(Z[G].mode==="showing")a:{u=g.AZ(this.j.U,!0);for(var y=0;y<u.length;y++)if(u[y].toString()===Z[G].id){u=u[y];break a}u=null}(this.loaded?this.U:null)!==u&&b9(this,u,!0)};
g.D.iaH=function(){!this.U&&this.G||this.unload()};
g.D.ib=function(Z,u,G,y){if(Z){var q;Xqe(this,(q=this.U)!=null?q:void 0);this.j.lw()&&(this.SD=[],this.B.fK("captions"),VE(this.Mu),this.Hu.reset());a:{q=this.Hu;y=y||0;G=OQv(q,Z,G||0);Z=[];try{for(var N=g.m(G),e=N.next();!e.done;e=N.next()){var h=e.value,d=h.trackData,K=h.Y3,f=q.W.S("safari_live_drm_captions_fix");if(typeof d!=="string"){G=Z;var V=G.concat;if(f&&Fud(d))var X=pFJ(q,d,K);else{var n=q,l=u,Y=d,E=K,W=y;if(!ZQa(Y))throw Error("Invalid binary caption track data");n.j||(n.j=new JL(W,l));
X=n.j.T(Y,E)}var p=V.call(G,X)}else{if(d.substring(0,6)==="WEBVTT")var z=Z.concat(pFJ(q,d,K));else{G=Z;var L=G.concat;b:{l=n=void 0;Y=q;E=u;if(d[0]==="{")try{Y.j||(Y.j=new R7(fhP(E)));var Q=l=Y.j.T(d,K);break b}catch(GR){g.SE(GR);Q=[];break b}var b=g.T1(d);if(!b||!b.firstChild){var w=Error("Invalid caption track data");w.params=d;throw w;}if(b.firstChild.tagName==="timedtext"){if(Number(b.firstChild.getAttribute("format"))===3){Y.j||(Y.j=new QE(fhP(E),Y.W));Q=n=Y.j.T(b,K);break b}var yv=Error("Unsupported subtitles format in web player (Format2)");
yv.params=d;throw yv;}if(b.firstChild.tagName==="transcript"){var x9=Error("Unsupported subtitles format in web player (Format1)");x9.params=d;throw x9;}var qS=Error("Invalid caption track data");qS.params=d;throw qS;}z=L.call(G,Q)}p=z}Z=p}var K7=Z;break a}catch(GR){g.Gm(q.logger,187101178,"Captions parsing failed: "+GR.message+". ");q.clear();K7=[];break a}K7=void 0}u=K7;u.length>0&&(K7=this.U,this.eM(K7,!!K7,I7(this)?"g":this.C?"m":"s"));this.player.JP(u,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");
!this.C||this.Zi||I7(this)||g.xK(this.W)||g.ZQ(this.W)||g.MO(this.W)||this.W.xx==="shortspage"||this.player.isInline()||(g.Uc(this.al),u=gWa({vg:0,Ne:5,UL:5,Xm:2,textAlign:0,Ca:0,lang:"en-GB"}),this.nV=[u],K7=["Click "," for settings"],this.JT||(N=new g.Dw(g.OqF()),g.M(this,N),this.JT=N.element),N=u.end-u.start,(e=g.gZ(this.U))&&this.nV.push(new tL(u.start,N,0,u.id,e)),this.nV.push(new tL(u.start,N,0,u.id,K7[0]),new tL(u.start,N,0,u.id,this.JT,!0),new tL(u.start,N,0,u.id,K7[1],!0)),this.player.JP(this.nV),
g.Rg(this.al));!this.C||this.Zi||I7(this)||(g.Pv(this.W)?wU(this,!0):TZ(this,!0),this.Fn&&(this.Fn.D=this.U),this.player.l1());this.C=!1}};
g.D.onCueRangeEnter=function(Z){this.SD.push(Z);VE(this.Mu)};
g.D.onCueRangeExit=function(Z){g.lu(this.SD,Z);this.j instanceof EL&&this.j.K&&this.player.Fx([Z]);VE(this.Mu)};
g.D.getCaptionWindowContainerId=function(){return this.K.element.id};
g.D.AdD=function(){bsa(this,this.nV);this.nV=null};
g.D.G9=function(){var Z=this;if(!this.Qu||!this.G){this.Mu.stop();g.vlt(this.sT);this.SD.sort(g.Nc);var u=this.SD;if(this.Qn){var G=g.kn(u,function(N){return this.Qn.indexOf(N)===-1},this);
G.length&&(u=G)}u=g.m(u);for(G=u.next();!G.done;G=u.next())pqa(this,G.value);u=g.m(Object.entries(this.xx));var y=u.next();for(G={};!y.done;G={MR:void 0,aS:void 0},y=u.next()){var q=g.m(y.value);y=q.next().value;q=q.next().value;G.MR=y;G.aS=q;this.sT[G.MR]?(G.aS.element.parentNode||(G.aS instanceof sL||G.aS instanceof $s||g.Vu(this.xx,function(N){return function(e,h){h!==N.MR&&e.U.params.vg===N.aS.U.params.vg&&e.U.params.Ne===N.aS.U.params.Ne&&e.U.params.UL===N.aS.U.params.UL&&(e.dispose(),delete Z.xx[h]);
return h===N.MR}}(G),this),this.K.element.appendChild(G.aS.element)),G.aS.WJ(this.sT[G.MR])):(G.aS.dispose(),delete this.xx[G.MR])}}};
g.D.qXm=function(){dj4(this,{},!0);this.player.OE("captionssettingschanged")};
g.D.ExT=function(){var Z=rU.FB;Z={background:Z.background,backgroundOpacity:Z.backgroundOpacity,charEdgeStyle:Z.charEdgeStyle,color:Z.color,fontFamily:Z.fontFamily,fontSizeIncrement:Z.fontSizeIncrement,fontStyle:Z.bold&&Z.italic?3:Z.bold?1:Z.italic?2:0,textOpacity:Z.textOpacity,windowColor:rU.windowColor,windowOpacity:rU.windowOpacity};var u=Khe()||{};u.background!=null&&(Z.background=u.background);u.backgroundOverride!=null&&(Z.backgroundOverride=u.backgroundOverride);u.backgroundOpacity!=null&&
(Z.backgroundOpacity=u.backgroundOpacity);u.backgroundOpacityOverride!=null&&(Z.backgroundOpacityOverride=u.backgroundOpacityOverride);u.charEdgeStyle!=null&&(Z.charEdgeStyle=u.charEdgeStyle);u.charEdgeStyleOverride!=null&&(Z.charEdgeStyleOverride=u.charEdgeStyleOverride);u.color!=null&&(Z.color=u.color);u.colorOverride!=null&&(Z.colorOverride=u.colorOverride);u.fontFamily!=null&&(Z.fontFamily=u.fontFamily);u.fontFamilyOverride!=null&&(Z.fontFamilyOverride=u.fontFamilyOverride);u.fontSizeIncrement!=
null&&(Z.fontSizeIncrement=u.fontSizeIncrement);u.fontSizeIncrementOverride!=null&&(Z.fontSizeIncrementOverride=u.fontSizeIncrementOverride);u.fontStyle!=null&&(Z.fontStyle=u.fontStyle);u.fontStyleOverride!=null&&(Z.fontStyleOverride=u.fontStyleOverride);u.textOpacity!=null&&(Z.textOpacity=u.textOpacity);u.textOpacityOverride!=null&&(Z.textOpacityOverride=u.textOpacityOverride);u.windowColor!=null&&(Z.windowColor=u.windowColor);u.windowColorOverride!=null&&(Z.windowColorOverride=u.windowColorOverride);
u.windowOpacity!=null&&(Z.windowOpacity=u.windowOpacity);u.windowOpacityOverride!=null&&(Z.windowOpacityOverride=u.windowOpacityOverride);return Z};
g.D.Yg=function(Z,u){var G={};Object.assign(G,Khe());Object.assign(G,Z);dj4(this,G,u);this.player.OE("captionssettingschanged")};
g.D.wP=function(){!this.G&&this.loaded&&(g.Re(this.xx,function(Z,u){Z.dispose();delete this.xx[u]},this),this.G9())};
g.D.ox=function(Z,u){switch(Z){case "fontSize":if(isNaN(u))break;Z=g.Oi(u,-2,4);this.Yg({fontSizeIncrement:Z});return Z;case "reload":u&&!this.G&&b9(this,this.U,!0);break;case "stickyLoading":u!==void 0&&this.W.C&&(g.Pv(this.W)?wU(this,!!u):TZ(this,!!u));break;case "track":return lX4(this,u);case "tracklist":return this.j?g.gA(g.AZ(this.j.U,!(!u||!u.includeAsr)),function(G){return g.wZ(G)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(G){return Object.assign({},G)}):[];
case "sampleSubtitles":this.G||u===void 0||Dje(this,!!u);break;case "sampleSubtitlesCustomized":this.G||Dje(this,!!u,u);break;case "recommendedTranslationLanguages":return g.z1();case "defaultTranslationSourceTrackIndices":return this.j?this.j.C:[]}};
g.D.getOptions=function(){var Z="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.C&&Z.push("stickyLoading");return Z};
g.D.sz=function(){var Z=this.U;if(this.B.Wb("captions")){if(this.W.S("html5_modify_caption_vss_logging")){var u;return(Z=(u=this.videoData.g6)!=null?u:null)?{cc:g.LIq(Z)}:{}}if(Z)return u=Z.vssId,Z.translationLanguage&&u&&(u="t"+u+"."+g.oU(Z)),{cc:u}}return{}};
g.D.Sxu=function(){this.isSubtitlesOn()?(g.Pv(this.W)?wU(this,!1):TZ(this,!1),Xqe(this),b9(this,null,!0)):this.oQ()};
g.D.oQ=function(){var Z=I7(this)||!this.U?j8(this,!0):this.U;Z&&this.po(Z.vssId,"m");this.isSubtitlesOn()||b9(this,I7(this)||!this.U?j8(this,!0):this.U,!0)};
g.D.isSubtitlesOn=function(){return!!this.loaded&&!!this.U&&!I7(this)};
g.D.Xc1=function(){var Z=I7(this);a7(this,Z)?b9(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.k9()&&(this.C=!1,this.U=null,this.j&&(this.j.dispose(),this.j=null)),this.aY()&&(Z?b9(this,j8(this,!1),!1):this.load()))};
g.D.lM=function(Z){Z&&(this.UT={top:Z.top,right:Z.right,bottom:Z.bottom,left:Z.left,width:1-Z.left-Z.right,height:1-Z.top-Z.bottom},this.K.element.style.top=this.UT.top*100+"%",this.K.element.style.left=this.UT.left*100+"%",this.K.element.style.width=this.UT.width*100+"%",this.K.element.style.height=this.UT.height*100+"%",this.K.element.style.position="absolute",Z=m2J(this))&&(this.K.element.style.width=Z.width+"px",this.K.element.style.height=Z.height+"px")};
g.D.onVideoDataChange=function(Z,u){Z==="newdata"&&(this.videoData=u,this.loaded&&this.unload(),this.C=!1,this.U=null,this.j&&(this.j.dispose(),this.j=null,this.player.OE("captionschanged",{})),this.aY()&&this.load())};
g.D.getAudioTrack=function(){return this.player.getAudioTrack()};
g.D.g$m=function(){var Z=this.B.l4();Z&&!Z.Bu()&&Z.Iu();this.B.isFullscreen()?(this.G=this.wH=!0,this.loaded&&this.Po()):(this.wH=this.W.controlsType==="3",this.G=ZkH(this));b9(this,this.U)};
g.D.b$=function(){var Z,u,G,y=(Z=this.videoData.getPlayerResponse())==null?void 0:(u=Z.captions)==null?void 0:(G=u.playerCaptionsTracklistRenderer)==null?void 0:G.openTranscriptCommand;y&&this.player.pV("innertubeCommand",y)};
g.D.eM=function(Z,u,G){var y=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,q="";Z&&(q=Z.vssId,q=q.replace(y,""));var N="";Z&&Z.getId()&&(N=Z.getId()||"");Z&&Z.getXtags()&&(Z=Z.getXtags(),Z=Z.replace(y,""),N=N.concat(";"+Z));this.B.eM(u?q:"",u?N:"",G)};
g.D.po=function(Z,u){Z=(Z||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");Z.length>0&&this.B.po(Z,u)};g.on("captions",fXe);})(_yt_player);
