(function(g){var window=this;'use strict';var OZ=function(Z){Z.publish("cardstatechange",Z.g2()&&Z.S1()?1:0)},iAi=function(Z){var u=g.xk(Z);
Z=g.fk(Z);return new g.S2(u.x,u.y,Z.width,Z.height)},uAa=function(Z,u){if(u.channel_name){var G=Z.createElement({Z:"div",
Il:["iv-branding-context-name"],T6:u.channel_name}),y=Z.createElement({Z:"div",Il:["iv-branding-context-subscribe"]}),q=u.standalone_subscribe_button_data;q&&(Z.j=new g.cf(q.subscribeText,q.subscribeCount,q.unsubscribeText,q.unsubscribeCount,!!q.enabled,!!q.classic,u.channel_id,!!q.subscribed,q.feature,u.session_data.itct,Z.context.B,!1),Z.j.gH(y));var N=Z.createElement({Z:"div",Il:["iv-branding-context-subscribe-caret"]}),e=Z.createElement({Z:"div",Il:["branding-context-container-inner"]});e.appendChild(N);
e.appendChild(G);e.appendChild(y);g.W3(e,!1);var h=Z.createElement({Z:"div",Il:["branding-context-container-outer"]});h.appendChild(e);g.O0(h,"right",u.image_width+"px");g.iP(Z.zw(),h);Z.T=new g.fy(function(){kgH(Z,e,h)},500);
g.M(Z,Z.T);Z.context.j.listen(Z.zw(),"mouseover",function(){Zha(Z,e,h,N,u.image_height)});
Z.context.j.listen(Z.zw(),"mouseout",function(){Z.T.start()})}},yUH=function(Z,u){var G={startMs:Math.floor(Number(Z.startMs)),
impressionUrls:AY(Z.impressionUrls||[],za),elements:AY(Z.elements||[],function(y,q){return GBH(u,y,q)})};
Z.trackingParams&&(G.visualElement=g.Jn(Z.trackingParams));return G},GBH=function(Z,u,G){function y(x9){var qS=x9.hovercardButton;
if(!qS)return null;qS=qS.subscribeButtonRenderer;if(!qS)return null;var K7=N(qS.unsubscribedButtonText),GR=N(qS.subscribedButtonText);if(qS.subscribed){var ED=N(qS.subscriberCountWithUnsubscribeText);var oq=N(qS.subscriberCountText)}else ED=N(qS.subscriberCountText),oq=N(qS.subscriberCountWithSubscribeText);var H=null;if(x9.signinEndpoint){H=LL(x9,"signinEndpoint","webNavigationEndpointData","url");if(!H){var GH,L7;H=(L7=g.C((GH=qS.signInEndpoint)==null?void 0:GH.commandMetadata,g.Jd))==null?void 0:
L7.url}if(!H)return null}return K7&&(GR||H)?{subscribed:qS.subscribed,subscribeText:K7,subscribeCount:ED,unsubscribeText:GR,unsubscribeCount:oq,enabled:qS.enabled,signinUrl:H,classic:x9.useClassicSubscribeButton}:null}
function q(x9){if(x9){var qS=[],K7=x9.videoId;K7&&qS.push("v="+K7);(K7=x9.playlistId)&&qS.push("list="+K7);(x9=x9.startTimeSeconds)&&qS.push("t="+x9);return"/watch?"+qS.join("&")}}
function N(x9){if(!x9)return null;var qS=x9.simpleText;return qS?qS:x9.runs?g.gA(x9.runs,function(K7){return K7.text}).join(""):null}
u=u.endscreenElementRenderer;if(!u)return null;var e=u.style,h=u.endpoint||{},d=null,K=null,f=!1,V=null,X=null,n=null,l=null,Y=!1,E=null,W=null,p=null,z=null,L=null,Q=null;if(e==="VIDEO")g.C(h,g.hK)?d=g.C(h,g.hK).url:(Q=g.C(h,g.hH),d=q(Q)),K=!1,V=Z,u.thumbnailOverlays?(f=u.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,X=N(f.text),f=f.style==="LIVE"):X=N(u.videoDuration);else if(e==="PLAYLIST")g.C(h,g.hK)?d=g.C(h,g.hK).url:(Q=g.C(h,g.hH),d=q(Q)),K=!1,V=Z,n=N(u.playlistLength);else if(e===
"CHANNEL"){if(Y=LL(h,"browseEndpoint","browseId"))l=Y,d="/channel/"+l;K=!1;V="new";(Y=!!u.isSubscribe)?E=y(u):W=N(u.subscribersText)}else e==="WEBSITE"?((p=LL(h,"urlEndpoint","url"))&&(d=p),K=!0,V="new",p=u.icon.thumbnails[0].url):e==="CREATOR_MERCHANDISE"&&(u.productPrice&&(z=N(u.productPrice)),u.additionalFeesText&&(L=N(u.additionalFeesText)),(K=LL(h,"urlEndpoint","url"))&&(d=K),K=!0,V="new");Z=LL(u,"title","accessibility","accessibilityData","label");var b=u.endpoint?u.endpoint.clickTrackingParams:
null,w="";if(u.metadata){var yv=N(u.metadata);yv&&(w=yv)}return{id:"element-"+G,type:e,title:N(u.title),metadata:w,callToAction:N(u.callToAction),oH:u.image,iconUrl:p,left:Number(u.left),width:Number(u.width),top:Number(u.top),aspectRatio:Number(u.aspectRatio),startMs:Math.floor(Number(u.startMs)),endMs:Math.floor(Number(u.endMs)),videoDuration:X,Bf:f,playlistLength:n,channelId:l,subscribeButton:E,subscribersText:W,isSubscribe:Y,targetUrl:d||null,AxD:K,sessionData:b?{itct:b}:null,qxn:V,GI:Z?Z:null,
isPlaceholder:u.isPlaceholder,impressionUrls:AY(u.impressionUrls||[],za),Wmm:AY(u.hovercardShowUrls||[],za),clickUrls:AY(h.loggingUrls||[],za),visualElement:g.Jn(u.trackingParams),productPrice:z,additionalFeesText:L,watchEndpoint:Q||null}},qJe=function(Z,u,G){var y=y===void 0?{}:y;
var q;return q=g.Uh(Z,u,function(){g.pr(q);G.apply(Z,arguments)},y)},N7i=function(Z,u,G,y,q){if(u.length!=2||G.length!=2)throw Error("Start and end points must be 2D");
sZ.call(this,Z,u,G,y,q)},eae=function(Z){var u=g.vw(),G=g.ZD();
G&&u&&Z.endscreen.visualElement&&g.rc(g.SD)(void 0,G,u,Z.endscreen.visualElement)},KEk=function(Z,u,G){function y(d){d&&(u.listen("blur",function(){d.style.display!="none"&&Z.Qn&&d.focus()}),u.V(d,"focus",e),u.V(d,"blur",q))}
function q(){N(-1)}
function N(d){Z.K+=d;Z.K>0?(g.AM(u.element,"ytp-ce-force-expand"),vh(Z,G.id,!0)):(g.w4(u.element,"ytp-ce-force-expand"),g.w4(u.element,"ytp-ce-element-hover"),vh(Z,G.id,!1))}
function e(){N(1)}
u.listen("mouseenter",function(){xra(Z,u,G)});
u.listen("mouseleave",function(){hai(Z,u,G)});
Z.player.J().U||u.listen("click",function(){g.AM(u.element,"ytp-ce-element-hover")});
u.listen("click",function(d){drd(Z,G,d)});
u.listen("keypress",function(d){drd(Z,G,d)});
u.listen("focus",function(){xra(Z,u,G)});
u.listen("blur",function(){hai(Z,u,G)});
u.listen("touchstart",function(){xra(Z,u,G)});
var h=g.sK("ytp-ce-expanding-overlay-hider",u.element);h&&u.V(h,"touchstart",function(d){d.stopPropagation();g.w4(u.element,"ytp-ce-element-hover");g.w4(u.element,"ytp-ce-force-expand")});
u.listen("keydown",function(d){Z.Qn=d.keyCode===9&&!d.shiftKey});
y(g.sK("ytp-sb-subscribe",u.element));y(g.sK("ytp-sb-unsubscribe",u.element));u.listen("focus",e);u.listen("blur",q)},fWd=function(Z){var u;
return((u=g.C(Z,g.hK))==null?0:u.url)?g.C(Z,g.hK).url:(Z=g.C(Z,g.hH))&&Z.videoId?(u="/watch?v="+Z.videoId,Z.playlistId&&(u+="&list="+Z.playlistId),Z.index&&(u+="&index="+Z.index),Z.startTimeSeconds&&(u+="&t="+Z.startTimeSeconds),u):null},lWa=function(Z){if(!Z)return null;
var u=S3(Z.type,VAi),G=S3(Z.trigger,Xvd);Z=Z.url;Z=Array.isArray(Z)&&Z.length?Z[0]:Z;Z=Ry(Z?Z:null);return u?new nqd(u,G,Z):null},CL=function(Z,u,G){G=G===void 0?!0:G;
Z.player.fK("creatorendscreen");Z.T&&(Z.T.dispose(),Z.T=null,Z.G.dispose(),Z.G=null);for(var y=g.m(Object.values(Z.U)),q=y.next();!q.done;q=y.next())q.value.dispose();Z.U={};Z.X={};Z.C.length>0&&(Z.C.forEach(function(h){h.dispose()}),Z.C.length=0);
Z.j&&(g.w4(Z.j,"ytp-ce-element-show"),Z.j.setAttribute("aria-hidden","true"));Z.K=0;if((Z.endscreen=u)&&u.elements){G&&eae(Z);G=[];y=new g.BX(u.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});G.push(y);Z.player.J().U||(Z.T=new g.P({Z:"div",Y:"ytp-ce-shadow"}),g.l7(Z.player,Z.T.element,4),Z.G=new g.wd(Z.T,200));for(y=0;y<u.elements.length;++y){q=u.elements[y];var N=DrP(Z,q);if(N){Z.U[q.id]=N;Z.X[q.id]=q;g.l7(Z.player,N.element,4);var e=new g.BX(q.startMs,q.endMs,{id:"ytp-ce-element-"+
q.id,namespace:"creatorendscreen"});G.push(e);KEk(Z,N,q)}else g.h6(new g.dw("buildEndscreenElement null",q))}Z.player.JP(G);Z.Hy()}},JUd=function(Z,u){switch(u.type){case "simple":Z=Z.xx;
var G=u.displayDomain?{Z:"div",Y:"iv-card-image-text",T6:u.displayDomain}:void 0;var y=MAd(u);G={Z:"div",Il:["iv-card"],L:[{Z:"a",Y:"iv-click-target",N:{href:u.url?Ph(u.url)||"":""},L:[oy(u.imageUrl,G),{Z:"div",Y:"iv-card-content",L:[Q1("h2",void 0,u.title),y]}]}]};G=new g.P(G);F0(Z,g.p4("iv-click-target",G.element),u,u.url);u=G;break;case "collaborator":Z=Z.xx;G={Z:"div",Il:["iv-card","iv-card-channel"],L:[{Z:"a",Il:["iv-click-target"],N:{href:Ph(u.url)||"","data-ytid":u.channelId},L:[oy(u.profileImageUrl),
{Z:"div",Y:"iv-card-content",L:[mrw(u),{Z:"h2",Y:"iv-card-primary-link",T6:u.title},YJH(u)]}]}]};G=new g.P(G);F0(Z,g.p4("iv-click-target",G.element),u,u.url);u=G;break;case "playlist":Z=Z.xx;G={Z:"div",Il:["iv-card","iv-card-playlist"],L:[{Z:"a",Y:"iv-click-target",N:{href:Ph(u.url)||""},L:[oy(u.OV,{Z:"div",Y:"iv-card-image-overlay",L:[{Z:"span",Y:"iv-card-playlist-video-count",T6:u.playlistVideoCount}]}),{Z:"div",Y:"iv-card-content",L:[mrw(u),Q1("h2","iv-card-primary-link",u.title),YJH(u)]}]}]};
G=new g.P(G);F0(Z,g.p4("iv-click-target",G.element),u,u.url);u=G;break;case "productListing":Z=Z.xx;var q=u.offers.length!=0;G=["iv-card"];y="";var N=MAd(u);q&&(G.push("iv-card-product-listing"),y="iv-card-primary-link",N=u.offers[0],q=[],N.price&&q.push({Z:"div",Y:"iv-card-offer-price",T6:N.price}),N.merchant&&q.push({Z:"div",Y:"iv-card-offer-merchant",T6:N.merchant}),N={Z:"div",L:q});q=u.url?Ph(u.url)||"":"";G={Z:"div",Il:G,N:{tabindex:"0"},L:[{Z:"a",Il:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+
u.imageUrl+");",href:q,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",Y:"iv-card-content",L:[u.sponsored?{Z:"div",Y:"iv-card-sponsored",L:["Sponsored",{Z:"div",Y:"iv-ad-info-container",L:[{Z:"div",Y:"iv-ad-info",T6:"{{adInfo}}"},{Z:"div",Y:"iv-ad-info-icon-container",L:[{Z:"div",Y:"iv-ad-info-icon"},{Z:"div",Y:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",Y:"iv-click-target",N:{href:q},L:[Q1("h2",y,u.title),N]}]}]};G=new g.P(G);y=g.Ol("span");g.vJ(y,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
G.setContent(y,"adInfo");F0(Z,g.p4("iv-click-target",G.element),u,u.url);u=G;break;case "video":Z=Z.xx;y=u.videoDuration?{Z:"span",Y:"iv-card-video-duration",T6:u.videoDuration}:void 0;N=u.isLiveNow?{Z:"span",Il:["yt-badge","yt-badge-live"],T6:"LIVE NOW"}:null;q={Z:"div",Il:["iv-card","iv-card-video"],L:[{Z:"a",Y:"iv-click-target",N:{href:((G=u.url)==null?void 0:Ph(G))||""},L:[oy(u.OV,y),{Z:"div",Y:"iv-card-content",L:[mrw(u),Q1("h2","iv-card-primary-link",u.title),YJH(u),N]}]}]};G=new g.P(q);F0(Z,
g.p4("iv-click-target",G.element),u,u.url);u=G;break;default:return null}return u},Eqk=function(Z,u){return function(){var G=g.Iq.apply(0,arguments);
Z.Bu()||Z.UT.push(g.BW.Jg(function(){u.apply(null,g.bg(G))}))}},ch=function(Z){Z.T&&(Z.Hu.hide(),g.Xp(Z.al),g.w4(Z.context.B.getRootNode(),g.CZ.IV_DRAWER_OPEN),Z.T=!1,OZ(Z.B),Z.X&&Z.X.stop(),Z.X=new g.fy(function(){Z.SD&&(Z.SD.focus(),Z.SD=null)},330),Z.X.start())},gF=function(Z,u,G,y){g.m8.call(this);
if(!Array.isArray(Z)||!Array.isArray(u))throw Error("Start and end parameters must be arrays");if(Z.length!=u.length)throw Error("Start and end points must be the same length");this.U=Z;this.K=u;this.duration=G;this.G=y;this.coords=[];this.progress=this.X=0;this.D=null},Uri=function(Z){Z.D&&(g.nh.clearTimeout(Z.D),Z.D=null)},xra=function(Z,u,G){g.c_(u.element,"ytp-ce-element-hover")||(G.type==="VIDEO"||G.type==="PLAYLIST"?g.AM(u.element,"ytp-ce-element-hover"):Z.player.J().U?(new g.fy(function(){g.AM(u.element,
"ytp-ce-element-hover")},200)).start():g.AM(u.element,"ytp-ce-element-hover"),wF(Z,G.Wmm),vh(Z,G.id,!0))},pvJ=function(Z,u){g.tq.call(this,Z);
this.coords=u.coords;this.x=u.coords[0];this.y=u.coords[1];this.z=u.coords[2];this.duration=u.duration;this.progress=u.progress;this.fps=u.X;this.state=u.j},Ph=function(Z){return Z.value?Z.value:null},S3=function(Z,u,G){for(var y in u)if(u[y]===Z)return Z;
return G},za=function(Z){return Z.baseUrl||null},DrP=function(Z,u){var G=null;
switch(u.type){case "VIDEO":Z={Z:"div",Il:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":u.GI||"","aria-hidden":"true"},L:[{Z:"div",Y:"ytp-ce-element-shadow"},{Z:"div",Y:"ytp-ce-covering-image",N:Ta(u)},{Z:"div",Y:"ytp-ce-covering-shadow-top"},{Z:"a",Y:"ytp-ce-covering-overlay",N:{href:ay(Z,u.targetUrl),tabindex:"-1"},L:[{Z:"div",Il:["ytp-ce-video-title","ytp-webkit-ellipsis"],N:{dir:g.NI(u.title||"")},T6:u.title},{Z:"div",Y:u.Bf?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
T6:u.videoDuration||void 0}]}]};G=new g.P(Z);break;case "PLAYLIST":Z={Z:"div",Il:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":u.GI||"","aria-hidden":"true"},L:[{Z:"div",Y:"ytp-ce-element-shadow"},{Z:"div",Y:"ytp-ce-covering-image",N:Ta(u)},{Z:"div",Y:"ytp-ce-covering-shadow-top"},{Z:"a",Y:"ytp-ce-covering-overlay",N:{href:ay(Z,u.targetUrl),tabindex:"-1"},L:[{Z:"div",Il:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],N:{dir:g.NI(u.title||"")},T6:u.title},{Z:"div",Y:"ytp-ce-playlist-count",
L:[{Z:"div",Y:"ytp-ce-playlist-icon"},{Z:"div",Y:"ytp-ce-playlist-count-text",T6:u.playlistLength||void 0}]}]}]};G=new g.P(Z);break;case "CHANNEL":G={Z:"div",Il:["ytp-ce-element","ytp-ce-channel",u.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":u.GI||"","aria-hidden":"true"},L:[{Z:"div",Y:"ytp-ce-element-shadow"},{Z:"div",Y:"ytp-ce-expanding-overlay",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-hider"},{Z:"div",Y:"ytp-ce-expanding-overlay-background"},{Z:"div",Y:"ytp-ce-expanding-overlay-content",
L:[{Z:"div",Y:"ytp-ce-expanding-overlay-body",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-body-padding",L:[{Z:"a",Il:["ytp-ce-channel-title","ytp-ce-link"],N:{href:ay(Z,u.targetUrl),target:"_blank",tabindex:"-1",dir:g.NI(u.title||"")},T6:u.title},u.subscribeButton?{Z:"div",Y:"ytp-ce-subscribe-container",L:[{Z:"div",Y:"ytp-ce-channel-subscribe"}]}:"",u.subscribersText?{Z:"div",Y:"ytp-ce-channel-subscribers-text",T6:u.subscribersText}:"",u.metadata?{Z:"div",Il:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],T6:u.metadata}:""]}]}]}]},{Z:"div",Y:"ytp-ce-expanding-image",N:Ta(u)}]};G=new g.P(G);var y=g.i4(document,"div","ytp-ce-channel-subscribe",G.element)[0];if(u.subscribeButton&&u.channelId){g.AM(y,"ytp-ce-subscribe-button");if(Z.player.J().U){var q=null;var N=u.sessionData.itct}else q="endscreen",N=null;q=new g.cf(u.subscribeButton.subscribeText,u.subscribeButton.subscribeCount,u.subscribeButton.unsubscribeText,u.subscribeButton.unsubscribeCount,!!u.subscribeButton.enabled,!!u.subscribeButton.classic,
u.channelId,!!u.subscribeButton.subscribed,q,N,Z.player,!1);y.appendChild(q.element);Z.C.push(q)}break;case "WEBSITE":Z={Z:"div",Il:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":u.GI||"","aria-hidden":"true"},L:[{Z:"div",Y:"ytp-ce-element-shadow"},{Z:"div",Y:"ytp-ce-expanding-overlay",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-hider"},{Z:"div",Y:"ytp-ce-expanding-overlay-background"},{Z:"div",Y:"ytp-ce-expanding-overlay-content",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-body",L:[{Z:"div",
Y:"ytp-ce-expanding-overlay-body-padding",L:[{Z:"div",Y:"ytp-ce-website-title",N:{dir:g.NI(u.title||"")},T6:u.title},{Z:"div",Y:"ytp-ce-website-metadata",T6:u.metadata},{Z:"a",Il:["ytp-ce-website-goto","ytp-ce-link"],N:{href:ay(Z,u.targetUrl),target:"_blank",tabindex:"-1"},T6:u.callToAction}]}]}]}]},{Z:"div",Y:"ytp-ce-expanding-image",N:Ta(u)},{Z:"div",Y:"ytp-ce-expanding-icon",N:Hhi(u.iconUrl)}]};G=new g.P(Z);break;case "CREATOR_MERCHANDISE":G="",u.productPrice&&(G={Z:"div",Y:"ytp-ce-merchandise-price-container",
L:[{Z:"div",Y:"ytp-ce-merchandise-price",T6:u.productPrice}]},u.additionalFeesText&&G.L.push({Z:"div",Y:"ytp-ce-merchandise-additional-fees",T6:u.additionalFeesText})),Z={Z:"div",Il:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":u.GI||"","aria-hidden":"true"},L:[{Z:"div",Y:"ytp-ce-element-shadow"},{Z:"div",Y:"ytp-ce-expanding-overlay",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-hider"},{Z:"div",Y:"ytp-ce-expanding-overlay-background"},{Z:"div",Y:"ytp-ce-expanding-overlay-content",
L:[{Z:"div",Y:"ytp-ce-expanding-overlay-body",L:[{Z:"div",Y:"ytp-ce-expanding-overlay-body-padding",L:[{Z:"div",Y:"ytp-ce-merchandise-title",N:{dir:g.NI(u.title||"")},T6:u.title},G,{Z:"div",Y:"ytp-ce-merchandise-metadata",T6:u.metadata},{Z:"a",Il:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:ay(Z,u.targetUrl),target:"_blank",tabindex:"-1"},T6:u.callToAction}]}]}]}]},{Z:"div",Y:"ytp-ce-expanding-image",N:Ta(u)},{Z:"div",Y:"ytp-ce-merchandise-invideo-cta-container",L:[{Z:"div",Y:"ytp-ce-merchandise-invideo-cta",
T6:u.callToAction||void 0}]}]},G=new g.P(Z)}u.isPlaceholder&&g.AM(G.element,"ytp-ce-placeholder");return G},oy=function(Z,u){Z="background-image: url("+Z+");";
var G=[];u&&G.push(u);return{Z:"div",Y:"iv-card-image",N:{style:Z},L:G}},$Y=function(Z){Z=g.La(Z);
delete bm[Z];g.fV(bm)&&Iy&&Iy.stop()},rF=function(Z,u,G,y){var q=1,N=void 0,e=-1;
if(G){var h=!1;N=function(){q--;q||h||(clearTimeout(e),h=!0,G())};
e=setTimeout(function(){h=!0;G()},1E3)}u=g.m(u||[]);
for(var d=u.next();!d.done;d=u.next())d=d.value,q++,g.hv(d,N);y&&(q++,y!==0&&Z.B.sendVideoStatsEngageEvent(y,N))},B7H=function(Z,u){return g.fQ(Z.action,u)},vh=function(Z,u,G){Z.T&&(G?Z.G.show():Z.G.hide());
for(var y=g.m(Object.keys(Z.U)),q=y.next();!q.done;q=y.next())q=q.value,q!==u&&g.Bv(Z.U[q].element,"ytp-ce-element-shadow-show",G)},drd=function(Z,u,G){if(u.targetUrl&&(!G||G.type!=="keypress"||G.keyCode===13)){for(var y=G.target;y&&!g.c_(y,"ytp-ce-element");){g.c_(y,"subscribe-label")&&tAv(Z,u);
if(g.c_(y,"ytp-ce-channel-subscribe"))return;y=y.parentElement||null}if(!y||g.c_(y,"ytp-ce-element-hover")){G.preventDefault();G.stopPropagation();if(y=Z.U[u.id])hai(Z,y,u),y.element.blur();if(G.ctrlKey||G.metaKey||u.qxn==="new")tAv(Z,u),Z.player.sendVideoStatsEngageEvent(17,void 0),Z.player.pauseVideo(),G=g.cX(ay(Z,u.targetUrl)),G=g.hr(G),g.y9(G,void 0,u.sessionData);else{var q=g.Pv(Z.player.J())||Z.player.getVideoData().Wc,N=function(){var e=ay(Z,u.targetUrl),h=u.sessionData,d=u.watchEndpoint,K=
g.kG(e);q&&K&&(K.v||K.list)?Z.player.CY(K.v,h,K.list,!1,void 0,d||void 0):g.Gq(e,h)};
tAv(Z,u,function(){Z.player.sendVideoStatsEngageEvent(17,N)})}}}},im=function(Z,u){g.O.call(this);
var G=this;this.element=Z;this.context=u;this.LV=!1;this.sT=new Map;this.wH=new Map;this.context.B.addEventListener(g.ir("annotations_module"),function(y){(y=G.sT.get(y))&&y.apply(G)});
this.context.B.addEventListener(g.kq("annotations_module"),function(y){(y=G.wH.get(y))&&y.apply(G)})},jpJ=function(Z,u){var G=Z.player.getVideoData().clientPlaybackNonce;
Z=Z.player.getCurrentTime().toFixed(2);G={CPN:G,AD_CPN:G,MT:Z};Z=[];for(var y=0;y<u.length;y++)Z.push(WEJ(u[y],G));return Z},Oh4=function(Z,u,G,y,q,N,e){this.j=Z;
this.T=u;this.W=G;this.videoData=y;this.logger=q;this.B=N;this.U=e},tAv=function(Z,u,G){wF(Z,u.clickUrls,G);
(Z=g.ZD())&&u.AxD&&g.a3(Z,u.visualElement)},AUe=function(Z,u,G,y,q){this.id=Z;
this.type=u;this.style=G;this.data=q;this.action=y||[]},mrw=function(Z){return Z.customMessage?Q1("div","iv-card-message",Z.customMessage):""},Zha=function(Z,u,G,y,q){Z.T.stop();
if(!Z.D){var N=g.fk(u);Z.j||(u.style.width=g.bl(N.width,!0),G.style.width=g.bl(N.width,!0));g.O0(y,"top",N.height-Math.max(Math.min(N.height,q)/2+10,20)+"px");g.O0(y,"right","1px");Z.D=!0;g.W3(u,!0);Z.G=new g.fy(function(){g.AM(this.zw(),"iv-branding-active")},0,Z);
Z.G.start()}},zaJ=function(Z){return typeof Z==="string"?Z:""},spe=function(Z,u){if(u=LE4(Z,u))u===Z.j&&(Z.j=null),Z.B.removeCueRange(u.a_.id),g.qr(u.m2),g.lu(Z.cards,u),Z.Fi(),kY(Z)},nqd=function(Z,u,G){this.type=Z;
this.trigger=u;this.url=G},Hhi=function(Z){return Z?{style:"background-image: url("+Z+")"}:{}},vqa=function(Z){return Z==="annotation-editor"||Z==="live-dashboard"},SJP=function(Z){Z.isCollapsed||Z.C||Z.D||(g.AM(Z.zw(),"iv-promo-collapsed"),Z.isCollapsed=!0,Z.G.start())},CrH=function(Z,u,G){im.call(this,u,G);
var y=this;this.B=Z;this.eventId=null;this.DY=this.Mu=this.ZY=this.T=this.isInitialized=!1;this.cards=[];this.kx=this.G=this.SD=this.X=this.nV=this.j=null;this.Qn=[];this.UT=this.C=this.yH=this.u7=null;this.K=0;this.Zi=new g.fy(function(){},G.W.pY?4E3:3E3);
g.M(this,this.Zi);this.JT=new g.fy(function(){});
g.M(this,this.JT);this.xx=new Rai(G,function(q,N,e,h,d,K){ZO(y,q,N,e,h,d,K)});
this.Fn=new g.P({Z:"div",Y:"iv-drawer",N:{id:"iv-drawer"},L:[{Z:"div",Y:"iv-drawer-header",N:{"aria-role":"heading"},L:[{Z:"span",Y:"iv-drawer-header-text"},{Z:"button",Il:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{Z:"div",Y:"iv-drawer-content"}]});g.M(this,this.Fn);this.D=this.Fn.element;this.Hu=new g.wd(this.Fn,330);g.M(this,this.Hu);this.Qu=g.sK("iv-drawer-header-text",this.D);this.U=g.sK("iv-drawer-content",this.D);this.addCueRange(0,G.videoData.lengthSeconds*
1E3,"",function(){y.ZY&&u9(y,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(y.ZY=y.T)&&ch(y)});
this.al=new g.Ch(this);g.M(this,this.al);this.B.addEventListener("videodatachange",this.Yv.bind(this))},GZ=function(Z,u,G){return{J9:(Z.impressionLoggingUrlsV2s||[]).map(function(y){return y.baseUrl||""}),
click:(G.loggingUrls||[]).map(function(y){return y.baseUrl||""}),
close:(u.dismissLoggingUrlsV2s||[]).map(function(y){return y.baseUrl||""}),
pN:(u.impressionLoggingUrlsV2s||[]).map(function(y){return y.baseUrl||""}),
VI:(u.clickLoggingUrlsV2s||[]).map(function(y){return y.baseUrl||""})}},kY=function(Z){g.Bv(Z.B.getRootNode(),"ytp-cards-shopping-active",PrJ(Z))},gqP=function(Z,u){function G(e){var h=Z.loadNumber;
Z.G=null;Z.loaded&&Z.loadNumber===h&&Z.player.getVideoData().videoId===y&&(e=g.Bw(e)&&e.responseXML?e.responseXML:null)&&(oqR(Z,e),g.AM(Z.player.getRootNode(),"iv-module-loaded"))}
var y=u.videoId;g.Fh()&&(G=Eqk(Z,G));var q={format:"XML",onFinish:G,onError:function(){Z.G=null},
urlParams:{}};u.isPharma&&(q.urlParams.pharma="1");q.method="POST";q.withCredentials=!0;var N=Z.player.J().Mu.get(y);N&&(Math.random()<g.Zh(Z.player.J().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.h6(new g.dw("Unexpected call to loadVastInfoCards; VastInfoCard exists.")),Qpe(q,N));N=N&&(N.v_||N.xZ);if(!u.Jv||N)u.L5?(Math.random()<g.Zh(Z.player.J().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.h6(new g.dw("Unexpected call to loadVastInfoCards; Attempting to load annotations via invideo URL.")),
FEP(Z,u.L5,q)):(Z.K=function(){if(!Z.C)Z.onVideoDataChange(q);var e=Z.player.getVideoData();(e==null?0:g.Rc(e))&&!Z.Qn&&cUH(Z,e)},Z.player.addEventListener("videodatachange",Z.K))},kgH=function(Z,u,G){g.w4(Z.zw(),"iv-branding-active");
Z.X=new g.fy(function(){g.W3(u,!1);Z.j||(G.style.width=g.bl(0,!0))},250);
Z.X.start();Z.D=!1},sZ=function(Z,u,G,y,q){gF.call(this,u,G,y,q);
this.element=Z},wvk=function(Z){var u=Z.annotation.data;
"start_ms"in u&&"end_ms"in u&&Z.addCueRange(Number(u.start_ms),Number(u.end_ms),Z.annotation.id,function(){Z.show()},function(){Z.hide()})},MAd=function(Z){if(!Z.customMessage)return"";
var u=["iv-card-action","iv-card-primary-link"],G={};Z.eT&&(u.push("iv-card-action-icon"),G.style="background-image: url("+Z.eT+");");G.dir=g.NI(Z.customMessage);var y=[{Z:"span",T6:Z.customMessage}];Z.showLinkIcon&&(y.push("\u00a0"),y.push({Z:"span",Y:"iv-card-link-icon"}));return{Z:"div",Il:u,N:G,L:y}},yE=function(Z){if(!Z.Fn){var u=new T7H(Z);
g.M(Z,u);var G=new g.IO(Z);g.M(Z,G);Z.Fn=new Oh4(u,G,Z.player.J(),Z.player.getVideoData(),Z.logger,Z.player,Z.i4)}return Z.Fn},PrJ=function(Z){if(Z.j)return Z.j.a_.type==="productListing";
if(Z.B.S("enable_wn_infocards")){var u;return!((u=Z.cards)==null||!u.length)&&g.vD(Z.cards,function(G){return G.a_.type==="productListing"})}return g.vD(Z.cards,function(G){return G.a_.type==="productListing"})},qT=function(Z){return Z.player.J().playerStyle==="creator-endscreen-editor"},aW4=function(Z){Z.Qn.push(g.cb("iv-teaser-shown",Z.L9,Z));
Z.Qn.push(g.cb("iv-teaser-hidden",Z.yxn,Z));Z.Qn.push(g.cb("iv-teaser-clicked",Z.vU,Z));Z.DY=!0},$rd=function(Z,u){var G=!1;
Z.j||(Z.j=bhR(Z),g.M(Z,Z.j));for(var y=g.m(u.cards||[]),q=y.next();!q.done;q=y.next())q=q.value,q.cardRenderer&&(IWR(Z.j,q.cardRenderer),G=!0);if(G){var N;(N=Z.player.getVideoData())!=null&&g.Rc(N)||(G=Z.j,y=u.headerText?g.Ah(u.headerText):"",g.vJ(G.Qu,y),G.G&&(G.B.S("player_tooltip_data_title_killswitch")?G.G.setAttribute("title",y):G.G.setAttribute("data-tooltip-title",y)),G.context.videoData.eventId&&(G.eventId=G.context.videoData.eventId),G.u7=u.trackingParams?g.Jn(u.trackingParams):null,G.C=
u.closeButton.infoCardIconRenderer.trackingParams?g.Jn(u.closeButton.infoCardIconRenderer.trackingParams):null,G.yH=u.icon.infoCardIconRenderer.trackingParams?g.Jn(u.icon.infoCardIconRenderer.trackingParams):null,Z.UB());OZ(Z.player)}},rUs=function(Z){return Math.pow(Z,3)},ihv=function(Z,u){for(var G={},y=g.m(u.attributes),q=y.next();!q.done;q=y.next())q=q.value,G[q.name]=q.nodeValue;
for(y=0;y<u.childNodes.length;y++)if(q=u.childNodes[y],g.n$(q)&&q.nodeType==1){if(G[q.tagName])var N=G[q.tagName];else if(q.tagName==="data"){q.childNodes.length>0&&(N=q.childNodes[0].nodeValue,G[q.tagName]=typeof N==="string"?N.trim():N);continue}else N=[],G[q.tagName]=N;q&&q.tagName==="TEXT"?q.childNodes.length===1&&q.childNodes[0].nodeType===3?N.push(q.childNodes[0].nodeValue):N.push(""):q&&N.push(ihv(Z,q))}return G},NT=function(Z,u,G,y){return{feature:G.feature?G.feature:"cards",
src_vid:Z.context.videoData.videoId,annotation_id:u,ei:Z.context.videoData.eventId||"",itct:y.trackingParams||""}},kBk=function(Z){return 3*Z*Z-2*Z*Z*Z},ay=function(Z,u){Z=Z.player.J();
if(u){if(u.startsWith("//"))return Z.protocol+":"+u;if(u.startsWith("/"))return g.zV(Z)+u}else return"";return u},cUH=function(Z,u){var G,y;
if(u=(G=u.getWatchNextResponse())==null?void 0:(y=G.cards)==null?void 0:y.cardCollectionRenderer)Z.Qn=!0,$rd(Z,u),u.headerText&&Z.CT&&(G=g.Ah(u.headerText),Z.player.S("player_tooltip_data_title_killswitch")?Z.CT.setAttribute("title",G):Z.CT.setAttribute("data-tooltip-title",G))},Q1=function(Z,u,G){u?typeof u==="string"?u={"class":u}:Array.isArray(u)&&(u={"class":u.join(" ")}):u={};
u.dir=g.NI(G);return{Z:Z,N:u,T6:G}},ytk=function(Z){g.gC.call(this,Z);
var u=this;this.Qn=this.C=!1;this.loadNumber=0;this.X={};this.logger=new Zs4(this.player);this.D=new g.Ch(this);this.G=this.K=null;this.events=new g.Ch(this);this.CT=this.Fn=this.j=null;this.UT=[];g.M(this,this.D);this.D.V(this.player,"onVideoAreaChange",function(){u.publish("onVideoAreaChange")});
this.D.V(this.player,"onHideControls",function(){u.publish("onHideControls")});
this.D.V(this.player,"onShowControls",function(){u.publish("onShowControls")});
this.D.V(this.player,"resize",function(N){u.publish("resize",N)});
this.D.V(this.player,"presentingplayerstatechange",function(N){u.publish("presentingplayerstatechange",N)});
this.subscribe("presentingplayerstatechange",this.WU,this);this.subscribe("resize",this.UB,this);this.player.J().Mu.subscribe("vast_info_card_add",this.W8,this);g.M(this,this.events);this.xx=this.createElement({Z:"div",Y:"video-custom-annotations"});this.U=new g.P({Z:"div",Il:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.U);g.l7(this.player,this.U.element,4);this.U.hide();this.T=new g.P({Z:"div",Il:["ytp-iv-video-content"]});g.M(this,this.T);Z=this.createElement({Z:"div",Y:"video-annotations"});
Z.appendChild(this.xx);this.T.element.appendChild(Z);this.aY()&&this.load();var G=this.createElement({Z:"style"});(g.jN("HEAD")[0]||document.body).appendChild(G);this.addOnDisposeCallback(function(){g.qr(G)});
if(Z=G.sheet){for(var y=g.m(ulv),q=y.next();!q.done;q=y.next())Z.insertRule(q.value,0);y=g.m(GEe);for(q=y.next();!q.done;q=y.next())Z.insertRule(q.value,0)}},qeJ=function(Z,u){Z.UT=u;
var G=Z.B.getVideoData();if(!G)return!1;G=g.a4v(G);if(G==null?0:G.markersMap)for(var y,q=0;((y=G)==null?void 0:y.markersMap.length)>q;q++){var N=void 0,e=(N=G)==null?void 0:N.markersMap[q];if(e.key==="ERROR_CORRECTION_MARKERS"&&(N=void 0,(e=(N=e.value)==null?void 0:N.markers)&&e.length>0))return y=void 0,u.startMs=((y=g.C(e[0],g.FGF))==null?void 0:y.timeRangeStartMillis)||0,Z.UT=null,!0}return!1},NSd=function(Z){return Z.player.getVideoData().Wc?"current":Z.Fn?"new":"current"},xVJ=function(Z){var u=
Z.annotation.data;
if(Z.annotation.style==="cta")var G=6;else if(Z.annotation.style==="video"||Z.annotation.style==="playlist")G=7;Z.X=u.collapsedelay_ms||Z.X;var y=["iv-promo","iv-promo-inactive"];Z.zw().setAttribute("aria-hidden","true");Z.zw().setAttribute("aria-label","Promotion");Z.zw().tabIndex=0;var q=Z.annotation.M0(),N=u.image_url;if(N){var e=Z.createElement({Z:"div",Il:["iv-promo-img","iv-click-target"]});N=Z.createElement({Z:"img",N:{src:N,"aria-hidden":"true"}});e.appendChild(N);u.video_duration&&!u.is_live?
(N=Z.createElement({Z:"span",Y:"iv-promo-video-duration",T6:u.video_duration}),e.appendChild(N)):u.playlist_length&&(N=Z.createElement({Z:"span",Y:"iv-promo-playlist-length",T6:u.playlist_length.toString()}),e.appendChild(N));q&&ZO(Z,e,q,Z.annotation.id,u.session_data,void 0,G)}q?(N=Z.createElement({Z:"a",Y:"iv-promo-txt"}),g.eA(N,Ph(q)),Z.j=N):Z.j=Z.createElement({Z:"div",Y:"iv-promo-txt"});switch(Z.annotation.style){case "cta":case "website":var h=Z.createElement({Z:"p",L:[{Z:"strong",T6:u.text_line_1}]});
var d=Z.createElement({Z:"p",L:[{Z:"span",Y:"iv-promo-link",T6:u.text_line_2}]});if(N=u.text_line_3){y.push("iv-promo-website-card-cta-redesign");var K=Z.createElement({Z:"button",Il:["iv-promo-round-expand-icon","ytp-button"]});N=Z.createElement({Z:"button",Il:["iv-button","iv-promo-button"],L:[{Z:"span",Y:"iv-button-content",T6:N}]});var f=Z.createElement({Z:"div",Y:"iv-promo-button-container"});f.appendChild(N);q&&ZO(Z,Z.zw(),q,Z.annotation.id,u.session_data,void 0,G)}g.AM(Z.j,"iv-click-target");
q&&ZO(Z,Z.j,q,Z.annotation.id,u.session_data,void 0,G);break;case "playlist":case "video":h=Z.createElement({Z:"p",L:[{Z:"span",T6:u.text_line_1}]}),d=Z.createElement({Z:"p",L:[{Z:"strong",T6:u.text_line_2}]}),u.is_live&&(h=d,d=Z.createElement({Z:"span",Il:["yt-badge","iv-promo-badge-live"],T6:"LIVE NOW"})),g.AM(Z.j,"iv-click-target"),q&&ZO(Z,Z.j,q,Z.annotation.id,u.session_data,void 0,G),y.push("iv-promo-video")}h&&Z.j.appendChild(h);d&&Z.j.appendChild(d);Z.K.appendChild(Z.j);f&&Z.K.appendChild(f);
G=Z.createElement({Z:"div",Y:"iv-promo-actions"});Z.U=Z.createElement({Z:"button",Il:["iv-promo-expand","ytp-button"]});Z.U.title="Expand";Z.context.j.listen(Z.U,"click",function(V){eue(Z,5E3,V)});
G.appendChild(Z.U);g.W3(Z.U,!1);Z.context.j.listen(Z.zw(),"mouseover",Z.Xun,Z);Z.context.j.listen(Z.zw(),"mouseout",Z.ai1,Z);Z.context.j.listen(Z.zw(),"touchend",function(V){eue(Z,5E3,V)});
Z.T=Z.createElement({Z:"button",Il:["iv-promo-close","ytp-button"]});Z.T.title="Close";Z.context.j.listen(Z.T,"click",Z.annotation.style==="cta"&&u.text_line_3?Z.MDn:Z.Ii6,Z);G.appendChild(Z.T);g.t7(Z.zw(),y);e&&(g.iP(Z.zw(),e),K&&e.appendChild(K));g.iP(Z.zw(),Z.K);g.iP(Z.zw(),G)},hui=function(Z,u){typeof Z.G==="function"&&(u=Z.G(u));
Z.coords=Array(Z.U.length);for(var G=0;G<Z.U.length;G++)Z.coords[G]=(Z.K[G]-Z.U[G])*u+Z.U[G]},dVi=function(Z,u,G,y){this.value=Z;
this.target=u;this.showLinkIcon=G;this.j=y},Kuw=function(Z){Z=Z.createElement({Z:"div",
Il:["annotation","annotation-type-custom"]});g.W3(Z,!1);return Z},AY=function(Z,u){return g.kn(g.gA(Z,u),function(G){return!!G})},fki=function(Z,u){var G;
return u.onClickCommand&&((G=g.C(u.onClickCommand,g.zMe))==null?void 0:G.targetId)==="engagement-panel-error-corrections"?(Z.UT=u,!0):!1},LL=function(Z,u){var G=g.rA(u),y=G?u:arguments;
for(G=G?0:1;G<y.length;G++){if(Z==null)return;Z=Z[y[G]]}return Z},e8=function(Z,u,G){im.call(this,Z,u);
this.annotation=G;this.isActive=!1},VEe=function(Z,u){u=u.data;
u.autoOpenMs&&Z.addCueRange(u.autoOpenMs,0x8000000000000,"",function(){u9(Z,"YOUTUBE_DRAWER_AUTO_OPEN")});
u.autoCloseMs&&Z.addCueRange(u.autoCloseMs,0x8000000000000,"",function(){ch(Z)});
var G=u.headerText;g.vJ(Z.Qu,G);Z.G&&(Z.B.S("player_tooltip_data_title_killswitch")?Z.G.setAttribute("title",G):Z.G.setAttribute("data-tooltip-title",G));u.eventId&&(Z.eventId=u.eventId);Z.u7=g.Jn(u.trackingParams);Z.C=g.Jn(u.closeTrackingParams);Z.yH=g.Jn(u.iconTrackingParams)},Xuw=function(Z){var u;
(u=Z)&&!(u=Z.length>1?Z.charAt(0)==="/"&&Z.charAt(1)!=="/":Z==="/")&&(u=Z.replace(/^(https?:)?\/\//,"").split("/",1),u=!u||u.length<1||!u[0]?[]:u[0].toLowerCase().split(".").reverse(),u=u[0]==="com"&&u[1]==="youtube"||u[0]==="be"&&u[1]==="youtu");return u?Z.indexOf("/redirect?")===-1:!1},nQi=function(Z,u,G){u&&(G?rF(Z,u.map(function(y){return g.Yx(y,G)})):rF(Z,u))},lke=function(Z){g.t7(Z.zw(),[g.CZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.l7(Z.B,Z.D,5);Z.d_();Z.G=g.sK("ytp-cards-button",Z.B.getRootNode());Z.kx=g.sK("iv-drawer-close-button",Z.D);Z.isInitialized=!0},xs=function(Z,u,G){e8.call(this,Z,u,G);
this.U=null;this.K=!1;this.T=null;this.D=!1;this.j=this.X=this.G=null},eue=function(Z,u,G){G.stopPropagation();
DVJ(Z);MEi(Z,u);Z.j.focus()},T7H=function(Z){g.O.call(this);
this.U=Z||window;this.j=[]},YJH=function(Z){if(!Z.metaInfo||Z.metaInfo.length===0)return"";
var u=[];Z=g.m(Z.metaInfo);for(var G=Z.next();!G.done;G=Z.next())u.push(Q1("li","",G.value));return{Z:"ul",Y:"iv-card-meta-info",L:u}},mVi=function(Z,u){Z.Fn.U7?(u=new gF([0,
Z.U.scrollTop],[0,u.m2.offsetTop],600,kBk),Z.context.T.listen(u,"animate",function(G){Z.U.scrollTop=G.y}),Z.context.T.listen(u,"finish",function(G){Z.U.scrollTop=G.y}),u.play()):(Z.Fn.s7(!0),Z.U.scrollTop=u.m2.offsetTop,Z.Fn.s7(!1))},hL=function(Z,u){if(!fki(Z,u)||qeJ(Z,u)){var G=JUd(Z,u);
if(G){var y={a_:u,m2:G.element,dX:!1};if(u.onClickCommand)Z.B.S("web_infocards_teaser_show_logging_fix")&&(Z.DY||aW4(Z),spe(Z,u.id),G=Z.findLastIndex(y),g.Dh(Z.cards,G,0,y));else{Z.isInitialized||lke(Z);spe(Z,u.id);var q=Z.findLastIndex(y);g.Dh(Z.cards,q,0,y);G.gH(Z.U,q);Z.Fi()}u.autoOpen?Z.addCueRange(u.startMs,0x8000000000000,u.id,function(){Z.T||(Z.j=y,kY(Z),mVi(Z,y),u9(Z,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(G=Z.context.B.getCurrentTime()*1E3,G<5E3&&G>u.startMs&&YeJ(Z,y),Z.addCueRange(u.startMs,
u.startMs+1,u.id,function(){YeJ(Z,y)}),kY(Z))}}},Zs4=function(Z){this.B=Z},wF=function(Z,u,G){function y(){N||(q++,q===u.length&&(e.stop(),G&&G()))}
if(!u||u.length===0||qT(Z))G&&G();else{u=jpJ(Z,u);var q=0,N=!1,e=new g.fy(function(){N=!0;G&&G()},1E3,Z);
e.start();for(Z=0;Z<u.length;Z++)g.hv(u[Z],y)}},Jtw=function(Z){var u=Z.player.getVideoData();
if(u.L5){var G=Z.player.J().Mu.get(u.videoId);if(G){var y={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(q,N,e){q=Z.loadNumber;N=u.videoId;Z.loaded&&Z.loadNumber===q&&Z.player.getVideoData().videoId===N&&(e=g.Bw(e)&&e.responseXML?e.responseXML:null)&&oqR(Z,e)}};
g.Fh()&&(y.onFinish=Eqk(Z,y.onFinish));y.postParams={ic_only:"1"};Qpe(y,G);Z.C=!0;g.Je(u.L5,y)}}},EQd=function(Z,u){u=!u.isCued()&&!g.T(u,1024);
Z.U.s7(u);Z.T.s7(u)},IWR=function(Z,u){var G=u.cardId?u.cardId:"cr:"+Z.K,y=Z.B.J().experiments.i7("enable_error_corrections_infocard_web_client");
if(!u.content&&u.teaser.simpleCardTeaserRenderer&&y){var q=u.teaser.simpleCardTeaserRenderer,N=u.icon?u.icon.infoCardIconRenderer:null;if(q.channelAvatar&&q.channelAvatar.thumbnails&&q.channelAvatar.thumbnails.length>0)var e=dU(q.channelAvatar.thumbnails,22,22).url;u={id:G,timestamp:Z.K,type:"simple",teaserText:g.Ah(q.message),teaserDurationMs:Number(u.cueRanges[0].teaserDurationMs),startMs:Number(u.cueRanges[0].startCardActiveMs),autoOpen:!!u.autoOpen,sessionData:{},sponsored:!1,Gh:{},X7:null,Eh:q.trackingParams?
g.Jn(q.trackingParams):null,yH:N&&N.trackingParams?g.Jn(N.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,eT:null,title:"",customMessage:"",url:null,onClickCommand:q.onTapCommand||null,T2:e};hL(Z,u)}else{var h;if((h=u.content)==null?0:h.simpleCardContentRenderer){if(!u.cueRanges.length)return;e=(q=u.content)==null?void 0:q.simpleCardContentRenderer;q=u.teaser.simpleCardTeaserRenderer;N=u.icon?u.icon.infoCardIconRenderer:null;u={id:G,timestamp:Z.K,type:"simple",teaserText:g.Ah(q.message),
teaserDurationMs:Number(u.cueRanges[0].teaserDurationMs),startMs:Number(u.cueRanges[0].startCardActiveMs),autoOpen:!!u.autoOpen,sessionData:NT(Z,G,u,e),sponsored:!1,Gh:GZ(e,q,e.command),X7:e.trackingParams?g.Jn(e.trackingParams):null,Eh:q.trackingParams?g.Jn(q.trackingParams):null,yH:N&&N.trackingParams?g.Jn(N.trackingParams):null,imageUrl:dU(e.image.thumbnails,290,290).url,displayDomain:e.displayDomain?g.Ah(e.displayDomain):null,showLinkIcon:!!e.showLinkIcon,eT:null,title:e.title?g.Ah(e.title):"",
customMessage:e.callToAction?g.Ah(e.callToAction):"",url:g.C(e.command,g.hK).url?Ry({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:g.C(e.command,g.hK).url}):null,onClickCommand:null};hL(Z,u)}else{var d;if((d=u.content)==null?0:d.collaboratorInfoCardContentRenderer){if(!u.cueRanges.length)return;e=(N=u.content)==null?void 0:N.collaboratorInfoCardContentRenderer;q=u.teaser.simpleCardTeaserRenderer;N=u.icon?u.icon.infoCardIconRenderer:null;u={id:G,timestamp:Z.K,type:"collaborator",
teaserText:g.Ah(q.message),teaserDurationMs:Number(u.cueRanges[0].teaserDurationMs),startMs:Number(u.cueRanges[0].startCardActiveMs),autoOpen:!!u.autoOpen,sessionData:NT(Z,G,u,e),sponsored:!1,Gh:GZ(e,q,e.endpoint),X7:e.trackingParams?g.Jn(e.trackingParams):null,Eh:q.trackingParams?g.Jn(q.trackingParams):null,yH:N&&N.trackingParams?g.Jn(N.trackingParams):null,channelId:g.C(e.endpoint,g.gl).browseId,customMessage:e.customText?g.Ah(e.customText):null,profileImageUrl:dU(e.channelAvatar.thumbnails,290,
290).url,title:e.channelName?g.Ah(e.channelName):"",metaInfo:[e.subscriberCountText?g.Ah(e.subscriberCountText):""],url:Ry({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:g.C(e.endpoint,g.gl).canonicalBaseUrl?g.C(e.endpoint,g.gl).canonicalBaseUrl:"/channel/"+g.C(e.endpoint,g.gl).browseId}),onClickCommand:null};hL(Z,u)}else{var K;if((K=u.content)==null?0:K.playlistInfoCardContentRenderer){if(!u.cueRanges.length)return;var f;e=(f=u.content)==null?void 0:f.playlistInfoCardContentRenderer;
q=u.teaser.simpleCardTeaserRenderer;N=u.icon?u.icon.infoCardIconRenderer:null;u={id:G,timestamp:Z.K,type:"playlist",teaserText:g.Ah(q.message),teaserDurationMs:Number(u.cueRanges[0].teaserDurationMs),startMs:Number(u.cueRanges[0].startCardActiveMs),autoOpen:!!u.autoOpen,sessionData:NT(Z,G,u,e),sponsored:!1,Gh:GZ(e,q,e.action),X7:e.trackingParams?g.Jn(e.trackingParams):null,Eh:q.trackingParams?g.Jn(q.trackingParams):null,yH:N&&N.trackingParams?g.Jn(N.trackingParams):null,OV:dU(e.playlistThumbnail.thumbnails,
258,290).url,customMessage:e.customMessage?g.Ah(e.customMessage):null,playlistVideoCount:g.Ah(e.playlistVideoCount),title:e.playlistTitle?g.Ah(e.playlistTitle):"",metaInfo:[e.channelName?g.Ah(e.channelName):"",e.videoCountText?g.Ah(e.videoCountText):""],url:Ry({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:fWd(e.action)}),onClickCommand:null};hL(Z,u)}else{var V;if((V=u.content)==null?0:V.videoInfoCardContentRenderer){if(!u.cueRanges.length)return;var X;e=(X=u.content)==
null?void 0:X.videoInfoCardContentRenderer;q=u.teaser.simpleCardTeaserRenderer;N=u.icon?u.icon.infoCardIconRenderer:null;u={id:G,timestamp:Z.K,type:"video",teaserText:g.Ah(q.message),teaserDurationMs:Number(u.cueRanges[0].teaserDurationMs),startMs:Number(u.cueRanges[0].startCardActiveMs),autoOpen:!!u.autoOpen,sessionData:NT(Z,G,u,e),sponsored:!1,Gh:GZ(e,q,e.action),X7:e.trackingParams?g.Jn(e.trackingParams):null,Eh:q.trackingParams?g.Jn(q.trackingParams):null,yH:N&&N.trackingParams?g.Jn(N.trackingParams):
null,OV:dU(e.videoThumbnail.thumbnails,258,290).url,videoDuration:e.lengthString?g.Ah(e.lengthString):null,customMessage:e.customMessage?g.Ah(e.customMessage):null,title:e.videoTitle?g.Ah(e.videoTitle):"",metaInfo:[e.channelName?g.Ah(e.channelName):"",e.viewCountText?g.Ah(e.viewCountText):""],isLiveNow:!!e.badge,url:Ry({pause_on_navigation:!Z.context.videoData.isLivePlayback,target:"new",value:fWd(e.action)}),onClickCommand:null};hL(Z,u)}}}}}Z.K++},Hsk=function(){var Z=g.Jr();
g.Re(bm,function(u){UVv(u,Z)});
g.fV(bm)||puw()},YeJ=function(Z,u){if(!g.c_(Z.B.getRootNode(),"ytp-cards-teaser-shown")){if(Z.j!==u){var G=g.ZD(),y=Z.j?Z.j.a_.yH:Z.yH;
G&&y&&g.o_(G,[y]);Z.j=u;kY(Z)}(G=Z.isInitialized&&Z.zw().style.display=="none")||(G=Z.context.B.getPlayerState(),y=G===0&&Z.context.B.getCurrentTime()===0,G=!(G===1||G===3||y));if(!G&&u.a_.teaserDurationMs){var q;G={teaserText:u.a_.teaserText,durationMs:u.a_.teaserDurationMs,onClickCommand:u.a_.onClickCommand,T2:(q=u.a_.T2)!=null?q:null};Z.B.iC(!0,G)}Z.JT.isActive()||((!Z.T||!Z.Zi.isActive()&&Z.Mu)&&mVi(Z,u),Z.JT.start(910+u.a_.teaserDurationMs))}},UVv=function(Z,u){u<Z.startTime&&(Z.endTime=u+Z.endTime-
Z.startTime,Z.startTime=u);
Z.progress=(u-Z.startTime)/(Z.endTime-Z.startTime);Z.progress>1&&(Z.progress=1);Z.X=1E3/(u-Z.D);Z.D=u;hui(Z,Z.progress);Z.progress==1?(Z.j=0,$Y(Z),Z.onFinish(),Z.xD()):Z.isPlaying()&&Z.M1()},F0=function(Z,u,G,y){if(y){u=g.m(u);
for(var q=u.next();!q.done;q=u.next())Z.j(q.value,y,G.id,G.sessionData,G.Gh.click,5)}},DVJ=function(Z){Z.G.stop();
Z.isCollapsed&&(g.hF(Z.zw(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),Z.isCollapsed=!1,Z.j&&Z.j.removeAttribute("aria-hidden"),g.W3(Z.U,!1),g.W3(Z.T,!0))},K0=function(Z){return Z.j&&Z.j.a_?Z.j.a_:Z.cards[0]&&Z.cards[0].a_?Z.cards[0].a_:null},BSR=function(Z,u){return u?u:Xuw(Z)?"current":"new"},ZO=function(Z,u,G,y,q,N,e){Z.context.j.listen(u,"click",function(h){Z.GL(G,y,q,N||[],e||0,h)});
Z.context.j.listen(u,"touchstart",function(){Z.LV=!1});
Z.context.j.listen(u,"touchmove",function(){Z.LV=!0})},dU=function(Z,u,G){for(var y=-1,q=-1,N=0;N<Z.length;N++){if(Z[N].height===u||Z[N].width===G)return Z[N];
((Z[N].height||0)<u||(Z[N].width||0)<G)&&(y<0||(Z[y].height||0)<(Z[N].height||0)||(Z[y].width||0)<(Z[N].width||0))?y=N:((Z[N].height||0)>=u||(Z[N].width||0)>=G)&&(q<0||(Z[q].height||0)>(Z[N].height||0)||(Z[q].width||0)>(Z[N].width||0))&&(q=N)}return Z[q>=0?q:y]},bhR=function(Z){var u=new g.P({Z:"div"});
g.W3(u.element,!1);var G=new CrH(Z.player,u.element,yE(Z));g.M(G,u);u.gH(Z.U.element);G.yZ();return G},u9=function(Z,u,G){if(!Z.T){Z.Hu.show();
Z.nV=new g.fy(function(){g.AM(Z.context.B.getRootNode(),g.CZ.IV_DRAWER_OPEN)},0);
Z.nV.start();Z.al.V(Z.U,"mousewheel",function(e){Z.Zi.start();e.preventDefault();e=e||window.event;var h=0;e.type=="MozMousePixelScroll"?h=0==(e.axis==e.HORIZONTAL_AXIS)?e.detail:0:window.opera?h=e.detail:h=e.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?e.wheelDeltaY/-30:e.wheelDeltaY/-1.2:e.wheelDelta/-1.6:e.wheelDeltaY/-3;if(e=h)Z.U.scrollTop+=e});
Z.T=!0;var y=g.ZD();y&&Z.u7&&Z.C&&g.Fg(y,[Z.u7,Z.C]);u={TRIGGER_TYPE:u};for(var q=g.m(Z.cards),N=q.next();!N.done;N=q.next())N=N.value,N.dX||(N.dX=!0,nQi(Z.context.logger,N.a_.Gh.J9,u)),y&&g.Fg(y,[N.a_.X7]);OZ(Z.B);G&&(Z.X=new g.fy(function(){Z.SD=Z.G;Z.kx.focus()},330),Z.X.start())}},Rai=function(Z,u){this.context=Z;
this.j=u},tEs=function(Z,u,G){e8.call(this,Z,u,G);
var y=this;this.C=this.isCollapsed=this.Fn=!1;this.X=5E3;this.U=this.T=this.j=this.D=null;this.K=this.createElement({Z:"div",Il:["iv-promo-contents"]});this.G=new g.fy(function(){y.j.setAttribute("aria-hidden","true");g.W3(y.T,!1);g.W3(y.U,!0)},700,this);
g.M(this,this.G)},WEJ=function(Z,u){return Z.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(G){var y=unescape(G);
y=y.substring(1,y.length-1);return u[y]?escape(u[y]):G})},WuP=function(Z,u){var G=G===void 0?0:G;
var y=iAi(u).width;g.eU(u,y);G=new N7i(u,[y,u.offsetTop],[y-y-G,u.offsetTop],200,rUs);g.M(Z,G);Z.context.T.listen(G,"begin",function(){g.W3(u,!0)});
G.play()},puw=function(){Iy||(Iy=new g.fy(function(){Hsk()},20));
var Z=Iy;Z.isActive()||Z.start()},hai=function(Z,u,G){g.w4(u.element,"ytp-ce-element-hover");
g.w4(u.element,"ytp-ce-force-expand");vh(Z,G.id,!1)},Ta=function(Z){if(Z.oH)var u=Z.oH.thumbnails;
return Hhi(u?u[u.length-1].url:null)},MEi=function(Z,u){Z.D||(Z.D=g.kh(function(){Uri(this);
SJP(this)},u,Z))},jRP=function(Z){var u=Z.player.getVideoData(),G=u.videoId;
Z.D&&Z.D.abort();G={method:"POST",onFinish:function(q){var N=Z.D=null;q.status===200&&(q=q.responseText,q.substring(0,3)===")]}"&&(q=q.substring(3),N=JSON.parse(q),N=yUH(N,NSd(Z))));CL(Z,N)},
urlParams:{v:G},withCredentials:!0};Z.Fn&&(G.urlParams.ptype="embedded");var y=u.qX;y&&(G.postParams={ad_tracking:y});if(u=g.Q2G(u))if(u=g.cX(u),u=g.hr(u))Z.D=g.Je(u,G)},OsJ=function(Z,u){this.merchant=Z;
this.price=u},FEP=function(Z,u,G){Z.C=!0;
Z.G=g.Je(u,G)},Ry=function(Z){if(!Z)return null;
var u=g.cX(zaJ(Z.value));u=g.hr(u);if(!u)return null;var G=S3(Z.target,Atd,"current");if(G==null)Z=null;else{var y=Z.show_link_icon;Z=new dVi(u,G,y==="true"||y==="false"?y==="true":!0,Z.pause_on_navigation!=null?Z.pause_on_navigation:!0)}return Z},LE4=function(Z,u){return g.fQ(Z.cards,function(G){return G.a_.id===u})},oqR=function(Z,u){var G=!1,y=u.getElementsByTagName("annotations");
if(y&&!(y.length<1)&&(y=y[0].getAttribute("itct"))){var q=g.ZD();if(q){var N=g.vw();N&&g.rc(g.vN)(void 0,q,N,[g.Jn(y)])}}u=u.getElementsByTagName("annotation");for(y=0;y<u.length;y++){N=ihv(Z,u[y]);q=null;try{if(N){var e=N.id,h=/.+/;var d=typeof e==="string"&&h!=null&&e!=null&&e.match(h)?e:"";var K=S3(N.type,zus),f=S3(N.style,LuR),V=zaJ(N.data),X=V.length!==0?JSON.parse(V):{};var n=N.action;N=lWa;if(n==null)var l=null;else if(g.rA(n)){h=[];for(var Y=g.m(n),E=Y.next();!E.done;E=Y.next()){var W=N(E.value);
W&&h.push(W)}l=h}else{var p=N(n);l=p?[p]:[]}q=d&&K?new AUe(d,K,f,l,X):null}else q=null}catch(yv){}if(q)if(q.type==="branding"||q.type==="promotion"){N=Z;h=q;var z=Kuw(N),L=null;switch(h.type){case "branding":if(N.player.J().VF)break;N.player.S("web_player_overlay_positioned_layout")?(z.setAttribute("data-overlay-order","11"),N.player.Gm(z,4,!0)):N.U.element.appendChild(z);L=new xs(z,yE(N),h);break;case "promotion":g.l7(N.player,z,4),L=new tEs(z,yE(N),h)}L&&L.yZ();if(N=L)g.M(Z,N),Z.X[q.id]=N}else if(q.type===
"card"||q.type==="drawer"){Z.j||(Z.j=bhR(Z),g.M(Z,Z.j));if(q.type==="card"){z=Z.j;var Q=(G=q)&&G.data&&G.data.card_type;q=G.data;if(Q)switch(N=q.tracking||{},N={J9:N.impression,click:N.click,close:N.close,pN:N.teaser_impression,VI:N.teaser_click},h=q.tracking_params||{},L=null,Q){case "collaborator":G={id:G.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||
!1,Gh:N,X7:h.card?g.Jn(h.card):null,Eh:h.teaser?g.Jn(h.teaser):null,yH:h.icon?g.Jn(h.icon):null,channelId:q.channel_id,customMessage:q.custom_message?q.custom_message:null,profileImageUrl:q.image_url,title:q.title,metaInfo:q.meta_info,url:Ry({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};hL(z,G);break;case "playlist":G={id:G.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,
autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,Gh:N,X7:h.card?g.Jn(h.card):null,Eh:h.teaser?g.Jn(h.teaser):null,yH:h.icon?g.Jn(h.icon):null,OV:q.image_url,playlistVideoCount:q.playlist_video_count,customMessage:q.custom_message?q.custom_message:null,title:q.title,metaInfo:q.meta_info,url:Ry({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};hL(z,G);break;case "productListing":q.signin_url&&(L=Ry({target:"current",
value:q.signin_url}));Q=[];for(var b=q.offers||[],w=0;w<b.length;w++)Q.push(new OsJ(g.p8(b[w].merchant),g.p8(b[w].price)));G={id:G.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,Gh:N,X7:h.card?g.Jn(h.card):null,Eh:h.teaser?g.Jn(h.teaser):null,yH:h.icon?g.Jn(h.icon):null,imageUrl:q.image_url,displayDomain:q.display_domain?q.display_domain:
null,showLinkIcon:!!q.show_link_icon,eT:q.button_icon_url?q.button_icon_url:null,title:q.title,customMessage:q.custom_message?q.custom_message:null,url:Ry({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),K6n:L,YFD:q.signin_title?q.signin_title:void 0,Xen:q.signin_message?q.signin_message:void 0,offers:Q,onClickCommand:null};hL(z,G);break;case "simple":G={id:G.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,
startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,Gh:N,X7:h.card?g.Jn(h.card):null,Eh:h.teaser?g.Jn(h.teaser):null,yH:h.icon?g.Jn(h.icon):null,imageUrl:q.image_url,displayDomain:q.display_domain?q.display_domain:null,showLinkIcon:!!q.show_link_icon,eT:q.button_icon_url?q.button_icon_url:null,title:q.title,customMessage:q.custom_message?q.custom_message:null,url:Ry({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};
hL(z,G);break;case "video":G={id:G.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,Gh:N,X7:h.card?g.Jn(h.card):null,Eh:h.teaser?g.Jn(h.teaser):null,yH:h.icon?g.Jn(h.icon):null,OV:q.image_url,videoDuration:q.video_duration||null,customMessage:q.custom_message?q.custom_message:null,title:q.title,metaInfo:q.meta_info,isLiveNow:!!q.is_live_now,
url:Ry({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null},hL(z,G)}}else VEe(Z.j,q);G=!0}}G&&(OZ(Z.player),Z.UB())},Qpe=function(Z,u){Z.method="POST";
Z.postParams=Z.postParams||{};u.xZ&&(Z.postParams.ic_coll=u.xZ);u.v_&&(Z.postParams.ic_xml=u.v_);u.EC&&(Z.postParams.ic_track=u.EC)},sRe=function(Z){g.gC.call(this,Z);
this.D=this.endscreen=null;this.U={};this.X={};this.G=this.T=null;this.C=[];this.j=null;this.Qn=!0;this.K=0;Z=Z.J();this.Fn=g.Ja(Z)||g.qO(Z);this.events=new g.Ch(this);g.M(this,this.events);this.events.V(this.player,g.ir("creatorendscreen"),this.onCueRangeEnter);this.events.V(this.player,g.kq("creatorendscreen"),this.onCueRangeExit);this.events.V(this.player,"resize",this.Hy);this.events.V(window,"focus",this.ZTD);this.load();var u=g.Ol("STYLE");(g.jN("HEAD")[0]||document.body).appendChild(u);this.addOnDisposeCallback(function(){g.qr(u)});
u.sheet&&(u.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),u.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))};
g.Jk.prototype.iC=g.$r(39,function(Z,u){var G=g.Bn(this.gt());G&&G.iC(Z,u)});
var bm={},Iy=null;g.O9(gF,g.m8);g.D=gF.prototype;g.D.getDuration=function(){return this.duration};
g.D.play=function(Z){if(Z||this.j==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;$Y(this);this.startTime=Z=g.Jr();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.HL();this.tZ("play");this.isPaused()&&this.tZ("resume");this.j=1;var u=g.La(this);u in bm||(bm[u]=this);puw();UVv(this,Z);return!0};
g.D.stop=function(Z){$Y(this);this.j=0;Z&&(this.progress=1);hui(this,this.progress);this.onStop();this.xD()};
g.D.pause=function(){this.isPlaying()&&($Y(this),this.j=-1,this.tZ("pause"))};
g.D.tT=function(){this.j==0||this.stop(!1);this.tZ("destroy");gF.lN.tT.call(this)};
g.D.destroy=function(){this.dispose()};
g.D.M1=function(){this.tZ("animate")};
g.D.tZ=function(Z){this.dispatchEvent(new pvJ(Z,this))};
g.O9(pvJ,g.tq);g.O9(sZ,gF);sZ.prototype.T=function(){};
sZ.prototype.M1=function(){this.T();sZ.lN.M1.call(this)};
sZ.prototype.xD=function(){this.T();sZ.lN.xD.call(this)};
sZ.prototype.HL=function(){this.T();sZ.lN.HL.call(this)};
g.O9(N7i,sZ);N7i.prototype.T=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.I(T7H,g.O);g.D=T7H.prototype;g.D.listen=function(Z,u,G,y){G=(0,g.YW)(G,y||this.U);Z=g.Uh(Z,u,G);this.j.push(Z);return Z};
g.D.iK=function(Z,u,G,y){G=(0,g.YW)(G,y||this.U);Z=qJe(Z,u,G);this.j.push(Z);return Z};
g.D.SI=function(Z){g.pr(Z);g.lu(this.j,Z)};
g.D.removeAll=function(){g.pr(this.j);this.j.length=0};
g.D.tT=function(){this.removeAll();g.O.prototype.tT.call(this)};g.I(sRe,g.gC);g.D=sRe.prototype;g.D.load=function(){g.gC.prototype.load.call(this);if(!qT(this)){var Z=g.Fzt(this.player.getVideoData());Z?(Z=yUH(Z,NSd(this)),CL(this,Z,!1)):jRP(this)}};
g.D.unload=function(){CL(this,null);this.D&&(this.D.abort(),this.D=null);g.gC.prototype.unload.call(this)};
g.D.ox=function(Z,u){return qT(this)?Z==="loadCustomEndscreenRenderer"?(Z=yUH(u,"new"),CL(this,Z),!0):null:null};
g.D.getOptions=function(){return qT(this)?["loadCustomEndscreenRenderer"]:[]};
g.D.Hy=function(){if(this.endscreen&&this.endscreen.elements){var Z=this.player.getVideoContentRect();if(Z&&Z.width!==0&&Z.height!==0){var u=this.player.getPlayerSize();if(u&&u.width!==0&&u.height!==0){var G=Z.width/Z.height;var y=0;for(var q=-1,N=0;N<vQv.length;N++){var e=Math.abs(u.width-vQv[N]);if(q===-1||y>=e)q=N,y=e}y=SeR[q];this.T&&g.O0(this.T.element,"outline-width",Math.max(u.width,u.height)+"px");for(u=0;u<this.endscreen.elements.length;++u)if(N=this.endscreen.elements[u].id,q=this.U[N],
e=this.X[N],q&&e){var h=e.width*G/e.aspectRatio,d=Math.round(e.width*Z.width);N=Math.round(h*Z.height);var K=Z.left+Math.round(e.left*Z.width),f=Z.top+Math.round(e.top*Z.height);g.wM(q.element,d,N);g.eU(q.element,K,f);g.hF(q.element,Rua);d>256||N>256?g.AM(q.element,"ytp-ce-large-round"):d>96||N>96?g.AM(q.element,"ytp-ce-medium-round"):g.AM(q.element,"ytp-ce-small-round");g.hF(q.element,C4i);d=e.left+e.width/2;e=e.top+h/2;g.AM(q.element,d<=.5&&e<=.5?"ytp-ce-top-left-quad":d>.5&&e<=.5?"ytp-ce-top-right-quad":
d<=.5&&e>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.hF(q.element,SeR);g.AM(q.element,y);(q=g.i4(document,"div","ytp-ce-expanding-overlay-body",q.element)[0])&&g.O0(q,"height",N+"px")}}}}};
g.D.onCueRangeEnter=function(Z){if(this.endscreen)if(Z.getId()==="ytp-ce-in-endscreen")wF(this,this.endscreen.impressionUrls),(Z=g.ZD())&&this.endscreen.visualElement&&g.Pw(Z,this.endscreen.visualElement),this.j&&(g.AM(this.j,"ytp-ce-element-show"),this.j.removeAttribute("aria-hidden"),this.player.g2()?g.AM(this.j,"ytp-ce-hide-button-lower"):g.w4(this.j,"ytp-ce-hide-button-lower"));else{Z=Z.getId().substring(15);var u=this.U[Z],G=this.X[Z];g.AM(u.element,"ytp-ce-element-show");u.element.removeAttribute("aria-hidden");
u=this.player.getRootNode();g.AM(u,"ytp-ce-shown");wF(this,G.impressionUrls);(u=g.ZD())&&g.Pw(u,G.visualElement);this.player.J().C&&this.player.pV("endscreenelementshown",Z)}};
g.D.onCueRangeExit=function(Z){if(Z.getId()==="ytp-ce-in-endscreen")this.j&&(g.w4(this.j,"ytp-ce-element-show"),this.j.setAttribute("aria-hidden","true"));else{Z=Z.getId().substring(15);var u=this.U[Z];g.w4(u.element,"ytp-ce-element-show");u.element.setAttribute("aria-hidden","true");u=this.player.getRootNode();g.w4(u,"ytp-ce-shown");this.player.J().C&&this.player.pV("endscreenelementhidden",Z)}};
g.D.ZTD=function(Z){var u=this;Z.target===window&&(new g.fy(function(){for(var G=g.m(Object.values(u.U)),y=G.next();!y.done;y=G.next())g.hF(y.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.D.s7=function(Z){for(var u=g.m(Object.values(this.U)),G=u.next();!G.done;G=u.next())G=G.value,Z?G.element.setAttribute("hidden",""):G.element.removeAttribute("hidden")};
g.D.yd6=function(Z){this.j&&this.player.getRootNode().removeChild(this.j);Z&&(g.AM(Z,"ytp-ce-hide-button-container"),this.j=Z,g.l7(this.player,this.j,4))};
var vQv=[346,426,470,506,570,640,853,1280,1920],SeR="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),C4i=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Rua=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Atd={EC7:"current",CgV:"new"};var VAi={CLOSE:"close",rZn:"openUrl",SUBSCRIBE:"subscribe"},Xvd={yX1:"click",CLOSE:"close",TsV:"hidden",Wiu:"rollOut",cnx:"rollOver",Dox:"shown"};AUe.prototype.M0=function(){var Z=B7H(this,function(u){return u.type==="openUrl"&&u.url!=null});
return Z?Z.url:null};
var LuR={rcx:"anchored",Ed:"branding",CHANNEL:"channel",QTn:"cta",xSD:"highlightText",WWH:"label",PLAYLIST:"playlist",POPUP:"popup",ZWm:"speech",SUBSCRIBE:"subscribe",V7m:"title",VIDEO:"video",u9D:"website"},zus={Ed:"branding",XTx:"card",qmn:"drawer",OYn:"highlight",gR6:"marker",RjD:"promotion",TEXT:"text",rru:"widget"};var ulv=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
GEe=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.I(im,g.O);g.D=im.prototype;g.D.addCueRange=function(Z,u,G,y,q){Z=new g.BX(Z,u,{id:G,namespace:"annotations_module"});y&&this.sT.set(Z,y);q&&this.wH.set(Z,q);this.context.B.JP([Z],1)};
g.D.yZ=function(){this.context.U.subscribe("resize",this.Fi,this)};
g.D.zw=function(){return this.element};
g.D.GL=function(Z,u,G,y,q,N){if(this.LV)return!1;N&&(N.stopPropagation(),N.preventDefault());this.navigate(Z,G,y,q);return!1};
g.D.show=function(){};
g.D.hide=function(){};
g.D.destroy=function(){g.qr(this.zw())};
g.D.Fi=function(){};
g.D.navigate=function(Z,u,G,y){var q=this,N=Ph(Z);if(N){var e=BSR(N,Z.target),h=function(){Z.j&&q.context.B.pauseVideo();var d=q.context.videoData.Wc||!1,K=g.kG(N||"");d&&K&&(K.v||K.list)?q.context.B.CY(K.v,u,K.list,!1):g.y9(N||"",e==="current"?"_top":void 0,u)};
e==="new"&&(h(),h=null);rF(this.context.logger,G,h,y);Xuw(N)||(G=g.ZD(),y=u.itct,G&&y&&g.a3(G,g.Jn(y)))}};
g.D.tT=function(){this.sT.clear();this.wH.clear();g.O.prototype.tT.call(this)};
g.D.createElement=function(Z){Z=new g.P(Z);g.M(this,Z);return Z.element};g.I(CrH,im);g.D=CrH.prototype;g.D.Yv=function(){this.UT&&hL(this,this.UT)};
g.D.isAvailable=function(){var Z;if(Z=!!this.cards.length)(Z=this.B.getRootNode())?(Z=g.fk(Z),Z=173<Z.width&&173<Z.height):Z=!1;return Z};
g.D.Fi=function(){var Z=this.isAvailable();g.W3(this.zw(),Z);g.Bv(this.context.B.getRootNode(),g.CZ.IV_DRAWER_ENABLED,Z);OZ(this.B)};
g.D.destroy=function(){this.B.iC(!1);try{this.B.getRootNode().removeChild(this.D)}catch(Z){}g.g1(this.Qn);g.Xp(this.al);this.nV&&this.nV.dispose();this.X&&this.X.dispose();im.prototype.destroy.call(this)};
g.D.d_=function(){var Z=this;this.context.j.listen(g.sK("iv-drawer-close-button",this.D),"click",this.ZO,this);this.context.j.listen(this.U,"touchend",function(){Z.Zi.start()});
this.context.j.listen(this.U,"scroll",this.rB,this);this.context.U.subscribe("onHideControls",function(){Z.Mu=!0});
this.context.U.subscribe("onShowControls",function(){Z.Mu=!1});
this.context.U.subscribe("onVideoAreaChange",function(){Z.Mu=g.c_(Z.B.getRootNode(),"ytp-autohide")});
this.Qn.push(g.cb("iv-button-shown",this.CWT,this));this.Qn.push(g.cb("iv-button-hidden",this.PWi,this));aW4(this)};
g.D.findLastIndex=function(Z){if(this.cards.length===0)return 0;var u=g.GU(this.cards,function(G){return Z.a_.startMs>G.a_.startMs||Z.a_.startMs===G.a_.startMs&&Z.a_.timestamp>=G.a_.timestamp?!0:!1});
return u===-1?0:u+1};
g.D.ZO=function(){if(this.T){rF(this.context.logger,K0(this).Gh.close);var Z=g.ZD();Z&&this.C&&g.a3(Z,this.C);ch(this)}};
g.D.rB=function(){g.Bv(this.D,"iv-drawer-scrolled",this.U.scrollTop>0)};
g.D.CWT=function(){var Z=g.ZD(),u=K0(this);u=u?u.yH:this.yH;Z&&u&&g.Fg(Z,[u])};
g.D.PWi=function(){var Z=g.ZD(),u=K0(this);u=u?u.yH:this.yH;Z&&u&&g.o_(Z,[u])};
g.D.L9=function(){var Z=K0(this);rF(this.context.logger,Z.Gh.pN);var u=g.ZD();if(u&&Z)if(this.B.S("web_infocards_teaser_show_logging_fix")){var G=[];Z.Eh&&G.push(Z.Eh);Z.yH&&G.push(Z.yH);G.length>0&&g.Fg(u,G)}else g.Fg(u,[Z.Eh,Z.yH])};
g.D.yxn=function(){var Z=g.ZD(),u=K0(this);Z&&u&&g.o_(Z,[u.Eh])};
g.D.vU=function(Z){var u=K0(this),G=g.ZD();this.j?Z?(Z=this.context.logger,rF(Z,u.Gh.VI),Z.B.sendVideoStatsEngageEvent(4,void 0),G&&u.Eh&&g.a3(G,u.Eh)):(Z=this.context.logger,rF(Z,u.Gh.VI),Z.B.sendVideoStatsEngageEvent(4,void 0),G&&u.yH&&g.a3(G,u.yH)):(Z=this.context.logger,rF(Z,u.Gh.VI),Z.B.sendVideoStatsEngageEvent(4,void 0),G&&this.yH&&g.a3(G,this.yH))};g.I(e8,im);e8.prototype.yZ=function(){im.prototype.yZ.call(this);wvk(this)};
e8.prototype.show=function(){im.prototype.show.call(this);var Z=g.ZD(),u=this.annotation.data;Z&&u&&(u=u.session_data)&&g.Fg(Z,[g.Jn(u.itct)])};
e8.prototype.hide=function(){im.prototype.hide.call(this);var Z=g.ZD(),u=this.annotation.data;Z&&u&&(u=u.session_data)&&g.o_(Z,[g.Jn(u.itct)])};g.I(xs,e8);
xs.prototype.show=function(){if(!this.isActive){e8.prototype.show.call(this);if(!this.K){g.AM(this.zw(),"iv-branding");var Z=this.annotation.data;this.U=this.createElement({Z:"img",Il:["branding-img","iv-click-target"],N:{"aria-label":"Channel watermark",src:Z.image_url,width:Z.image_width,height:Z.image_height}});g.W3(this.U,!1);var u=this.createElement({Z:"button",Il:["branding-img-container","ytp-button"]});u.appendChild(this.U);this.zw().appendChild(u);var G=this.annotation.M0();G&&ZO(this,u,
G,this.annotation.id,Z.session_data);this.context.B.S("disable_branding_context")||uAa(this,Z);this.K=!0}g.W3(this.zw(),!0);this.isActive=!0;if(this.U){try{WuP(this,this.U)}catch(y){}g.AM(this.context.B.getRootNode(),"ytp-branding-shown");this.context.B.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
xs.prototype.hide=function(){this.isActive&&(e8.prototype.hide.call(this),g.W3(this.zw(),!1),this.isActive=!1,g.w4(this.context.B.getRootNode(),"ytp-branding-shown"))};
xs.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);g.w4(this.context.B.getRootNode(),"ytp-branding-shown");e8.prototype.destroy.call(this)};g.I(tEs,e8);g.D=tEs.prototype;g.D.show=function(){this.isActive||(e8.prototype.show.call(this),this.Fn||(xVJ(this),this.Fn=!0),g.W3(this.zw(),!0),g.kh(function(){g.w4(this.zw(),"iv-promo-inactive")},100,this),this.zw().removeAttribute("aria-hidden"),this.isActive=!0,Uri(this),DVJ(this),MEi(this,this.X))};
g.D.hide=function(){this.isActive&&(g.AM(this.zw(),"iv-promo-inactive"),this.isActive=!1,this.zw().setAttribute("aria-hidden","true"))};
g.D.GL=function(Z,u,G,y,q,N){return this.isCollapsed?!1:e8.prototype.GL.call(this,Z,u,G,y,q,N)};
g.D.Xun=function(Z){this.C=!0;eue(this,500,Z)};
g.D.ai1=function(){this.C=!1;SJP(this)};
g.D.Ii6=function(Z){Z.stopPropagation();this.hide()};
g.D.MDn=function(Z){Z.stopPropagation();Uri(this);this.isCollapsed=!0;g.AM(this.zw(),"iv-promo-collapsed-no-delay");this.G.start()};
g.D.destroy=function(){this.G.dispose();e8.prototype.destroy.call(this)};g.I(ytk,g.gC);g.D=ytk.prototype;g.D.ox=function(Z,u){if(!vqa(this.player.J().playerStyle))return null;switch(Z){case "loadCustomAnnotationsXml":return(Z=g.T1(u))&&oqR(this,Z),!0;case "removeCustomAnnotationById":return u&&this.j&&(spe(this.j,u),OZ(this.player)),!0}return null};
g.D.getOptions=function(){return vqa(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.D.aY=function(){var Z=this.player.J(),u=this.player.getVideoData(),G=Z.annotationsLoadPolicy||u.annotationsLoadPolicy;return u.Wc||this.player.isMutedByEmbedsMutedAutoplay()?!1:G===1&&!u.Si||Z.Mu.get(u.videoId)||g.Cj(u)||g.tJ(u)?!0:!1};
g.D.UB=function(){if(this.T){var Z=this.player.l7().getVideoContentRect(!0);g.wM(this.T.element,Z.width,Z.height);g.eU(this.T.element,Z.left,Z.top)}if(this.j){var u=this.player.RT();Z=this.j;u=u.width;g.Bv(Z.D,"iv-drawer-small",u<=426);g.Bv(Z.D,"iv-drawer-big",u>=1280)}};
g.D.WU=function(Z){EQd(this,Z.state);g.T(Z.state,2)&&(this.g2()&&this.S1()&&this.player.getPresentingPlayerType()!==2&&this.HJ(!1),this.iC(!1))};
g.D.load=function(){g.gC.prototype.load.call(this);EQd(this,this.player.getPlayerStateObject());this.loadNumber++;var Z=this.player.getVideoData();gqP(this,Z);g.l7(this.player,this.T.element,4);this.UB();var u=g.Cj(Z);u&&$rd(this,u);if((u=g.tJ(Z))&&u.featuredChannel){var G=u.featuredChannel;u=u.annotationId||"branding";var y=Z.videoId||null,q=Z.eventId||null;if(!this.player.J().VF){var N=[];G.navigationEndpoint&&g.C(G.navigationEndpoint,g.gl)&&g.C(G.navigationEndpoint,g.gl).browseId&&N.push(new nqd("openUrl",
"click",new dVi("/channel/"+g.C(G.navigationEndpoint,g.gl).browseId,"new",!0,!0)));var e=G.watermark.thumbnails[0];y={channel_name:G.channelName,end_ms:G.endTimeMs,image_height:e.height,image_type:1,image_url:e.url,image_width:e.width,is_mobile:!1,session_data:{annotation_id:u,ei:q,feature:"iv",itct:G.trackingParams,src_vid:y},start_ms:G.startTimeMs};if(G.subscribeButton&&g.C(G.subscribeButton,g.NU)){y.channel_id=g.C(G.subscribeButton,g.NU).channelId;var h;G=g.C(G.subscribeButton,g.NU);e=q=null;G.subscribed?
(G.subscriberCountWithUnsubscribeText&&(q=g.Ah(G.subscriberCountWithUnsubscribeText)),G.subscriberCountText&&(e=g.Ah(G.subscriberCountText))):(G.subscriberCountText&&(q=g.Ah(G.subscriberCountText)),G.subscriberCountWithSubscribeText&&(e=g.Ah(G.subscriberCountWithSubscribeText)));var d,K=((d=g.C((h=G.signInEndpoint)==null?void 0:h.commandMetadata,g.Jd))==null?void 0:d.url)||"";h={subscribeText:g.Ah(G.unsubscribedButtonText),subscribeCount:q||"",unsubscribeText:g.Ah(G.subscribedButtonText),unsubscribeCount:e||
"",enabled:G.enabled||!1,classic:!1,subscribed:G.subscribed||!1,feature:"iv",signInUrl:K};y.standalone_subscribe_button_data=h}h=new AUe(u,"branding","branding",N,y);d=Kuw(this);this.player.S("web_player_overlay_positioned_layout")?(d.setAttribute("data-overlay-order","11"),this.player.Gm(d,4,!0)):this.U.element.appendChild(d);h=new xs(d,yE(this),h);h.yZ();g.M(h,h);this.X[u]=h}}this.CT=g.sK("ytp-cards-button",this.player.getRootNode());g.Rc(Z)&&cUH(this,Z)};
g.D.onVideoDataChange=function(Z){var u=this.player.getVideoData();u.L5&&FEP(this,u.L5,Z)};
g.D.unload=function(){this.player.fK("annotations_module");for(var Z=g.m(Object.keys(this.X)),u=Z.next();!u.done;u=Z.next())this.X[u.value].destroy();this.Fn=null;this.j&&(this.j.destroy(),this.j=null,OZ(this.player));this.C=!1;this.G&&(this.G.abort(),this.G=null);this.Qn=!1;this.X={};this.U.hide();g.gC.prototype.unload.call(this);this.T.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.D.W8=function(Z){Z===this.player.getVideoData().videoId&&(this.loaded?Jtw(this):this.load())};
g.D.g2=function(){var Z;return((Z=this.j)==null?void 0:Z.isAvailable())||this.Qn};
g.D.S1=function(){return!!this.j&&this.j.T};
g.D.HJ=function(Z,u,G){u=u===void 0?!1:u;this.g2();this.j&&(Z?G?u9(this.j,G,u):u9(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",u):ch(this.j))};
g.D.iC=function(Z,u){this.player.publish(Z?"cardsteasershow":"cardsteaserhide",u)};
g.D.tT=function(){this.player.J().Mu.unsubscribe("vast_info_card_add",this.W8,this);g.w4(this.player.getRootNode(),g.CZ.IV_DRAWER_OPEN);for(var Z=this.UT,u=g.BW,G=0,y=Z.length;G<y;G++)u.qe(Z[G]);this.UT.length=0;g.gC.prototype.tT.call(this)};
g.D.createElement=function(Z){Z=new g.P(Z);g.M(this,Z);return Z.element};g.on("annotations_module",ytk);g.on("creatorendscreen",sRe);})(_yt_player);
