(function(g){var window=this;'use strict';var xw=function(Z){var u=Z.J(),G=g.lN||g.Ac?{style:"will-change: opacity"}:void 0,y=u.D,q=["ytp-videowall-still"];u.U&&q.push("ytp-videowall-show-text");g.P.call(this,{Z:"a",Il:q,N:{href:"{{url}}",target:y?u.Fn:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{Z:"div",Y:"ytp-videowall-still-image",N:{style:"{{background}}"}},{Z:"span",Y:"ytp-videowall-still-info",N:{"aria-hidden":"true"},L:[{Z:"span",Y:"ytp-videowall-still-info-bg",
L:[{Z:"span",Y:"ytp-videowall-still-info-content",N:G,L:[{Z:"span",Y:"ytp-videowall-still-info-title",T6:"{{title}}"},{Z:"span",Y:"ytp-videowall-still-info-author",T6:"{{author_and_views}}"},{Z:"span",Y:"ytp-videowall-still-info-live",T6:"Live"},{Z:"span",Y:"ytp-videowall-still-info-duration",T6:"{{duration}}"}]}]}]},{Z:"span",Il:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},L:[{Z:"span",Y:"ytp-videowall-still-listlabel-icon"},"Playlist",{Z:"span",
Y:"ytp-videowall-still-listlabel-length",L:[" (",{Z:"span",T6:"{{playlist_length}}"},")"]}]},{Z:"span",Il:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},L:[{Z:"span",Y:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Z:"span",Y:"ytp-videowall-still-listlabel-length",T6:" (50+)"}]}]});this.suggestion=null;this.U=y;this.api=Z;this.j=new g.Ch(this);g.M(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.V(Z,"videodatachange",
this.onVideoDataChange);Z.createServerVe(this.element,this);this.onVideoDataChange()},uXH=function(Z){Z.publish("autonavvisibility")},G$w=function(Z){h8.call(this,Z,"videowall-endscreen");
var u=this;this.B=Z;this.stills=[];this.T=this.videoData=null;this.D=this.X=!1;this.K=null;g.AM(this.element,"modern-videowall-endscreen");this.U=new g.Ch(this);g.M(this,this.U);this.G=new g.fy(function(){g.AM(u.element,"ytp-show-tiles")},0);
g.M(this,this.G);this.table=new g.Dw({Z:"div",Y:"ytp-modern-endscreen-content"});g.M(this,this.table);this.table.gH(this.element);Z.getVideoData().LV?this.j=new dq(Z,!0):this.j=new KX(Z);g.M(this,this.j);g.l7(this.player,this.j.element,4);Z.createClientVe(this.element,this,158789);this.hide()},fX=function(Z){h8.call(this,Z,"watch-again-on-youtube-endscreen");
this.watchButton=new ywi(Z,1);g.M(this,this.watchButton);this.watchButton.gH(this.element);g.wLo(Z)&&(this.j=new g.wb(Z),g.M(this,this.j),this.U=new g.P({Z:"div",Il:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],N:{tabIndex:"-1"},L:[this.j]}),g.M(this,this.U),this.j.gH(this.U.element),this.U.gH(this.element));Z.createClientVe(this.element,this,156914);this.hide()},h8d=function(Z){g.gC.call(this,Z);
var u=this;this.endScreen=null;this.j=this.U=this.T=!1;this.listeners=new g.Ch(this);g.M(this,this.listeners);var G=Z.J();Z.isEmbedsShortsMode()?this.endScreen=new fX(Z):qKi(Z)?(this.T=!0,NsH(this),this.j?this.endScreen=new VO(Z):G.S("delhi_modern_endscreen")?this.endScreen=new G$w(Z):this.endScreen=new XE(Z)):G.DJ?this.endScreen=new e8i(Z):this.endScreen=new h8(Z);g.M(this,this.endScreen);g.l7(Z,this.endScreen.element,4);xEi(this);this.listeners.V(Z,"videodatachange",this.onVideoDataChange,this);
this.listeners.V(Z,g.ir("endscreen"),function(y){u.onCueRangeEnter(y)});
this.listeners.V(Z,g.kq("endscreen"),function(y){u.onCueRangeExit(y)})},KAJ=function(Z,u){u=u.getWatchNextResponse();
var G,y;u=(G=dEe(u))==null?void 0:(y=G.nextButton)==null?void 0:y.buttonRenderer;Z.G=u==null?void 0:u.navigationEndpoint;G=u==null?void 0:u.trackingParams;Z.playButton&&G&&Z.B.setTrackingParams(Z.playButton.element,G)},ywi=function(Z,u){g.P.call(this,{Z:"button",
Il:["ytp-watch-on-youtube-button","ytp-button"],T6:"{{content}}"});this.B=Z;this.buttonType=this.buttonType=u;this.xX();this.buttonType===2&&g.AM(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.xX);this.s7(!0)},nX=function(Z){return g.OQ(Z.player)&&Z.TY()&&!Z.D},XJJ=function(Z){var u=fVd(Z),G=Math,y=G.min;
var q=Z.T?Date.now()-Z.T:0;G=y.call(G,q,u);V5k(Z,Math.ceil((u-G)/1E3));u-G<=500&&Z.nG()?Z.select(!0):Z.nG()&&Z.D.start()},h8=function(Z,u){g.P.call(this,{Z:"div",
Il:["html5-endscreen","ytp-player-content",u||"base-endscreen"]});this.created=!1;this.player=Z},n8e=function(Z){var u;
return!((u=Z.B.getVideoData())==null||!u.watchToWatchTransitionRenderer)},lR=function(Z){var u=Z.J(),G=u.D;
g.P.call(this,{Z:"a",Y:"ytp-autonav-suggestion-card",N:{href:"{{url}}",target:G?u.Fn:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{Z:"div",Il:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],N:{style:"{{background}}"},L:[{Z:"div",N:{"aria-label":"{{timestamp}}"},Il:["ytp-autonav-timestamp"],T6:"{{duration}}"},{Z:"div",Il:["ytp-autonav-live-stamp"],T6:"Live"},{Z:"div",
Il:["ytp-autonav-upcoming-stamp"],T6:"Upcoming"},{Z:"div",Y:"ytp-autonav-list-overlay",L:[{Z:"div",Y:"ytp-autonav-mix-text",T6:"Mix"},{Z:"div",Y:"ytp-autonav-mix-icon"}]}]},{Z:"div",Il:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],T6:"{{title}}"},{Z:"div",Il:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],T6:"{{author}}"},{Z:"div",Il:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],T6:"{{views_and_publish_time}}"}]});this.B=Z;this.suggestion=
null;this.j=G;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},xEi=function(Z){Z.player.fK("endscreen");
var u=Z.player.getVideoData();u=new g.BX(Math.max((u.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var G=new g.BX(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});Z.player.JP([u,G])},V5k=function(Z,u){u=u===void 0?-1:u;
Z=Z.j.Di("ytp-autonav-endscreen-upnext-header");g.Cz(Z);if(u>=0){u=String(u);var G="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],y="Up next in $SECONDS".indexOf(G);if(y>=0){Z.appendChild(g.IL("Up next in $SECONDS".slice(0,y)));var q=g.Ol("span");g.ed(q,"ytp-autonav-endscreen-upnext-header-countdown-number");g.vJ(q,u);Z.appendChild(q);Z.appendChild(g.IL("Up next in $SECONDS".slice(y+G.length)));return}}g.vJ(Z,"Up next")},e8i=function(Z){h8.call(this,Z,"subscribecard-endscreen");
this.j=new g.P({Z:"div",Y:"ytp-subscribe-card",L:[{Z:"img",Y:"ytp-author-image",N:{src:"{{profilePicture}}"}},{Z:"div",Y:"ytp-subscribe-card-right",L:[{Z:"div",Y:"ytp-author-name",T6:"{{author}}"},{Z:"div",Y:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.gH(this.element);var u=Z.getVideoData();this.subscribeButton=new g.cf("Subscribe",null,"Unsubscribe",null,!0,!1,u.Pg,u.subscribed,"trailer-endscreen",null,Z,!1);g.M(this,this.subscribeButton);this.subscribeButton.gH(this.j.Di("html5-subscribe-button-container"));
this.V(Z,"videodatachange",this.Vn);this.Vn();this.hide()},VO=function(Z){h8.call(this,Z,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.P({Z:"div",Y:"ytp-suggestion-panel",L:[{Z:"div",Il:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],T6:"More videos"}]});this.K=new g.P({Z:"div",Y:"ytp-suggestions-container"});this.videos=[];this.T=null;this.G=this.X=!1;this.U=new dq(this.player);g.M(this,this.U);this.U.gH(this.element);Z.getVideoData().LV?this.j=this.U:(this.j=new KX(Z),g.l7(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.P({Z:"div",
Y:"ytp-autonav-overlay-cancelled-state"});g.M(this,this.overlay);this.overlay.gH(this.element);this.D=new g.Ch(this);g.M(this,this.D);g.M(this,this.table);this.table.gH(this.element);this.table.show();g.M(this,this.K);this.K.gH(this.table.element);this.hide()},Da=function(Z){var u=Z.Dv();
u!==Z.G&&(Z.G=u,uXH(Z.player),Z.G?(Z.U!==Z.j&&Z.U.hide(),Z.table.hide()):(Z.U!==Z.j&&Z.U.show(),Z.table.show()))},MW=function(Z){var u=Z.Dv();
u!==Z.X&&(Z.X=u,uXH(Z.player))},lVi=function(Z,u){if(u)return u;
if(Z.api.isFullscreen()){var G;Z=(G=Z.api.getVideoData())==null?void 0:G.RL;return Z===-1||Z===void 0?8E3:Z}return Z.api.s_()>=0?Z.api.s_():g.Zh(Z.api.J().experiments,"autoplay_time")||1E4},dEe=function(Z){var u,G,y;
return Z==null?void 0:(u=Z.playerOverlays)==null?void 0:(G=u.playerOverlayRenderer)==null?void 0:(y=G.autoplay)==null?void 0:y.playerOverlayAutoplayRenderer},fVd=function(Z){if(Z.B.isFullscreen()){var u;
Z=(u=Z.B.getVideoData())==null?void 0:u.RL;return Z===-1||Z===void 0?8E3:Z}return Z.B.s_()>=0?Z.B.s_():g.Zh(Z.B.J().experiments,"autoplay_time")||1E4},dq=function(Z,u){u=u===void 0?!1:u;
g.P.call(this,{Z:"div",Y:"ytp-autonav-endscreen-countdown-overlay"});var G=this;this.X=u;this.cancelCommand=this.G=void 0;this.T=0;this.container=new g.P({Z:"div",Y:"ytp-autonav-endscreen-countdown-container"});g.M(this,this.container);this.container.gH(this.element);u=Z.J();var y=u.D;this.B=Z;this.suggestion=null;this.onVideoDataChange("newdata",this.B.getVideoData());this.V(Z,"videodatachange",this.onVideoDataChange);this.j=new g.P({Z:"div",Y:"ytp-autonav-endscreen-upnext-container",N:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{Z:"div",Y:"ytp-autonav-endscreen-upnext-header"},{Z:"div",Y:"ytp-autonav-endscreen-upnext-alternative-header",T6:"{{autoplayAlternativeHeader}}"},{Z:"a",Y:"ytp-autonav-endscreen-link-container",N:{href:"{{url}}",target:y?u.Fn:""},L:[{Z:"div",Y:"ytp-autonav-endscreen-upnext-thumbnail",N:{style:"{{background}}"},L:[{Z:"div",N:{"aria-label":"{{timestamp}}"},Il:["ytp-autonav-timestamp"],
T6:"{{duration}}"},{Z:"div",Il:["ytp-autonav-live-stamp"],T6:"Live"},{Z:"div",Il:["ytp-autonav-upcoming-stamp"],T6:"Upcoming"}]},{Z:"div",Y:"ytp-autonav-endscreen-video-info",L:[{Z:"div",Y:"ytp-autonav-endscreen-premium-badge"},{Z:"div",Y:"ytp-autonav-endscreen-upnext-title",T6:"{{title}}"},{Z:"div",Y:"ytp-autonav-endscreen-upnext-author",T6:"{{author}}"},{Z:"div",Y:"ytp-autonav-view-and-date",T6:"{{views_and_publish_time}}"},{Z:"div",Y:"ytp-autonav-author-and-view",T6:"{{author_and_views}}"}]}]}]});
g.M(this,this.j);this.j.gH(this.container.element);y||this.V(this.j.Di("ytp-autonav-endscreen-link-container"),"click",this.g7);this.B.createClientVe(this.container.element,this,115127);this.B.createClientVe(this.j.Di("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.P({Z:"div",Y:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.gH(this.container.element);this.U=new g.P({Z:"div",Y:"ytp-autonav-endscreen-button-container"});g.M(this,this.U);this.U.gH(this.container.element);
this.cancelButton=new g.P({Z:"button",Il:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",u.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],N:{"aria-label":"Cancel auto-play"},T6:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.gH(this.U.element);this.cancelButton.listen("click",this.U1,this);this.B.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.P({Z:"a",Il:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
u.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],N:{href:"{{url}}",role:"button","aria-label":"Play next video"},T6:"Play now"});g.M(this,this.playButton);this.playButton.gH(this.U.element);this.playButton.listen("click",this.g7,this);this.B.createServerVe(this.playButton.element,this.playButton,!0);(u=this.B.getVideoData())&&KAJ(this,u);this.D=new g.fy(function(){XJJ(G)},500);
g.M(this,this.D);this.uE();this.V(Z,"autonavvisibility",this.uE);this.B.S("web_autonav_color_transition")&&(this.V(Z,"autonavchange",this.E1),this.V(Z,"onAutonavCoundownStarted",this.Yci))},mG=function(Z){return g.OQ(Z.player)&&Z.TY()&&!Z.T},Yw=function(Z){var u=Z.B.RT(!0,Z.B.isFullscreen());
g.Bv(Z.container.element,"ytp-autonav-endscreen-small-mode",Z.lV(u));g.Bv(Z.container.element,"ytp-autonav-endscreen-is-premium",!!Z.suggestion&&!!Z.suggestion.h3n);g.Bv(Z.B.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!Z.B.Dv());g.Bv(Z.B.getRootNode(),"countdown-running",Z.nG());g.Bv(Z.container.element,"ytp-player-content",Z.B.Dv());g.O0(Z.overlay.element,{width:u.width+"px"});if(!Z.nG()){Z.B.Dv()?V5k(Z,Math.round(fVd(Z)/1E3)):V5k(Z);u=!!Z.suggestion&&!!Z.suggestion.zA;var G=Z.B.Dv()||
!u;g.Bv(Z.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!G&&u);g.Bv(Z.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",G&&!u);Z.U.s7(Z.B.Dv());g.Bv(Z.element,"ytp-enable-w2w-color-transitions",n8e(Z))}},qKi=function(Z){Z=Z.J();
return Z.Du&&!Z.DJ&&!Z.disableOrganicUi},DEs=function(Z){return Z.isBackground()&&Z.V4()},J8=function(Z){var u=Z.Dv();
u!==Z.K&&(Z.K=u,uXH(Z.player))},M5J=function(Z,u){u=lVi(Z,u);
var G=Math,y=G.min;var q=(0,g.MJ)()-Z.U;G=y.call(G,q,u);u=u===0?1:Math.min(G/u,1);Z.G.setAttribute("stroke-dashoffset",""+-211*(u+1));u>=1&&Z.nG()&&Z.api.getPresentingPlayerType()!==3?Z.select(!0):Z.nG()&&Z.j.start()},NsH=function(Z){var u=Z.player.getVideoData();
if(!u||Z.j===u.mH&&Z.U===u.LV)return!1;Z.j=u.mH;Z.U=u.LV;return!0},KX=function(Z){g.P.call(this,{Z:"div",
Il:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},L:[{Z:"div",Y:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{Z:"span",Y:"ytp-upnext-top",L:[{Z:"span",Y:"ytp-upnext-header",T6:"Up Next"},{Z:"span",Y:"ytp-upnext-title",T6:"{{title}}"},{Z:"span",Y:"ytp-upnext-author",T6:"{{author}}"}]},{Z:"a",Y:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{Z:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
L:[{Z:"circle",Y:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Z:"circle",Y:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Z:"path",Y:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Z:"span",Y:"ytp-upnext-bottom",L:[{Z:"span",Y:"ytp-upnext-cancel"},{Z:"span",Y:"ytp-upnext-paused",
T6:"Auto-play is paused"}]}]});this.api=Z;this.cancelButton=null;this.G=this.Di("ytp-svg-autoplay-ring");this.T=this.notification=this.j=this.suggestion=null;this.D=new g.fy(this.Rn,5E3,this);this.U=0;var u=this.Di("ytp-upnext-cancel");this.cancelButton=new g.P({Z:"button",Il:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancel auto-play"},T6:"Cancel"});g.M(this,this.cancelButton);this.cancelButton.listen("click",this.Tk,this);this.cancelButton.gH(u);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.M(this,this.D);this.api.createClientVe(this.element,this,18788);u=this.Di("ytp-upnext-autoplay-icon");this.V(u,"click",this.t4);this.api.createClientVe(u,this,115130);this.qf();this.V(Z,"autonavvisibility",this.qf);this.V(Z,"mdxnowautoplaying",this.fe6);this.V(Z,"mdxautoplaycanceled",this.ZKu);g.Bv(this.element,"ytp-upnext-mobile",this.api.J().U)},mEi=function(Z,u){Z.pV("onAutonavCoundownStarted",u)},XE=function(Z){h8.call(this,Z,"videowall-endscreen");
var u=this;this.B=Z;this.T=0;this.stills=[];this.D=this.videoData=null;this.G=this.K=!1;this.C=null;this.U=new g.Ch(this);g.M(this,this.U);this.X=new g.fy(function(){g.AM(u.element,"ytp-show-tiles")},0);
g.M(this,this.X);var G=new g.P({Z:"button",Il:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Previous"},L:[g.c$()]});g.M(this,G);G.gH(this.element);G.listen("click",this.gW,this);this.table=new g.Dw({Z:"div",Y:"ytp-endscreen-content"});g.M(this,this.table);this.table.gH(this.element);G=new g.P({Z:"button",Il:["ytp-button","ytp-endscreen-next"],N:{"aria-label":"Next"},L:[g.l1()]});g.M(this,G);G.gH(this.element);G.listen("click",this.ut,this);Z.getVideoData().LV?this.j=new dq(Z,!0):this.j=
new KX(Z);g.M(this,this.j);g.l7(this.player,this.j.element,4);Z.createClientVe(this.element,this,158789);this.hide()};
g.Jk.prototype.s_=g.$r(6,function(){return this.app.s_()});
g.cj.prototype.s_=g.$r(5,function(){return this.getVideoData().DE});
g.aw.prototype.mA=g.$r(4,function(Z){this.N6().mA(Z)});
g.ZH.prototype.mA=g.$r(3,function(Z){this.XM!==Z&&(this.XM=Z,this.LW())});
g.I(lR,g.P);lR.prototype.select=function(){this.B.CY(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dk||void 0)&&this.B.logClick(this.element)};
lR.prototype.onClick=function(Z){g.kI(Z,this.B,this.j,this.suggestion.sessionData||void 0)&&this.select()};
lR.prototype.onKeyPress=function(Z){switch(Z.keyCode){case 13:case 32:Z.defaultPrevented||(this.select(),Z.preventDefault())}};g.I(dq,g.P);g.D=dq.prototype;g.D.im=function(Z){this.suggestion!==Z&&(this.suggestion=Z,g.an(this.j,Z),this.playButton.updateValue("url",this.suggestion.yr()),Yw(this))};
g.D.nG=function(){return this.T>0};
g.D.gx=function(){this.nG()||(this.T=Date.now(),XJJ(this),mEi(this.B,fVd(this)),g.Bv(this.B.getRootNode(),"countdown-running",this.nG()))};
g.D.bF=function(){this.F7();XJJ(this);var Z=this.j.Di("ytp-autonav-endscreen-upnext-header");Z&&g.vJ(Z,"Up next")};
g.D.F7=function(){this.nG()&&(this.D.stop(),this.T=0)};
g.D.select=function(Z){this.B.nextVideo(!1,Z===void 0?!1:Z);this.F7()};
g.D.g7=function(Z){g.kI(Z,this.B)&&(Z.currentTarget===this.playButton.element?this.B.logClick(this.playButton.element):Z.currentTarget===this.j.Di("ytp-autonav-endscreen-link-container")&&(Z=this.j.Di("ytp-autonav-endscreen-link-container"),this.B.logVisibility(Z,!0),this.B.logClick(Z)),this.G?(this.B.pV("innertubeCommand",this.G),this.F7()):this.select())};
g.D.U1=function(){this.B.logClick(this.cancelButton.element);g.i5(this.B,!0);this.cancelCommand&&this.B.pV("innertubeCommand",this.cancelCommand)};
g.D.onVideoDataChange=function(Z,u){KAJ(this,u);Z=u.getWatchNextResponse();var G,y;Z=(G=dEe(Z))==null?void 0:(y=G.cancelButton)==null?void 0:y.buttonRenderer;this.cancelCommand=Z==null?void 0:Z.command};
g.D.Yci=function(Z){if(n8e(this)){var u=this.B.getVideoData().watchToWatchTransitionRenderer,G=u==null?void 0:u.fromColorPaletteDark;u=u==null?void 0:u.toColorPaletteDark;if(G&&u){var y=this.element;y.style.setProperty("--w2w-start-background-color",g.py(G.surgeColor));y.style.setProperty("--w2w-start-primary-text-color",g.py(G.primaryTitleColor));y.style.setProperty("--w2w-start-secondary-text-color",g.py(G.secondaryTitleColor));y.style.setProperty("--w2w-end-background-color",g.py(u.surgeColor));
y.style.setProperty("--w2w-end-primary-text-color",g.py(u.primaryTitleColor));y.style.setProperty("--w2w-end-secondary-text-color",g.py(u.secondaryTitleColor));y.style.setProperty("--w2w-animation-duration",Z+"ms")}g.Bv(this.element,"ytp-w2w-animate",!0)}};
g.D.E1=function(Z){this.B.S("web_autonav_color_transition")&&Z!==2&&g.Bv(this.element,"ytp-w2w-animate",!1)};
g.D.uE=function(){var Z=this.B.Dv();this.X&&this.U7!==Z&&this.s7(Z);Yw(this);this.B.logVisibility(this.container.element,Z);this.B.logVisibility(this.cancelButton.element,Z);this.B.logVisibility(this.j.Di("ytp-autonav-endscreen-link-container"),Z);this.B.logVisibility(this.playButton.element,Z)};
g.D.lV=function(Z){return Z.width<400||Z.height<459};g.I(h8,g.P);g.D=h8.prototype;g.D.create=function(){this.created=!0};
g.D.destroy=function(){this.created=!1};
g.D.TY=function(){return!1};
g.D.Dv=function(){return!1};
g.D.yY=function(){return!1};g.I(KX,g.P);g.D=KX.prototype;g.D.Rn=function(){this.notification&&(this.D.stop(),this.SI(this.T),this.T=null,this.notification.close(),this.notification=null)};
g.D.im=function(Z){this.suggestion=Z;g.an(this,Z,"hqdefault.jpg")};
g.D.qf=function(){this.s7(this.api.Dv());this.api.logVisibility(this.element,this.api.Dv());this.api.logVisibility(this.Di("ytp-upnext-autoplay-icon"),this.api.Dv());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Dv())};
g.D.aen=function(){window.focus();this.Rn()};
g.D.gx=function(Z){var u=this;this.nG()||(g.$J("a11y-announce","Up Next "+this.suggestion.title),this.U=(0,g.MJ)(),this.j=new g.fy(function(){M5J(u,Z)},25),M5J(this,Z),mEi(this.api,lVi(this,Z)));
g.w4(this.element,"ytp-upnext-autoplay-paused")};
g.D.hide=function(){g.P.prototype.hide.call(this)};
g.D.nG=function(){return!!this.j};
g.D.bF=function(){this.F7();this.U=(0,g.MJ)();M5J(this);g.AM(this.element,"ytp-upnext-autoplay-paused")};
g.D.F7=function(){this.nG()&&(this.j.dispose(),this.j=null)};
g.D.select=function(Z){Z=Z===void 0?!1:Z;if(this.api.J().S("autonav_notifications")&&Z&&window.Notification&&typeof document.hasFocus==="function"){var u=Notification.permission;u==="default"?Notification.requestPermission():u!=="granted"||document.hasFocus()||(this.Rn(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.B7()}),this.T=this.V(this.notification,"click",this.aen),this.D.start())}this.F7();this.api.nextVideo(!1,Z)};
g.D.t4=function(Z){!g.Sp(this.cancelButton.element,Z.target)&&g.kI(Z,this.api)&&(this.api.Dv()&&this.api.logClick(this.Di("ytp-upnext-autoplay-icon")),this.select())};
g.D.Tk=function(){this.api.Dv()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.i5(this.api,!0)};
g.D.fe6=function(Z){this.api.getPresentingPlayerType();this.show();this.gx(Z)};
g.D.ZKu=function(){this.api.getPresentingPlayerType();this.F7();this.hide()};
g.D.tT=function(){this.F7();this.Rn();g.P.prototype.tT.call(this)};g.I(VO,h8);g.D=VO.prototype;g.D.create=function(){h8.prototype.create.call(this);this.D.V(this.player,"appresize",this.J8);this.D.V(this.player,"onVideoAreaChange",this.J8);this.D.V(this.player,"videodatachange",this.onVideoDataChange);this.D.V(this.player,"autonavchange",this.fq);this.D.V(this.player,"onAutonavCancelled",this.O1);this.onVideoDataChange()};
g.D.show=function(){h8.prototype.show.call(this);(this.X||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.i5(this.player,!1);g.OQ(this.player)&&this.TY()&&!this.T?(Da(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||DEs(this.player.Ox())&&this.player.S("web_player_pip_logging_fix")?this.j.select(!0):this.j.gx():this.videoData.autonavState===3&&this.j.bF()):(g.i5(this.player,!0),Da(this));this.J8()};
g.D.hide=function(){h8.prototype.hide.call(this);this.j.bF();Da(this)};
g.D.J8=function(){var Z=this.player.RT(!0,this.player.isFullscreen());Da(this);Yw(this.U);g.Bv(this.element,"ytp-autonav-cancelled-small-mode",this.lV(Z));g.Bv(this.element,"ytp-autonav-cancelled-tiny-mode",this.E2(Z));g.Bv(this.element,"ytp-autonav-cancelled-mini-mode",Z.width<=400||Z.height<=360);this.overlay&&g.O0(this.overlay.element,{width:Z.width+"px"});if(!this.G)for(Z=0;Z<this.videos.length;Z++)g.Bv(this.videos[Z].element,"ytp-suggestion-card-with-margin",Z%2===1)};
g.D.onVideoDataChange=function(){var Z=this.player.getVideoData();if(this.videoData!==Z&&Z){this.videoData=Z;Z=this.videoData.suggestions;var u=g.oJ(this.videoData);u&&(this.j.im(u),this.j!==this.U&&this.U.im(u));if(Z&&Z.length)for(u=0;u<YKw.length;++u){var G=YKw[u];if(Z&&Z[G]){this.videos[u]=new lR(this.player);var y=this.videos[u];G=Z[G];y.suggestion!==G&&(y.suggestion=G,g.an(y,G));g.M(this,this.videos[u]);this.videos[u].gH(this.K.element)}}this.J8()}};
g.D.fq=function(Z){Z===1?(this.X=!1,this.T=this.videoData.clientPlaybackNonce,this.j.F7(),this.U7&&this.J8()):(this.X=!0,this.Dv()&&(Z===2?this.j.gx():Z===3&&this.j.bF()))};
g.D.O1=function(Z){Z?this.fq(1):(this.T=null,this.X=!1)};
g.D.TY=function(){return this.videoData.autonavState!==1};
g.D.lV=function(Z){return(Z.width<910||Z.height<459)&&!this.E2(Z)&&!(Z.width<=400||Z.height<=360)};
g.D.E2=function(Z){return Z.width<800&&!(Z.width<=400||Z.height<=360)};
g.D.Dv=function(){return this.U7&&g.OQ(this.player)&&this.TY()&&!this.T};
var YKw=[1,3,2,4];g.I(G$w,h8);g.D=G$w.prototype;g.D.create=function(){h8.prototype.create.call(this);var Z=this.player.getVideoData();Z&&(this.videoData=Z);this.He();this.U.V(this.player,"appresize",this.He);this.U.V(this.player,"onVideoAreaChange",this.He);this.U.V(this.player,"videodatachange",this.onVideoDataChange);this.U.V(this.player,"autonavchange",this.Se);this.U.V(this.player,"onAutonavCancelled",this.DP);Z=this.videoData.autonavState;Z!==this.K&&this.Se(Z);this.U.V(this.element,"transitionend",this.A4)};
g.D.destroy=function(){g.Xp(this.U);g.rT(this.stills);this.stills=[];h8.prototype.destroy.call(this);g.w4(this.element,"ytp-show-tiles");this.G.stop();this.K=this.videoData.autonavState};
g.D.TY=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var Z=this.U7;h8.prototype.show.call(this);g.w4(this.element,"ytp-show-tiles");this.player.J().U?g.Ec(this.G):this.G.start();(this.D||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.i5(this.player,!1);mG(this)?(MW(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||DEs(this.player.Ox())&&this.player.S("web_player_pip_logging_fix")?this.j.select(!0):this.j.gx():this.videoData.autonavState===3&&this.j.bF()):(g.i5(this.player,!0),MW(this));Z!==this.U7&&
this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var Z=this.U7;h8.prototype.hide.call(this);this.j.bF();MW(this);Z!==this.U7&&this.player.logVisibility(this.element,!1)};
g.D.A4=function(Z){Z.target===this.element&&this.He()};
g.D.He=function(){var Z,u,G,y;var q=((Z=this.videoData)==null?0:(u=Z.suggestions)==null?0:u.length)?(G=this.videoData)==null?void 0:G.suggestions:[(y=this.videoData)==null?void 0:g.oJ(y)];if(q.length){u=this.B.RT(!0,this.B.isFullscreen());Z=Math.floor((u.width-64+16)/(g.Oi(u.width*.27,250,450)+16));u=Math.min(3,Math.floor((u.height-64)/((u.width-64-(Z-1)*16)/Z*.5625+70)));g.hF(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.AM(this.element,"ytp-modern-endscreen-limit-rows-"+u);g.Bv(this.element,"ytp-modern-endscreen-single-item",Z===1);g.Bv(this.element,"ytp-modern-endscreen-row-0",u===0);Z=this.table.element;Z.ariaLive="polite";this.j.im(g.oJ(this.videoData));this.j instanceof dq&&Yw(this.j);g.Bv(this.element,"ytp-endscreen-takeover",mG(this));MW(this);u=0;Z.ariaBusy="true";G=q.length;for(y=0;y<G;y++){var N=y%G,e=this.stills[y];e||(e=new g.RF(this.player),this.stills[y]=e,Z.appendChild(e.element));g.kb7(e,q[N]);u++}this.stills.length=
u}};
g.D.onVideoDataChange=function(){var Z=this.player.getVideoData(1);this.videoData!==Z&&(Z!=null&&g.oJ(Z)?(this.videoData=Z,this.He()):this.player.ET("missg",{vid:(Z==null?void 0:Z.videoId)||"",cpn:(Z==null?void 0:Z.clientPlaybackNonce)||""}))};
g.D.yY=function(){return this.j.nG()};
g.D.Se=function(Z){Z===1?(this.D=!1,this.T=this.videoData.clientPlaybackNonce,this.j.F7(),this.U7&&this.He()):(this.D=!0,this.U7&&mG(this)&&(Z===2?this.j.gx():Z===3&&this.j.bF()))};
g.D.DP=function(Z){if(Z){for(Z=0;Z<this.stills.length;Z++)this.B.logVisibility(this.stills[Z].element,!0);this.Se(1)}else this.T=null,this.D=!1;this.He()};
g.D.Dv=function(){return this.U7&&mG(this)};g.I(e8i,h8);e8i.prototype.Vn=function(){var Z=this.player.getVideoData();this.j.update({profilePicture:Z.profilePicture,author:Z.author});this.subscribeButton.channelId=Z.Pg;var u=this.subscribeButton;Z.subscribed?u.j():u.U()};g.I(xw,g.P);xw.prototype.select=function(){this.api.CY(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dk||void 0)&&this.api.logClick(this.element)};
xw.prototype.onClick=function(Z){if(g.PC(this.api.J())&&this.api.S("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var u=this.suggestion.yr(),G={};g.LP(this.api,G);u=g.ku(u,G);g.qg(u,this.api,Z)}else g.kI(Z,this.api,this.U,this.suggestion.sessionData||void 0)&&this.select()};
xw.prototype.onKeyPress=function(Z){switch(Z.keyCode){case 13:case 32:Z.defaultPrevented||(this.select(),Z.preventDefault())}};
xw.prototype.onVideoDataChange=function(){var Z=this.api.getVideoData(),u=this.api.J();this.U=Z.Wc?!1:u.D};g.I(XE,h8);g.D=XE.prototype;g.D.create=function(){h8.prototype.create.call(this);var Z=this.player.getVideoData();Z&&(this.videoData=Z);this.jl();this.U.V(this.player,"appresize",this.jl);this.U.V(this.player,"onVideoAreaChange",this.jl);this.U.V(this.player,"videodatachange",this.onVideoDataChange);this.U.V(this.player,"autonavchange",this.Xk);this.U.V(this.player,"onAutonavCancelled",this.zk);Z=this.videoData.autonavState;Z!==this.C&&this.Xk(Z);this.U.V(this.element,"transitionend",this.q5)};
g.D.destroy=function(){g.Xp(this.U);g.rT(this.stills);this.stills=[];h8.prototype.destroy.call(this);g.w4(this.element,"ytp-show-tiles");this.X.stop();this.C=this.videoData.autonavState};
g.D.TY=function(){return this.videoData.autonavState!==1};
g.D.show=function(){var Z=this.U7;h8.prototype.show.call(this);g.w4(this.element,"ytp-show-tiles");this.player.J().U?g.Ec(this.X):this.X.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.i5(this.player,!1);nX(this)?(J8(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||DEs(this.player.Ox())&&this.player.S("web_player_pip_logging_fix")?this.j.select(!0):this.j.gx():this.videoData.autonavState===3&&this.j.bF()):(g.i5(this.player,!0),J8(this));Z!==this.U7&&
this.player.logVisibility(this.element,!0)};
g.D.hide=function(){var Z=this.U7;h8.prototype.hide.call(this);this.j.bF();J8(this);Z!==this.U7&&this.player.logVisibility(this.element,!1)};
g.D.q5=function(Z){Z.target===this.element&&this.jl()};
g.D.jl=function(){var Z,u,G,y;var q=((Z=this.videoData)==null?0:(u=Z.suggestions)==null?0:u.length)?(G=this.videoData)==null?void 0:G.suggestions:[(y=this.videoData)==null?void 0:g.oJ(y)];if(q.length){g.AM(this.element,"ytp-endscreen-paginate");var N=this.B.RT(!0,this.B.isFullscreen());if(Z=g.$o(this.B))Z=Z.xj()?48:32,N.width-=Z*2;var e=N.width/N.height;y=96/54;u=Z=2;var h=Math.max(N.width/96,2),d=Math.max(N.height/54,2);G=q.length;var K=G*4;for(K-=4;K>0&&(Z<h||u<d);){var f=Z/2,V=u/2,X=Z<=h-2&&K>=
V*4,n=u<=d-2&&K>=f*4;if((f+1)/V*y/e>e/(f/(V+1)*y)&&n)K-=f*4,u+=2;else if(X)K-=V*4,Z+=2;else if(n)K-=f*4,u+=2;else break}y=!1;K>=12&&G*4-K<=6&&(u>=4||Z>=4)&&(y=!0);K=Z*96;h=u*54;e=K/h<e?N.height/h:N.width/K;e=Math.min(e,2);K=Math.floor(Math.min(N.width,K*e));h=Math.floor(Math.min(N.height,h*e));N=this.table.element;N.ariaLive="polite";g.wM(N,K,h);g.O0(N,{marginLeft:K/-2+"px",marginTop:h/-2+"px"});this.j.im(g.oJ(this.videoData));this.j instanceof dq&&Yw(this.j);g.Bv(this.element,"ytp-endscreen-takeover",
nX(this));J8(this);K+=4;h+=4;e=0;N.ariaBusy="true";for(d=0;d<Z;d++)for(f=0;f<u;f++)if(V=e,n=0,y&&d>=Z-2&&f>=u-2?n=1:f%2===0&&d%2===0&&(f<2&&d<2?f===0&&d===0&&(n=2):n=2),V=g.wwJ(V+this.T,G),n!==0){X=this.stills[e];X||(X=new xw(this.player),this.stills[e]=X,N.appendChild(X.element));var l=Math.floor(h*f/u),Y=Math.floor(K*d/Z),E=Math.floor(h*(f+n)/u)-l-4,W=Math.floor(K*(d+n)/Z)-Y-4;g.eU(X.element,Y,l);g.wM(X.element,W,E);g.O0(X.element,"transitionDelay",(f+d)/20+"s");g.Bv(X.element,"ytp-videowall-still-mini",
n===1);g.Bv(X.element,"ytp-videowall-still-large",n>2);n=Math.max(W,E);g.Bv(X.element,"ytp-videowall-still-round-large",n>=256);g.Bv(X.element,"ytp-videowall-still-round-medium",n>96&&n<256);g.Bv(X.element,"ytp-videowall-still-round-small",n<=96);V=q[V];X.suggestion!==V&&(X.suggestion=V,n=X.api.J(),l=g.c_(X.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.an(X,V,l),g.PC(n)&&!X.api.S("web_player_log_click_before_generating_ve_conversion_params")&&(n=V.yr(),l={},g.WX(X.api,"addEmbedsConversionTrackingParams",
[l]),n=g.ku(n,l),X.updateValue("url",n)),(V=(V=V.sessionData)&&V.itct)&&X.api.setTrackingParams(X.element,V));e++}N.ariaBusy="false";g.Bv(this.element,"ytp-endscreen-paginate",e<G);for(q=this.stills.length-1;q>=e;q--)Z=this.stills[q],g.qr(Z.element),g.H8(Z);this.stills.length=e}};
g.D.onVideoDataChange=function(){var Z=this.player.getVideoData(1);this.videoData!==Z&&(Z!=null&&g.oJ(Z)?(this.T=0,this.videoData=Z,this.jl()):this.player.ET("missg",{vid:(Z==null?void 0:Z.videoId)||"",cpn:(Z==null?void 0:Z.clientPlaybackNonce)||""}))};
g.D.ut=function(){this.T+=this.stills.length;this.jl()};
g.D.gW=function(){this.T-=this.stills.length;this.jl()};
g.D.yY=function(){return this.j.nG()};
g.D.Xk=function(Z){Z===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.F7(),this.U7&&this.jl()):(this.G=!0,this.U7&&nX(this)&&(Z===2?this.j.gx():Z===3&&this.j.bF()))};
g.D.zk=function(Z){if(Z){for(Z=0;Z<this.stills.length;Z++)this.B.logVisibility(this.stills[Z].element,!0);this.Xk(1)}else this.D=null,this.G=!1;this.jl()};
g.D.Dv=function(){return this.U7&&nX(this)};g.I(ywi,g.P);g.D=ywi.prototype;g.D.xX=function(){switch(this.buttonType){case 1:var Z="Watch again on YouTube";var u=156915;break;case 2:Z="Continue watching on YouTube";u=156942;break;default:Z="Continue watching on YouTube",u=156942}this.update({content:Z});this.B.hasVe(this.element)&&this.B.destroyVe(this.element);this.B.createClientVe(this.element,this,u)};
g.D.onClick=function(Z){this.B.S("web_player_log_click_before_generating_ve_conversion_params")&&this.B.logClick(this.element);g.qg(this.getVideoUrl(),this.B,Z);this.B.S("web_player_log_click_before_generating_ve_conversion_params")||this.B.logClick(this.element)};
g.D.getVideoUrl=function(){var Z=!0;switch(this.buttonType){case 1:Z=!0;break;case 2:Z=!1}Z=this.B.getVideoUrl(Z,!1,!1,!0);var u=this.B.J();if(g.PC(u)){var G={};g.PC(u)&&g.WX(this.B,"addEmbedsConversionTrackingParams",[G]);Z=g.ku(Z,G)}return Z};
g.D.logVisibility=function(){this.B.logVisibility(this.element,this.U7&&this.Fn)};
g.D.show=function(){g.P.prototype.show.call(this);this.logVisibility()};
g.D.hide=function(){g.P.prototype.hide.call(this);this.logVisibility()};
g.D.Uc=function(Z){g.P.prototype.Uc.call(this,Z);this.logVisibility()};g.I(fX,h8);fX.prototype.hasSuggestions=function(){var Z;return(Z=this.j)==null?void 0:Z.hasSuggestions()};
fX.prototype.show=function(){if(this.player.getPlayerState()!==3){h8.prototype.show.call(this);var Z=this.U;if(Z){var u=this.j.hasSuggestions();g.Bv(this.element,"ytp-shorts-branded-ui",u);u?Z.show():Z.hide()}var G;(G=g.$o(this.player))==null||G.mA(!0);this.player.logVisibility(this.element,!0);this.watchButton.Uc(!0)}};
fX.prototype.hide=function(){h8.prototype.hide.call(this);var Z;(Z=g.$o(this.player))==null||Z.mA(!1);this.player.logVisibility(this.element,!1);this.watchButton.Uc(!1)};g.I(h8d,g.gC);g.D=h8d.prototype;g.D.aY=function(){var Z=this.player.getVideoData(),u=Z.mutedAutoplay&&(Z.limitedPlaybackDurationInSeconds>0||Z.endSeconds>0||Z.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!u)return!0;var G;var y=!!((Z==null?0:g.oJ(Z))||(Z==null?0:(G=Z.suggestions)==null?0:G.length));y=!qKi(this.player)||y;Z=Z.wb;G=this.player.VP();return y&&!Z&&!G&&!u};
g.D.Dv=function(){return this.endScreen.Dv()};
g.D.tK1=function(){return this.Dv()?this.endScreen.yY():!1};
g.D.tT=function(){this.player.fK("endscreen");g.gC.prototype.tT.call(this)};
g.D.load=function(){var Z=this.player.getVideoData();var u=Z.transitionEndpointAtEndOfStream;if(u&&u.videoId){var G=this.player.gt().zJ.get("heartbeat"),y=g.oJ(Z);!y||u.videoId!==y.videoId||Z.sV?(this.player.CY(u.videoId,void 0,void 0,!0,!0,u),G&&G.zs("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),Z=!0):Z=!1}else Z=!1;Z||(g.gC.prototype.load.call(this),this.endScreen.show())};
g.D.unload=function(){g.gC.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.D.onCueRangeEnter=function(Z){this.aY()&&(this.endScreen.created||this.endScreen.create(),Z.getId()==="load"&&this.load())};
g.D.onCueRangeExit=function(Z){Z.getId()==="load"&&this.loaded&&this.unload()};
g.D.onVideoDataChange=function(){xEi(this);this.T&&NsH(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new VO(this.player):this.endScreen=new XE(this.player),g.M(this,this.endScreen),g.l7(this.player,this.endScreen.element,4))};g.on("endscreen",h8d);})(_yt_player);
